// @generated by schema/goldens.py -- do not edit.
//
// Both test suites assert these same field values against the same
// schema/golden/*.bin files, then re-encode and require the bytes back.

#pragma once

#include <cstddef>
#include <cstdint>
#include <string>

#include "wire/generated.hpp"
#include "golden_support.hpp"

namespace mdstack::golden {

using namespace mdstack::wire;

// One AddOrder. Anchors the AddOrder block and the packet header.
inline std::string check_add_order(const std::byte* buf, std::size_t len) {
    auto h = PacketHeaderDecoder::wrap(buf, len);
    if (!h) return "packet header: wrap failed";
    CHECK_EQ("packet.schemaId", h->schema_id(), 1);
    CHECK_EQ("packet.version", h->version(), 1);
    CHECK_EQ("packet.messageCount", h->message_count(), 1);
    CHECK_EQ("packet.channel", h->channel(), 0);
    CHECK_EQ("packet.flags", h->flags(), 0);
    CHECK_EQ("packet.firstSequence", h->first_sequence(), 1048576ULL);
    CHECK_EQ("packet.sendTimestampNs", h->send_timestamp_ns(), 1702361767298204934ULL);
    CHECK_EQ("packet.isSnapshot", h->is_snapshot(), false);
    std::size_t pos = kPacketHeaderLen;
    const std::uint64_t first_seq = 1048576ULL;
    // message 0
    {
        auto d = AddOrderDecoder::wrap(buf + pos, len - pos);
        if (!d) return "message 0: not a decodable AddOrder";
        CHECK_EQ("message 0 sequence", static_cast<std::uint64_t>(first_seq + 0ULL), 1048576ULL);
        CHECK_EQ("message 0.order_id", d->order_id(), 4294967298ULL);
        CHECK_EQ("message 0.price", d->price(), 1012500);
        CHECK_EQ("message 0.quantity", d->quantity(), 250);
        CHECK_EQ("message 0.symbol_id", d->symbol_id(), 7);
        {
            auto e = d->side();
            if (!e) return "message 0.side: undefined enum value";
            CHECK_EQ("message 0.side", static_cast<int>(*e), static_cast<int>(Side::kBid));
        }
        pos += d->total_len();
    }
    if (pos != len) return "trailing bytes past the last message";
    return "";
}

// Re-encodes `add_order` from the same values check_add_order asserts.
inline std::size_t build_add_order(std::byte* out, std::size_t cap, std::string& err) {
    auto ph = encode_packet_header(out, cap
        , static_cast<std::uint8_t>(0)
        , static_cast<std::uint8_t>(0)
        , 1048576ULL
        , 1702361767298204934ULL
    );
    if (!ph) { err = "packet header did not fit"; return 0; }
    std::size_t pos = *ph;
    // message 0
    {
        auto n = encode_add_order(out + pos, cap - pos
            , static_cast<std::uint64_t>(4294967298ULL)
            , static_cast<std::int64_t>(1012500)
            , static_cast<std::uint32_t>(250ULL)
            , static_cast<std::uint16_t>(7ULL)
            , Side::kBid
        );
        if (!n) { err = "message 0 did not fit"; return 0; }
        pos += *n;
    }
    if (!patch_message_count(out, cap, static_cast<std::uint16_t>(1)))
        { err = "could not patch messageCount"; return 0; }
    return pos;
}

// A Replace, which loses queue priority. channel=1 exercises the B arm.
inline std::string check_modify_order(const std::byte* buf, std::size_t len) {
    auto h = PacketHeaderDecoder::wrap(buf, len);
    if (!h) return "packet header: wrap failed";
    CHECK_EQ("packet.schemaId", h->schema_id(), 1);
    CHECK_EQ("packet.version", h->version(), 1);
    CHECK_EQ("packet.messageCount", h->message_count(), 1);
    CHECK_EQ("packet.channel", h->channel(), 1);
    CHECK_EQ("packet.flags", h->flags(), 0);
    CHECK_EQ("packet.firstSequence", h->first_sequence(), 1048577ULL);
    CHECK_EQ("packet.sendTimestampNs", h->send_timestamp_ns(), 1702361767298204934ULL);
    CHECK_EQ("packet.isSnapshot", h->is_snapshot(), false);
    std::size_t pos = kPacketHeaderLen;
    const std::uint64_t first_seq = 1048577ULL;
    // message 0
    {
        auto d = ModifyOrderDecoder::wrap(buf + pos, len - pos);
        if (!d) return "message 0: not a decodable ModifyOrder";
        CHECK_EQ("message 0 sequence", static_cast<std::uint64_t>(first_seq + 0ULL), 1048577ULL);
        CHECK_EQ("message 0.order_id", d->order_id(), 4294967298ULL);
        CHECK_EQ("message 0.new_price", d->new_price(), 1012600);
        CHECK_EQ("message 0.new_quantity", d->new_quantity(), 100);
        CHECK_EQ("message 0.symbol_id", d->symbol_id(), 7);
        {
            auto e = d->side();
            if (!e) return "message 0.side: undefined enum value";
            CHECK_EQ("message 0.side", static_cast<int>(*e), static_cast<int>(Side::kBid));
        }
        {
            auto e = d->reason();
            if (!e) return "message 0.reason: undefined enum value";
            CHECK_EQ("message 0.reason", static_cast<int>(*e), static_cast<int>(ModifyReason::kReplace));
        }
        pos += d->total_len();
    }
    if (pos != len) return "trailing bytes past the last message";
    return "";
}

// Re-encodes `modify_order` from the same values check_modify_order asserts.
inline std::size_t build_modify_order(std::byte* out, std::size_t cap, std::string& err) {
    auto ph = encode_packet_header(out, cap
        , static_cast<std::uint8_t>(1)
        , static_cast<std::uint8_t>(0)
        , 1048577ULL
        , 1702361767298204934ULL
    );
    if (!ph) { err = "packet header did not fit"; return 0; }
    std::size_t pos = *ph;
    // message 0
    {
        auto n = encode_modify_order(out + pos, cap - pos
            , static_cast<std::uint64_t>(4294967298ULL)
            , static_cast<std::int64_t>(1012600)
            , static_cast<std::uint32_t>(100ULL)
            , static_cast<std::uint16_t>(7ULL)
            , Side::kBid
            , ModifyReason::kReplace
        );
        if (!n) { err = "message 0 did not fit"; return 0; }
        pos += *n;
    }
    if (!patch_message_count(out, cap, static_cast<std::uint16_t>(1)))
        { err = "could not patch messageCount"; return 0; }
    return pos;
}

// The shortest message: a 12-byte block that leaves the next message 4-byte aligned.
inline std::string check_delete_order(const std::byte* buf, std::size_t len) {
    auto h = PacketHeaderDecoder::wrap(buf, len);
    if (!h) return "packet header: wrap failed";
    CHECK_EQ("packet.schemaId", h->schema_id(), 1);
    CHECK_EQ("packet.version", h->version(), 1);
    CHECK_EQ("packet.messageCount", h->message_count(), 1);
    CHECK_EQ("packet.channel", h->channel(), 0);
    CHECK_EQ("packet.flags", h->flags(), 0);
    CHECK_EQ("packet.firstSequence", h->first_sequence(), 1048578ULL);
    CHECK_EQ("packet.sendTimestampNs", h->send_timestamp_ns(), 1702361767298204934ULL);
    CHECK_EQ("packet.isSnapshot", h->is_snapshot(), false);
    std::size_t pos = kPacketHeaderLen;
    const std::uint64_t first_seq = 1048578ULL;
    // message 0
    {
        auto d = DeleteOrderDecoder::wrap(buf + pos, len - pos);
        if (!d) return "message 0: not a decodable DeleteOrder";
        CHECK_EQ("message 0 sequence", static_cast<std::uint64_t>(first_seq + 0ULL), 1048578ULL);
        CHECK_EQ("message 0.order_id", d->order_id(), 4294967298ULL);
        CHECK_EQ("message 0.symbol_id", d->symbol_id(), 7);
        {
            auto e = d->side();
            if (!e) return "message 0.side: undefined enum value";
            CHECK_EQ("message 0.side", static_cast<int>(*e), static_cast<int>(Side::kAsk));
        }
        pos += d->total_len();
    }
    if (pos != len) return "trailing bytes past the last message";
    return "";
}

// Re-encodes `delete_order` from the same values check_delete_order asserts.
inline std::size_t build_delete_order(std::byte* out, std::size_t cap, std::string& err) {
    auto ph = encode_packet_header(out, cap
        , static_cast<std::uint8_t>(0)
        , static_cast<std::uint8_t>(0)
        , 1048578ULL
        , 1702361767298204934ULL
    );
    if (!ph) { err = "packet header did not fit"; return 0; }
    std::size_t pos = *ph;
    // message 0
    {
        auto n = encode_delete_order(out + pos, cap - pos
            , static_cast<std::uint64_t>(4294967298ULL)
            , static_cast<std::uint16_t>(7ULL)
            , Side::kAsk
        );
        if (!n) { err = "message 0 did not fit"; return 0; }
        pos += *n;
    }
    if (!patch_message_count(out, cap, static_cast<std::uint16_t>(1)))
        { err = "could not patch messageCount"; return 0; }
    return pos;
}

// The longest fixed block, and the only message naming two orders.
inline std::string check_trade(const std::byte* buf, std::size_t len) {
    auto h = PacketHeaderDecoder::wrap(buf, len);
    if (!h) return "packet header: wrap failed";
    CHECK_EQ("packet.schemaId", h->schema_id(), 1);
    CHECK_EQ("packet.version", h->version(), 1);
    CHECK_EQ("packet.messageCount", h->message_count(), 1);
    CHECK_EQ("packet.channel", h->channel(), 0);
    CHECK_EQ("packet.flags", h->flags(), 0);
    CHECK_EQ("packet.firstSequence", h->first_sequence(), 1048579ULL);
    CHECK_EQ("packet.sendTimestampNs", h->send_timestamp_ns(), 1702361767298204934ULL);
    CHECK_EQ("packet.isSnapshot", h->is_snapshot(), false);
    std::size_t pos = kPacketHeaderLen;
    const std::uint64_t first_seq = 1048579ULL;
    // message 0
    {
        auto d = TradeDecoder::wrap(buf + pos, len - pos);
        if (!d) return "message 0: not a decodable Trade";
        CHECK_EQ("message 0 sequence", static_cast<std::uint64_t>(first_seq + 0ULL), 1048579ULL);
        CHECK_EQ("message 0.trade_id", d->trade_id(), 17);
        CHECK_EQ("message 0.aggressor_order_id", d->aggressor_order_id(), 4294967298ULL);
        CHECK_EQ("message 0.resting_order_id", d->resting_order_id(), 4294967299ULL);
        CHECK_EQ("message 0.price", d->price(), 1012500);
        CHECK_EQ("message 0.quantity", d->quantity(), 50);
        CHECK_EQ("message 0.symbol_id", d->symbol_id(), 7);
        {
            auto e = d->aggressor_side();
            if (!e) return "message 0.aggressor_side: undefined enum value";
            CHECK_EQ("message 0.aggressor_side", static_cast<int>(*e), static_cast<int>(Side::kAsk));
        }
        pos += d->total_len();
    }
    if (pos != len) return "trailing bytes past the last message";
    return "";
}

// Re-encodes `trade` from the same values check_trade asserts.
inline std::size_t build_trade(std::byte* out, std::size_t cap, std::string& err) {
    auto ph = encode_packet_header(out, cap
        , static_cast<std::uint8_t>(0)
        , static_cast<std::uint8_t>(0)
        , 1048579ULL
        , 1702361767298204934ULL
    );
    if (!ph) { err = "packet header did not fit"; return 0; }
    std::size_t pos = *ph;
    // message 0
    {
        auto n = encode_trade(out + pos, cap - pos
            , static_cast<std::uint64_t>(17ULL)
            , static_cast<std::uint64_t>(4294967298ULL)
            , static_cast<std::uint64_t>(4294967299ULL)
            , static_cast<std::int64_t>(1012500)
            , static_cast<std::uint32_t>(50ULL)
            , static_cast<std::uint16_t>(7ULL)
            , Side::kAsk
        );
        if (!n) { err = "message 0 did not fit"; return 0; }
        pos += *n;
    }
    if (!patch_message_count(out, cap, static_cast<std::uint16_t>(1)))
        { err = "could not patch messageCount"; return 0; }
    return pos;
}

// Idle-channel keepalive; the handler uses it to tell quiet from dead.
inline std::string check_heartbeat(const std::byte* buf, std::size_t len) {
    auto h = PacketHeaderDecoder::wrap(buf, len);
    if (!h) return "packet header: wrap failed";
    CHECK_EQ("packet.schemaId", h->schema_id(), 1);
    CHECK_EQ("packet.version", h->version(), 1);
    CHECK_EQ("packet.messageCount", h->message_count(), 1);
    CHECK_EQ("packet.channel", h->channel(), 1);
    CHECK_EQ("packet.flags", h->flags(), 0);
    CHECK_EQ("packet.firstSequence", h->first_sequence(), 1048580ULL);
    CHECK_EQ("packet.sendTimestampNs", h->send_timestamp_ns(), 1702361767298204934ULL);
    CHECK_EQ("packet.isSnapshot", h->is_snapshot(), false);
    std::size_t pos = kPacketHeaderLen;
    const std::uint64_t first_seq = 1048580ULL;
    // message 0
    {
        auto d = HeartbeatDecoder::wrap(buf + pos, len - pos);
        if (!d) return "message 0: not a decodable Heartbeat";
        CHECK_EQ("message 0 sequence", static_cast<std::uint64_t>(first_seq + 0ULL), 1048580ULL);
        CHECK_EQ("message 0.last_sequence", d->last_sequence(), 1048580);
        pos += d->total_len();
    }
    if (pos != len) return "trailing bytes past the last message";
    return "";
}

// Re-encodes `heartbeat` from the same values check_heartbeat asserts.
inline std::size_t build_heartbeat(std::byte* out, std::size_t cap, std::string& err) {
    auto ph = encode_packet_header(out, cap
        , static_cast<std::uint8_t>(1)
        , static_cast<std::uint8_t>(0)
        , 1048580ULL
        , 1702361767298204934ULL
    );
    if (!ph) { err = "packet header did not fit"; return 0; }
    std::size_t pos = *ph;
    // message 0
    {
        auto n = encode_heartbeat(out + pos, cap - pos
            , static_cast<std::uint64_t>(1048580ULL)
        );
        if (!n) { err = "message 0 did not fit"; return 0; }
        pos += *n;
    }
    if (!patch_message_count(out, cap, static_cast<std::uint16_t>(1)))
        { err = "could not patch messageCount"; return 0; }
    return pos;
}

// The publisher restarts its numbering.
inline std::string check_sequence_reset(const std::byte* buf, std::size_t len) {
    auto h = PacketHeaderDecoder::wrap(buf, len);
    if (!h) return "packet header: wrap failed";
    CHECK_EQ("packet.schemaId", h->schema_id(), 1);
    CHECK_EQ("packet.version", h->version(), 1);
    CHECK_EQ("packet.messageCount", h->message_count(), 1);
    CHECK_EQ("packet.channel", h->channel(), 0);
    CHECK_EQ("packet.flags", h->flags(), 0);
    CHECK_EQ("packet.firstSequence", h->first_sequence(), 1048581ULL);
    CHECK_EQ("packet.sendTimestampNs", h->send_timestamp_ns(), 1702361767298204934ULL);
    CHECK_EQ("packet.isSnapshot", h->is_snapshot(), false);
    std::size_t pos = kPacketHeaderLen;
    const std::uint64_t first_seq = 1048581ULL;
    // message 0
    {
        auto d = SequenceResetDecoder::wrap(buf + pos, len - pos);
        if (!d) return "message 0: not a decodable SequenceReset";
        CHECK_EQ("message 0 sequence", static_cast<std::uint64_t>(first_seq + 0ULL), 1048581ULL);
        CHECK_EQ("message 0.new_sequence", d->new_sequence(), 2097152);
        pos += d->total_len();
    }
    if (pos != len) return "trailing bytes past the last message";
    return "";
}

// Re-encodes `sequence_reset` from the same values check_sequence_reset asserts.
inline std::size_t build_sequence_reset(std::byte* out, std::size_t cap, std::string& err) {
    auto ph = encode_packet_header(out, cap
        , static_cast<std::uint8_t>(0)
        , static_cast<std::uint8_t>(0)
        , 1048581ULL
        , 1702361767298204934ULL
    );
    if (!ph) { err = "packet header did not fit"; return 0; }
    std::size_t pos = *ph;
    // message 0
    {
        auto n = encode_sequence_reset(out + pos, cap - pos
            , static_cast<std::uint64_t>(2097152ULL)
        );
        if (!n) { err = "message 0 did not fit"; return 0; }
        pos += *n;
    }
    if (!patch_message_count(out, cap, static_cast<std::uint16_t>(1)))
        { err = "could not patch messageCount"; return 0; }
    return pos;
}

// The repeating group, the snapshot flag on the packet header, and the last-fragment flag on the message. Orders are listed in queue order: a consumer that re-adds them in this order reproduces price-time priority exactly, which an aggregated snapshot could never do.
inline std::string check_snapshot_two_orders(const std::byte* buf, std::size_t len) {
    auto h = PacketHeaderDecoder::wrap(buf, len);
    if (!h) return "packet header: wrap failed";
    CHECK_EQ("packet.schemaId", h->schema_id(), 1);
    CHECK_EQ("packet.version", h->version(), 1);
    CHECK_EQ("packet.messageCount", h->message_count(), 1);
    CHECK_EQ("packet.channel", h->channel(), 0);
    CHECK_EQ("packet.flags", h->flags(), 1);
    CHECK_EQ("packet.firstSequence", h->first_sequence(), 1048582ULL);
    CHECK_EQ("packet.sendTimestampNs", h->send_timestamp_ns(), 1702361767298204934ULL);
    CHECK_EQ("packet.isSnapshot", h->is_snapshot(), true);
    std::size_t pos = kPacketHeaderLen;
    const std::uint64_t first_seq = 1048582ULL;
    // message 0
    {
        auto d = SnapshotDecoder::wrap(buf + pos, len - pos);
        if (!d) return "message 0: not a decodable Snapshot";
        CHECK_EQ("message 0 sequence", static_cast<std::uint64_t>(first_seq + 0ULL), 1048582ULL);
        CHECK_EQ("message 0.last_sequence", d->last_sequence(), 1048576);
        CHECK_EQ("message 0.symbol_id", d->symbol_id(), 7);
        CHECK_EQ("message 0.flags", d->flags(), 1);
        CHECK_EQ("message 0.orders.numInGroup", d->orders_count(), 2);
        CHECK_EQ("message 0.orders.blockLength", d->orders_block_length(), 24);
        {
            auto l = d->order(0);
            CHECK_EQ("message 0.orders[0].order_id", l.order_id(), 4294967298ULL);
            CHECK_EQ("message 0.orders[0].price", l.price(), 1012500);
            CHECK_EQ("message 0.orders[0].quantity", l.quantity(), 250);
            {
                auto e = l.side();
                if (!e) return "message 0.orders[0].side: undefined enum value";
                CHECK_EQ("message 0.orders[0].side", static_cast<int>(*e), static_cast<int>(Side::kBid));
            }
        }
        {
            auto l = d->order(1);
            CHECK_EQ("message 0.orders[1].order_id", l.order_id(), 4294967299ULL);
            CHECK_EQ("message 0.orders[1].price", l.price(), 1012600);
            CHECK_EQ("message 0.orders[1].quantity", l.quantity(), 100);
            {
                auto e = l.side();
                if (!e) return "message 0.orders[1].side: undefined enum value";
                CHECK_EQ("message 0.orders[1].side", static_cast<int>(*e), static_cast<int>(Side::kAsk));
            }
        }
        pos += d->total_len();
    }
    if (pos != len) return "trailing bytes past the last message";
    return "";
}

// Re-encodes `snapshot_two_orders` from the same values check_snapshot_two_orders asserts.
inline std::size_t build_snapshot_two_orders(std::byte* out, std::size_t cap, std::string& err) {
    auto ph = encode_packet_header(out, cap
        , static_cast<std::uint8_t>(0)
        , static_cast<std::uint8_t>(1)
        , 1048582ULL
        , 1702361767298204934ULL
    );
    if (!ph) { err = "packet header did not fit"; return 0; }
    std::size_t pos = *ph;
    // message 0
    {
        auto e = SnapshotEncoder::start(out + pos, cap - pos
            , 1048576ULL
            , static_cast<std::uint16_t>(7)
            , static_cast<std::uint8_t>(1)
        );
        if (!e) { err = "message 0 did not fit"; return 0; }
        if (!e->push_order(
                static_cast<std::uint64_t>(4294967298ULL)
                , static_cast<std::int64_t>(1012500)
                , static_cast<std::uint32_t>(250)
                , Side::kBid
        )) { err = "message 0 order 0 did not fit"; return 0; }
        if (!e->push_order(
                static_cast<std::uint64_t>(4294967299ULL)
                , static_cast<std::int64_t>(1012600)
                , static_cast<std::uint32_t>(100)
                , Side::kAsk
        )) { err = "message 0 order 1 did not fit"; return 0; }
        pos += e->finish();
    }
    if (!patch_message_count(out, cap, static_cast<std::uint16_t>(1)))
        { err = "could not patch messageCount"; return 0; }
    return pos;
}

// A snapshot of an empty book. numInGroup=0 must still carry the group header, or total_len walks the reader into the next message.
inline std::string check_snapshot_empty_group(const std::byte* buf, std::size_t len) {
    auto h = PacketHeaderDecoder::wrap(buf, len);
    if (!h) return "packet header: wrap failed";
    CHECK_EQ("packet.schemaId", h->schema_id(), 1);
    CHECK_EQ("packet.version", h->version(), 1);
    CHECK_EQ("packet.messageCount", h->message_count(), 1);
    CHECK_EQ("packet.channel", h->channel(), 0);
    CHECK_EQ("packet.flags", h->flags(), 1);
    CHECK_EQ("packet.firstSequence", h->first_sequence(), 1048583ULL);
    CHECK_EQ("packet.sendTimestampNs", h->send_timestamp_ns(), 1702361767298204934ULL);
    CHECK_EQ("packet.isSnapshot", h->is_snapshot(), true);
    std::size_t pos = kPacketHeaderLen;
    const std::uint64_t first_seq = 1048583ULL;
    // message 0
    {
        auto d = SnapshotDecoder::wrap(buf + pos, len - pos);
        if (!d) return "message 0: not a decodable Snapshot";
        CHECK_EQ("message 0 sequence", static_cast<std::uint64_t>(first_seq + 0ULL), 1048583ULL);
        CHECK_EQ("message 0.last_sequence", d->last_sequence(), 1048583);
        CHECK_EQ("message 0.symbol_id", d->symbol_id(), 9);
        CHECK_EQ("message 0.flags", d->flags(), 1);
        CHECK_EQ("message 0.orders.numInGroup", d->orders_count(), 0);
        CHECK_EQ("message 0.orders.blockLength", d->orders_block_length(), 24);
        pos += d->total_len();
    }
    if (pos != len) return "trailing bytes past the last message";
    return "";
}

// Re-encodes `snapshot_empty_group` from the same values check_snapshot_empty_group asserts.
inline std::size_t build_snapshot_empty_group(std::byte* out, std::size_t cap, std::string& err) {
    auto ph = encode_packet_header(out, cap
        , static_cast<std::uint8_t>(0)
        , static_cast<std::uint8_t>(1)
        , 1048583ULL
        , 1702361767298204934ULL
    );
    if (!ph) { err = "packet header did not fit"; return 0; }
    std::size_t pos = *ph;
    // message 0
    {
        auto e = SnapshotEncoder::start(out + pos, cap - pos
            , 1048583ULL
            , static_cast<std::uint16_t>(9)
            , static_cast<std::uint8_t>(1)
        );
        if (!e) { err = "message 0 did not fit"; return 0; }
        pos += e->finish();
    }
    if (!patch_message_count(out, cap, static_cast<std::uint16_t>(1)))
        { err = "could not patch messageCount"; return 0; }
    return pos;
}

// Six messages of five types behind one header, including a variable-length snapshot in the middle. This is the vector that proves a decoder can walk a batch: get any total_len wrong and every message after it is garbage. Batching is not an optimisation here, it is the framing the throughput target depends on.
inline std::string check_batch_mixed(const std::byte* buf, std::size_t len) {
    auto h = PacketHeaderDecoder::wrap(buf, len);
    if (!h) return "packet header: wrap failed";
    CHECK_EQ("packet.schemaId", h->schema_id(), 1);
    CHECK_EQ("packet.version", h->version(), 1);
    CHECK_EQ("packet.messageCount", h->message_count(), 6);
    CHECK_EQ("packet.channel", h->channel(), 0);
    CHECK_EQ("packet.flags", h->flags(), 0);
    CHECK_EQ("packet.firstSequence", h->first_sequence(), 4294967294ULL);
    CHECK_EQ("packet.sendTimestampNs", h->send_timestamp_ns(), 1702361767298204934ULL);
    CHECK_EQ("packet.isSnapshot", h->is_snapshot(), false);
    std::size_t pos = kPacketHeaderLen;
    const std::uint64_t first_seq = 4294967294ULL;
    // message 0
    {
        auto d = AddOrderDecoder::wrap(buf + pos, len - pos);
        if (!d) return "message 0: not a decodable AddOrder";
        CHECK_EQ("message 0 sequence", static_cast<std::uint64_t>(first_seq + 0ULL), 4294967294ULL);
        CHECK_EQ("message 0.order_id", d->order_id(), 8589934593ULL);
        CHECK_EQ("message 0.price", d->price(), 990000);
        CHECK_EQ("message 0.quantity", d->quantity(), 1000);
        CHECK_EQ("message 0.symbol_id", d->symbol_id(), 3);
        {
            auto e = d->side();
            if (!e) return "message 0.side: undefined enum value";
            CHECK_EQ("message 0.side", static_cast<int>(*e), static_cast<int>(Side::kBid));
        }
        pos += d->total_len();
    }
    // message 1
    {
        auto d = DeleteOrderDecoder::wrap(buf + pos, len - pos);
        if (!d) return "message 1: not a decodable DeleteOrder";
        CHECK_EQ("message 1 sequence", static_cast<std::uint64_t>(first_seq + 1ULL), 4294967295ULL);
        CHECK_EQ("message 1.order_id", d->order_id(), 8589934594ULL);
        CHECK_EQ("message 1.symbol_id", d->symbol_id(), 3);
        {
            auto e = d->side();
            if (!e) return "message 1.side: undefined enum value";
            CHECK_EQ("message 1.side", static_cast<int>(*e), static_cast<int>(Side::kAsk));
        }
        pos += d->total_len();
    }
    // message 2
    {
        auto d = SnapshotDecoder::wrap(buf + pos, len - pos);
        if (!d) return "message 2: not a decodable Snapshot";
        CHECK_EQ("message 2 sequence", static_cast<std::uint64_t>(first_seq + 2ULL), 4294967296ULL);
        CHECK_EQ("message 2.last_sequence", d->last_sequence(), 4294967295);
        CHECK_EQ("message 2.symbol_id", d->symbol_id(), 3);
        CHECK_EQ("message 2.flags", d->flags(), 0);
        CHECK_EQ("message 2.orders.numInGroup", d->orders_count(), 3);
        CHECK_EQ("message 2.orders.blockLength", d->orders_block_length(), 24);
        {
            auto l = d->order(0);
            CHECK_EQ("message 2.orders[0].order_id", l.order_id(), 8589934593ULL);
            CHECK_EQ("message 2.orders[0].price", l.price(), 990000);
            CHECK_EQ("message 2.orders[0].quantity", l.quantity(), 1000);
            {
                auto e = l.side();
                if (!e) return "message 2.orders[0].side: undefined enum value";
                CHECK_EQ("message 2.orders[0].side", static_cast<int>(*e), static_cast<int>(Side::kBid));
            }
        }
        {
            auto l = d->order(1);
            CHECK_EQ("message 2.orders[1].order_id", l.order_id(), 8589934596ULL);
            CHECK_EQ("message 2.orders[1].price", l.price(), 990100);
            CHECK_EQ("message 2.orders[1].quantity", l.quantity(), 400);
            {
                auto e = l.side();
                if (!e) return "message 2.orders[1].side: undefined enum value";
                CHECK_EQ("message 2.orders[1].side", static_cast<int>(*e), static_cast<int>(Side::kAsk));
            }
        }
        {
            auto l = d->order(2);
            CHECK_EQ("message 2.orders[2].order_id", l.order_id(), 8589934597ULL);
            CHECK_EQ("message 2.orders[2].price", l.price(), 990200);
            CHECK_EQ("message 2.orders[2].quantity", l.quantity(), 700);
            {
                auto e = l.side();
                if (!e) return "message 2.orders[2].side: undefined enum value";
                CHECK_EQ("message 2.orders[2].side", static_cast<int>(*e), static_cast<int>(Side::kAsk));
            }
        }
        pos += d->total_len();
    }
    // message 3
    {
        auto d = TradeDecoder::wrap(buf + pos, len - pos);
        if (!d) return "message 3: not a decodable Trade";
        CHECK_EQ("message 3 sequence", static_cast<std::uint64_t>(first_seq + 3ULL), 4294967297ULL);
        CHECK_EQ("message 3.trade_id", d->trade_id(), 42);
        CHECK_EQ("message 3.aggressor_order_id", d->aggressor_order_id(), 8589934595ULL);
        CHECK_EQ("message 3.resting_order_id", d->resting_order_id(), 8589934593ULL);
        CHECK_EQ("message 3.price", d->price(), 990000);
        CHECK_EQ("message 3.quantity", d->quantity(), 400);
        CHECK_EQ("message 3.symbol_id", d->symbol_id(), 3);
        {
            auto e = d->aggressor_side();
            if (!e) return "message 3.aggressor_side: undefined enum value";
            CHECK_EQ("message 3.aggressor_side", static_cast<int>(*e), static_cast<int>(Side::kAsk));
        }
        pos += d->total_len();
    }
    // message 4
    {
        auto d = ModifyOrderDecoder::wrap(buf + pos, len - pos);
        if (!d) return "message 4: not a decodable ModifyOrder";
        CHECK_EQ("message 4 sequence", static_cast<std::uint64_t>(first_seq + 4ULL), 4294967298ULL);
        CHECK_EQ("message 4.order_id", d->order_id(), 8589934593ULL);
        CHECK_EQ("message 4.new_price", d->new_price(), 990000);
        CHECK_EQ("message 4.new_quantity", d->new_quantity(), 600);
        CHECK_EQ("message 4.symbol_id", d->symbol_id(), 3);
        {
            auto e = d->side();
            if (!e) return "message 4.side: undefined enum value";
            CHECK_EQ("message 4.side", static_cast<int>(*e), static_cast<int>(Side::kBid));
        }
        {
            auto e = d->reason();
            if (!e) return "message 4.reason: undefined enum value";
            CHECK_EQ("message 4.reason", static_cast<int>(*e), static_cast<int>(ModifyReason::kReduce));
        }
        pos += d->total_len();
    }
    // message 5
    {
        auto d = HeartbeatDecoder::wrap(buf + pos, len - pos);
        if (!d) return "message 5: not a decodable Heartbeat";
        CHECK_EQ("message 5 sequence", static_cast<std::uint64_t>(first_seq + 5ULL), 4294967299ULL);
        CHECK_EQ("message 5.last_sequence", d->last_sequence(), 4294967299ULL);
        pos += d->total_len();
    }
    if (pos != len) return "trailing bytes past the last message";
    return "";
}

// Re-encodes `batch_mixed` from the same values check_batch_mixed asserts.
inline std::size_t build_batch_mixed(std::byte* out, std::size_t cap, std::string& err) {
    auto ph = encode_packet_header(out, cap
        , static_cast<std::uint8_t>(0)
        , static_cast<std::uint8_t>(0)
        , 4294967294ULL
        , 1702361767298204934ULL
    );
    if (!ph) { err = "packet header did not fit"; return 0; }
    std::size_t pos = *ph;
    // message 0
    {
        auto n = encode_add_order(out + pos, cap - pos
            , static_cast<std::uint64_t>(8589934593ULL)
            , static_cast<std::int64_t>(990000)
            , static_cast<std::uint32_t>(1000ULL)
            , static_cast<std::uint16_t>(3ULL)
            , Side::kBid
        );
        if (!n) { err = "message 0 did not fit"; return 0; }
        pos += *n;
    }
    // message 1
    {
        auto n = encode_delete_order(out + pos, cap - pos
            , static_cast<std::uint64_t>(8589934594ULL)
            , static_cast<std::uint16_t>(3ULL)
            , Side::kAsk
        );
        if (!n) { err = "message 1 did not fit"; return 0; }
        pos += *n;
    }
    // message 2
    {
        auto e = SnapshotEncoder::start(out + pos, cap - pos
            , 4294967295ULL
            , static_cast<std::uint16_t>(3)
            , static_cast<std::uint8_t>(0)
        );
        if (!e) { err = "message 2 did not fit"; return 0; }
        if (!e->push_order(
                static_cast<std::uint64_t>(8589934593ULL)
                , static_cast<std::int64_t>(990000)
                , static_cast<std::uint32_t>(1000)
                , Side::kBid
        )) { err = "message 2 order 0 did not fit"; return 0; }
        if (!e->push_order(
                static_cast<std::uint64_t>(8589934596ULL)
                , static_cast<std::int64_t>(990100)
                , static_cast<std::uint32_t>(400)
                , Side::kAsk
        )) { err = "message 2 order 1 did not fit"; return 0; }
        if (!e->push_order(
                static_cast<std::uint64_t>(8589934597ULL)
                , static_cast<std::int64_t>(990200)
                , static_cast<std::uint32_t>(700)
                , Side::kAsk
        )) { err = "message 2 order 2 did not fit"; return 0; }
        pos += e->finish();
    }
    // message 3
    {
        auto n = encode_trade(out + pos, cap - pos
            , static_cast<std::uint64_t>(42ULL)
            , static_cast<std::uint64_t>(8589934595ULL)
            , static_cast<std::uint64_t>(8589934593ULL)
            , static_cast<std::int64_t>(990000)
            , static_cast<std::uint32_t>(400ULL)
            , static_cast<std::uint16_t>(3ULL)
            , Side::kAsk
        );
        if (!n) { err = "message 3 did not fit"; return 0; }
        pos += *n;
    }
    // message 4
    {
        auto n = encode_modify_order(out + pos, cap - pos
            , static_cast<std::uint64_t>(8589934593ULL)
            , static_cast<std::int64_t>(990000)
            , static_cast<std::uint32_t>(600ULL)
            , static_cast<std::uint16_t>(3ULL)
            , Side::kBid
            , ModifyReason::kReduce
        );
        if (!n) { err = "message 4 did not fit"; return 0; }
        pos += *n;
    }
    // message 5
    {
        auto n = encode_heartbeat(out + pos, cap - pos
            , static_cast<std::uint64_t>(4294967299ULL)
        );
        if (!n) { err = "message 5 did not fit"; return 0; }
        pos += *n;
    }
    if (!patch_message_count(out, cap, static_cast<std::uint16_t>(6)))
        { err = "could not patch messageCount"; return 0; }
    return pos;
}

// Prices are signed on the wire. Spreads, settlement marks and a few real contracts go below zero, and a decoder that reads the field as unsigned looks correct until the day one does.
inline std::string check_negative_price(const std::byte* buf, std::size_t len) {
    auto h = PacketHeaderDecoder::wrap(buf, len);
    if (!h) return "packet header: wrap failed";
    CHECK_EQ("packet.schemaId", h->schema_id(), 1);
    CHECK_EQ("packet.version", h->version(), 1);
    CHECK_EQ("packet.messageCount", h->message_count(), 1);
    CHECK_EQ("packet.channel", h->channel(), 0);
    CHECK_EQ("packet.flags", h->flags(), 0);
    CHECK_EQ("packet.firstSequence", h->first_sequence(), 1048592ULL);
    CHECK_EQ("packet.sendTimestampNs", h->send_timestamp_ns(), 1702361767298204934ULL);
    CHECK_EQ("packet.isSnapshot", h->is_snapshot(), false);
    std::size_t pos = kPacketHeaderLen;
    const std::uint64_t first_seq = 1048592ULL;
    // message 0
    {
        auto d = AddOrderDecoder::wrap(buf + pos, len - pos);
        if (!d) return "message 0: not a decodable AddOrder";
        CHECK_EQ("message 0 sequence", static_cast<std::uint64_t>(first_seq + 0ULL), 1048592ULL);
        CHECK_EQ("message 0.order_id", d->order_id(), 12884901889ULL);
        CHECK_EQ("message 0.price", d->price(), static_cast<std::int64_t>(-12500));
        CHECK_EQ("message 0.quantity", d->quantity(), 5);
        CHECK_EQ("message 0.symbol_id", d->symbol_id(), 11);
        {
            auto e = d->side();
            if (!e) return "message 0.side: undefined enum value";
            CHECK_EQ("message 0.side", static_cast<int>(*e), static_cast<int>(Side::kAsk));
        }
        pos += d->total_len();
    }
    if (pos != len) return "trailing bytes past the last message";
    return "";
}

// Re-encodes `negative_price` from the same values check_negative_price asserts.
inline std::size_t build_negative_price(std::byte* out, std::size_t cap, std::string& err) {
    auto ph = encode_packet_header(out, cap
        , static_cast<std::uint8_t>(0)
        , static_cast<std::uint8_t>(0)
        , 1048592ULL
        , 1702361767298204934ULL
    );
    if (!ph) { err = "packet header did not fit"; return 0; }
    std::size_t pos = *ph;
    // message 0
    {
        auto n = encode_add_order(out + pos, cap - pos
            , static_cast<std::uint64_t>(12884901889ULL)
            , static_cast<std::int64_t>(-12500)
            , static_cast<std::uint32_t>(5ULL)
            , static_cast<std::uint16_t>(11ULL)
            , Side::kAsk
        );
        if (!n) { err = "message 0 did not fit"; return 0; }
        pos += *n;
    }
    if (!patch_message_count(out, cap, static_cast<std::uint16_t>(1)))
        { err = "could not patch messageCount"; return 0; }
    return pos;
}

// firstSequence near 2^64. The sequence of message i is firstSequence+i, so a reader that widens through i32 or i64 breaks here and nowhere else.
inline std::string check_sequence_wrap_high(const std::byte* buf, std::size_t len) {
    auto h = PacketHeaderDecoder::wrap(buf, len);
    if (!h) return "packet header: wrap failed";
    CHECK_EQ("packet.schemaId", h->schema_id(), 1);
    CHECK_EQ("packet.version", h->version(), 1);
    CHECK_EQ("packet.messageCount", h->message_count(), 2);
    CHECK_EQ("packet.channel", h->channel(), 1);
    CHECK_EQ("packet.flags", h->flags(), 0);
    CHECK_EQ("packet.firstSequence", h->first_sequence(), 18446744073709551613ULL);
    CHECK_EQ("packet.sendTimestampNs", h->send_timestamp_ns(), 1702361767298204934ULL);
    CHECK_EQ("packet.isSnapshot", h->is_snapshot(), false);
    std::size_t pos = kPacketHeaderLen;
    const std::uint64_t first_seq = 18446744073709551613ULL;
    // message 0
    {
        auto d = HeartbeatDecoder::wrap(buf + pos, len - pos);
        if (!d) return "message 0: not a decodable Heartbeat";
        CHECK_EQ("message 0 sequence", static_cast<std::uint64_t>(first_seq + 0ULL), 18446744073709551613ULL);
        CHECK_EQ("message 0.last_sequence", d->last_sequence(), 18446744073709551613ULL);
        pos += d->total_len();
    }
    // message 1
    {
        auto d = HeartbeatDecoder::wrap(buf + pos, len - pos);
        if (!d) return "message 1: not a decodable Heartbeat";
        CHECK_EQ("message 1 sequence", static_cast<std::uint64_t>(first_seq + 1ULL), 18446744073709551614ULL);
        CHECK_EQ("message 1.last_sequence", d->last_sequence(), 18446744073709551614ULL);
        pos += d->total_len();
    }
    if (pos != len) return "trailing bytes past the last message";
    return "";
}

// Re-encodes `sequence_wrap_high` from the same values check_sequence_wrap_high asserts.
inline std::size_t build_sequence_wrap_high(std::byte* out, std::size_t cap, std::string& err) {
    auto ph = encode_packet_header(out, cap
        , static_cast<std::uint8_t>(1)
        , static_cast<std::uint8_t>(0)
        , 18446744073709551613ULL
        , 1702361767298204934ULL
    );
    if (!ph) { err = "packet header did not fit"; return 0; }
    std::size_t pos = *ph;
    // message 0
    {
        auto n = encode_heartbeat(out + pos, cap - pos
            , static_cast<std::uint64_t>(18446744073709551613ULL)
        );
        if (!n) { err = "message 0 did not fit"; return 0; }
        pos += *n;
    }
    // message 1
    {
        auto n = encode_heartbeat(out + pos, cap - pos
            , static_cast<std::uint64_t>(18446744073709551614ULL)
        );
        if (!n) { err = "message 1 did not fit"; return 0; }
        pos += *n;
    }
    if (!patch_message_count(out, cap, static_cast<std::uint16_t>(2)))
        { err = "could not patch messageCount"; return 0; }
    return pos;
}

struct Vector {
    const char* name;
    const char* file;
    const char* why;
    std::string (*check)(const std::byte*, std::size_t);
    std::size_t (*build)(std::byte*, std::size_t, std::string&);
};

inline constexpr Vector kVectors[] = {
    {"add_order", "add_order.bin", "One AddOrder. Anchors the AddOrder block and the packet header.", check_add_order, build_add_order},
    {"modify_order", "modify_order.bin", "A Replace, which loses queue priority. channel=1 exercises the B arm.", check_modify_order, build_modify_order},
    {"delete_order", "delete_order.bin", "The shortest message: a 12-byte block that leaves the next message 4-byte aligned.", check_delete_order, build_delete_order},
    {"trade", "trade.bin", "The longest fixed block, and the only message naming two orders.", check_trade, build_trade},
    {"heartbeat", "heartbeat.bin", "Idle-channel keepalive; the handler uses it to tell quiet from dead.", check_heartbeat, build_heartbeat},
    {"sequence_reset", "sequence_reset.bin", "The publisher restarts its numbering.", check_sequence_reset, build_sequence_reset},
    {"snapshot_two_orders", "snapshot_two_orders.bin", "The repeating group, the snapshot flag on the packet header, and the last-fragment flag on the message. Orders are listed in queue order: a consumer that re-adds them in this order reproduces price-time priority exactly, which an aggregated snapshot could never do.", check_snapshot_two_orders, build_snapshot_two_orders},
    {"snapshot_empty_group", "snapshot_empty_group.bin", "A snapshot of an empty book. numInGroup=0 must still carry the group header, or total_len walks the reader into the next message.", check_snapshot_empty_group, build_snapshot_empty_group},
    {"batch_mixed", "batch_mixed.bin", "Six messages of five types behind one header, including a variable-length snapshot in the middle. This is the vector that proves a decoder can walk a batch: get any total_len wrong and every message after it is garbage. Batching is not an optimisation here, it is the framing the throughput target depends on.", check_batch_mixed, build_batch_mixed},
    {"negative_price", "negative_price.bin", "Prices are signed on the wire. Spreads, settlement marks and a few real contracts go below zero, and a decoder that reads the field as unsigned looks correct until the day one does.", check_negative_price, build_negative_price},
    {"sequence_wrap_high", "sequence_wrap_high.bin", "firstSequence near 2^64. The sequence of message i is firstSequence+i, so a reader that widens through i32 or i64 breaks here and nowhere else.", check_sequence_wrap_high, build_sequence_wrap_high},
};

}  // namespace mdstack::golden
