//! @generated by schema/codegen.py from schema/market-data.xml -- do not edit.
//!
//! Edit the schema and run `make codegen`. CI regenerates and diffs, so a
//! hand-edit here fails the build rather than silently surviving.

#![allow(clippy::too_many_arguments)]

use crate::error::WireError;

/// Schema identity, checked on every datagram.
pub const SCHEMA_ID: u16 = 1;
pub const SCHEMA_VERSION: u16 = 1;
pub const SEMANTIC_VERSION: &str = "1.0.0";

/// Schema constant `priceExponent`.
pub const PRICE_EXPONENT: i8 = -4;

/// Bytes of per-datagram framing.
pub const PACKET_HEADER_LEN: usize = 24;
/// Bytes of per-message framing.
pub const MESSAGE_HEADER_LEN: usize = 8;
/// Bytes of per-group framing.
pub const GROUP_SIZE_ENCODING_LEN: usize = 4;

/// `packetHeader.flags` bit 0: this datagram belongs to a snapshot cycle.
pub const PACKET_FLAG_SNAPSHOT: u8 = 0x01;
/// `Snapshot.flags` bit 0: the last fragment for this symbol in this cycle.
///
/// A book with more resting orders than fit in one datagram is split
/// across several `Snapshot` messages. A consumer must not treat a
/// partial book as complete, so it accumulates fragments until it sees
/// this bit.
pub const SNAPSHOT_FLAG_LAST_FRAGMENT: u8 = 0x01;
/// `Snapshot.flags` bit 1: the last fragment of the whole cycle.
///
/// A cycle covers every symbol, so the last fragment *of a symbol*
/// completes one book and not the set. A consumer recovering from a
/// gap has to wait for this bit, or it adopts the first symbol it
/// sees, declares itself recovered, and discards the snapshots for
/// every other symbol as unsolicited.
pub const SNAPSHOT_FLAG_CYCLE_END: u8 = 0x02;
/// `Snapshot.flags` bit 2: the first fragment of the whole cycle.
///
/// A cycle replaces every book, so a consumer must join it at the
/// start. Adopting from the middle leaves the symbols whose fragments
/// already went past holding stale state, while reporting a
/// successful recovery.
pub const SNAPSHOT_FLAG_CYCLE_START: u8 = 0x04;

// Unaligned-safe little-endian access. Messages are packed back to back
// inside a datagram, so a block can start at any byte offset; every read
// and write below goes through a fixed-size copy, which the compiler
// lowers to a single instruction on x86-64 and aarch64.
#[inline(always)]
fn le_u8(b: &[u8], o: usize) -> u8 {
    b[o]
}

#[inline(always)]
fn put_u8(b: &mut [u8], o: usize, v: u8) {
    b[o] = v;
}

#[inline(always)]
fn le_u16(b: &[u8], o: usize) -> u16 {
    let mut a = [0u8; 2];
    a.copy_from_slice(&b[o..o + 2]);
    u16::from_le_bytes(a)
}

#[inline(always)]
fn put_u16(b: &mut [u8], o: usize, v: u16) {
    b[o..o + 2].copy_from_slice(&v.to_le_bytes());
}

#[inline(always)]
fn le_u32(b: &[u8], o: usize) -> u32 {
    let mut a = [0u8; 4];
    a.copy_from_slice(&b[o..o + 4]);
    u32::from_le_bytes(a)
}

#[inline(always)]
fn put_u32(b: &mut [u8], o: usize, v: u32) {
    b[o..o + 4].copy_from_slice(&v.to_le_bytes());
}

#[inline(always)]
fn le_u64(b: &[u8], o: usize) -> u64 {
    let mut a = [0u8; 8];
    a.copy_from_slice(&b[o..o + 8]);
    u64::from_le_bytes(a)
}

#[inline(always)]
fn put_u64(b: &mut [u8], o: usize, v: u64) {
    b[o..o + 8].copy_from_slice(&v.to_le_bytes());
}

#[inline(always)]
fn le_i64(b: &[u8], o: usize) -> i64 {
    let mut a = [0u8; 8];
    a.copy_from_slice(&b[o..o + 8]);
    i64::from_le_bytes(a)
}

#[inline(always)]
fn put_i64(b: &mut [u8], o: usize, v: i64) {
    b[o..o + 8].copy_from_slice(&v.to_le_bytes());
}

/// `Side` as encoded on the wire.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum Side {
    Bid = 0,
    Ask = 1,
}

impl Side {
    /// Reject anything the schema does not define rather than
    /// transmuting an unknown discriminant.
    #[inline]
    pub fn from_u8(v: u8) -> Result<Self, WireError> {
        match v {
            0 => Ok(Self::Bid),
            1 => Ok(Self::Ask),
            other => Err(WireError::InvalidEnum {
                name: "Side",
                value: other as u64,
            }),
        }
    }

    #[inline(always)]
    pub fn to_u8(self) -> u8 {
        self as u8
    }
}

/// `ModifyReason` as encoded on the wire.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum ModifyReason {
    Reduce = 0,
    Replace = 1,
}

impl ModifyReason {
    /// Reject anything the schema does not define rather than
    /// transmuting an unknown discriminant.
    #[inline]
    pub fn from_u8(v: u8) -> Result<Self, WireError> {
        match v {
            0 => Ok(Self::Reduce),
            1 => Ok(Self::Replace),
            other => Err(WireError::InvalidEnum {
                name: "ModifyReason",
                value: other as u64,
            }),
        }
    }

    #[inline(always)]
    pub fn to_u8(self) -> u8 {
        self as u8
    }
}

/// Template ids, as they appear in `messageHeader.templateId`.
pub mod template {
    /// A new order rests on the book
    pub const ADD_ORDER: u16 = 1;
    /// A resting order changes price or quantity
    pub const MODIFY_ORDER: u16 = 2;
    /// A resting order leaves the book
    pub const DELETE_ORDER: u16 = 3;
    /// An aggressing order crossed with a resting order
    pub const TRADE: u16 = 4;
    /// Full book state for one symbol, consistent as of lastSequence
    pub const SNAPSHOT: u16 = 5;
    /// Published on an idle channel so a handler can tell quiet from dead
    pub const HEARTBEAT: u16 = 6;
    /// The publisher restarts its sequence; the handler must resynchronise
    pub const SEQUENCE_RESET: u16 = 7;
}

/// Read-only view over the 24-byte datagram header.
#[derive(Debug, Clone, Copy)]
pub struct PacketHeaderDecoder<'a> {
    buf: &'a [u8],
}

impl<'a> PacketHeaderDecoder<'a> {
    /// Wraps a datagram. Fails on a short buffer or a foreign schema,
    /// which is the only place a wrong-feed datagram gets rejected.
    #[inline]
    pub fn wrap(buf: &'a [u8]) -> Result<Self, WireError> {
        if buf.len() < PACKET_HEADER_LEN {
            return Err(WireError::ShortBuffer {
                needed: PACKET_HEADER_LEN,
                got: buf.len(),
            });
        }
        let d = Self { buf };
        if d.schema_id() != SCHEMA_ID {
            return Err(WireError::SchemaMismatch {
                expected: SCHEMA_ID,
                got: d.schema_id(),
            });
        }
        Ok(d)
    }

    /// Must equal the schema id; a mismatch is a hard reject
    #[inline(always)]
    pub fn schema_id(&self) -> u16 {
        le_u16(self.buf, 0)
    }

    /// Schema version the publisher encoded with
    #[inline(always)]
    pub fn version(&self) -> u16 {
        le_u16(self.buf, 2)
    }

    /// Number of messages packed into this datagram
    #[inline(always)]
    pub fn message_count(&self) -> u16 {
        le_u16(self.buf, 4)
    }

    /// 0 = feed A, 1 = feed B; diagnostic only, arbitration keys on sequence
    #[inline(always)]
    pub fn channel(&self) -> u8 {
        le_u8(self.buf, 6)
    }

    /// bit0 = this datagram is part of a snapshot cycle
    #[inline(always)]
    pub fn flags(&self) -> u8 {
        le_u8(self.buf, 7)
    }

    /// Sequence of the first message; message i is firstSequence + i
    #[inline(always)]
    pub fn first_sequence(&self) -> u64 {
        le_u64(self.buf, 8)
    }

    /// Publisher clock at send, nanoseconds since the Unix epoch
    #[inline(always)]
    pub fn send_timestamp_ns(&self) -> u64 {
        le_u64(self.buf, 16)
    }

    /// True when this datagram is part of a snapshot cycle.
    #[inline(always)]
    pub fn is_snapshot(&self) -> bool {
        self.flags() & PACKET_FLAG_SNAPSHOT != 0
    }
}

/// Writes the datagram header. `message_count` is patched by
/// [`patch_message_count`] once the messages have been written.
#[inline]
pub fn encode_packet_header(
    buf: &mut [u8],
    channel: u8,
    flags: u8,
    first_sequence: u64,
    send_timestamp_ns: u64,
) -> Result<usize, WireError> {
    if buf.len() < PACKET_HEADER_LEN {
        return Err(WireError::ShortBuffer {
            needed: PACKET_HEADER_LEN,
            got: buf.len(),
        });
    }
    buf[..PACKET_HEADER_LEN].fill(0);
    put_u16(buf, 0, SCHEMA_ID);
    put_u16(buf, 2, SCHEMA_VERSION);
    put_u16(buf, 4, 0);
    put_u8(buf, 6, channel);
    put_u8(buf, 7, flags);
    put_u64(buf, 8, first_sequence);
    put_u64(buf, 16, send_timestamp_ns);
    Ok(PACKET_HEADER_LEN)
}

/// Sets `packetHeader.channel` on an already-written header.
///
/// The two arms send identical bytes apart from this one field, so the
/// header is written once and only the channel is patched per arm. That
/// also means the buffer is always a valid datagram, even when a
/// simulated drop means it is never actually sent.
#[inline]
pub fn patch_packet_channel(buf: &mut [u8], channel: u8) -> Result<(), WireError> {
    if buf.len() < PACKET_HEADER_LEN {
        return Err(WireError::ShortBuffer {
            needed: PACKET_HEADER_LEN,
            got: buf.len(),
        });
    }
    put_u8(buf, 6, channel);
    Ok(())
}

/// Sets `Snapshot.flags` on a message already written by
/// [`SnapshotEncoder`].
///
/// Whether a fragment is the last one for its symbol is only known
/// once the encoder has run out of room, which is after the root
/// block was written. Patching afterwards is simpler and less
/// error-prone than predicting it.
#[inline]
pub fn patch_snapshot_flags(buf: &mut [u8], flags: u8) -> Result<(), WireError> {
    const OFFSET: usize = MESSAGE_HEADER_LEN + 10;
    if buf.len() <= OFFSET {
        return Err(WireError::ShortBuffer {
            needed: OFFSET + 1,
            got: buf.len(),
        });
    }
    put_u8(buf, OFFSET, flags);
    Ok(())
}

/// Patches `messageCount` in a header written by [`encode_packet_header`].
#[inline]
pub fn patch_message_count(buf: &mut [u8], count: u16) -> Result<(), WireError> {
    if buf.len() < PACKET_HEADER_LEN {
        return Err(WireError::ShortBuffer {
            needed: PACKET_HEADER_LEN,
            got: buf.len(),
        });
    }
    put_u16(buf, 4, count);
    Ok(())
}

/// Read-only view over the 8-byte message header.
#[derive(Debug, Clone, Copy)]
pub struct MessageHeaderDecoder<'a> {
    buf: &'a [u8],
}

impl<'a> MessageHeaderDecoder<'a> {
    #[inline]
    pub fn wrap(buf: &'a [u8]) -> Result<Self, WireError> {
        if buf.len() < MESSAGE_HEADER_LEN {
            return Err(WireError::ShortBuffer {
                needed: MESSAGE_HEADER_LEN,
                got: buf.len(),
            });
        }
        Ok(Self { buf })
    }

    /// Bytes of root block following this header, excluding any group
    #[inline(always)]
    pub fn block_length(&self) -> u16 {
        le_u16(self.buf, 0)
    }

    /// Which message this is
    #[inline(always)]
    pub fn template_id(&self) -> u16 {
        le_u16(self.buf, 2)
    }

    #[inline(always)]
    pub fn schema_id(&self) -> u16 {
        le_u16(self.buf, 4)
    }

    #[inline(always)]
    pub fn version(&self) -> u16 {
        le_u16(self.buf, 6)
    }
}

#[inline(always)]
fn write_message_header(buf: &mut [u8], block_length: u16, template_id: u16) {
    put_u16(buf, 0, block_length);
    put_u16(buf, 2, template_id);
    put_u16(buf, 4, SCHEMA_ID);
    put_u16(buf, 6, SCHEMA_VERSION);
}

// --- AddOrder ------------------------------------------------------

/// A new order rests on the book
///
/// Borrows the datagram; decoding copies nothing.
#[derive(Debug, Clone, Copy)]
pub struct AddOrderDecoder<'a> {
    buf: &'a [u8],
    root_len: usize,
}

impl<'a> AddOrderDecoder<'a> {
    pub const TEMPLATE_ID: u16 = 1;
    pub const BLOCK_LENGTH: u16 = 24;

    /// Wraps a buffer whose first byte is the message header.
    ///
    /// The root block length comes from the wire, not from the constant,
    /// so a newer publisher that appended fields is skipped correctly
    /// rather than misparsed.
    #[inline]
    pub fn wrap(buf: &'a [u8]) -> Result<Self, WireError> {
        let hdr = MessageHeaderDecoder::wrap(buf)?;
        if hdr.template_id() != Self::TEMPLATE_ID {
            return Err(WireError::TemplateMismatch {
                expected: Self::TEMPLATE_ID,
                got: hdr.template_id(),
            });
        }
        let root_len = hdr.block_length() as usize;
        if root_len < Self::BLOCK_LENGTH as usize {
            return Err(WireError::BlockTooSmall {
                message: "AddOrder",
                needed: Self::BLOCK_LENGTH,
                got: hdr.block_length(),
            });
        }
        let need = MESSAGE_HEADER_LEN + root_len;
        if buf.len() < need {
            return Err(WireError::ShortBuffer {
                needed: need,
                got: buf.len(),
            });
        }
        let d = Self { buf, root_len };
        Ok(d)
    }

    #[inline(always)]
    pub fn order_id(&self) -> u64 {
        le_u64(self.buf, MESSAGE_HEADER_LEN)
    }

    /// Fixed point, scaled by 10^-4.
    #[inline(always)]
    pub fn price(&self) -> i64 {
        le_i64(self.buf, MESSAGE_HEADER_LEN + 8)
    }

    #[inline(always)]
    pub fn quantity(&self) -> u32 {
        le_u32(self.buf, MESSAGE_HEADER_LEN + 16)
    }

    #[inline(always)]
    pub fn symbol_id(&self) -> u16 {
        le_u16(self.buf, MESSAGE_HEADER_LEN + 20)
    }

    #[inline(always)]
    pub fn side_raw(&self) -> u8 {
        le_u8(self.buf, MESSAGE_HEADER_LEN + 22)
    }

    /// Validating accessor. Use `side_raw()` on the hot path.
    #[inline]
    pub fn side(&self) -> Result<Side, WireError> {
        Side::from_u8(self.side_raw())
    }

    /// Total bytes, header included.
    #[inline(always)]
    pub fn total_len(&self) -> usize {
        MESSAGE_HEADER_LEN + self.root_len
    }
}

/// Encodes a `AddOrder` at `buf[0]`, header included.
///
/// Returns the bytes written. Reserved bytes are zeroed, which is what
/// makes a re-encode byte-identical to the golden vector.
#[inline]
pub fn encode_add_order(
    buf: &mut [u8],
    order_id: u64,
    price: i64,
    quantity: u32,
    symbol_id: u16,
    side: Side,
) -> Result<usize, WireError> {
    const LEN: usize = MESSAGE_HEADER_LEN + 24;
    if buf.len() < LEN {
        return Err(WireError::ShortBuffer {
            needed: LEN,
            got: buf.len(),
        });
    }
    buf[..LEN].fill(0);
    write_message_header(buf, 24, template::ADD_ORDER);
    put_u64(buf, MESSAGE_HEADER_LEN, order_id);
    put_i64(buf, MESSAGE_HEADER_LEN + 8, price);
    put_u32(buf, MESSAGE_HEADER_LEN + 16, quantity);
    put_u16(buf, MESSAGE_HEADER_LEN + 20, symbol_id);
    put_u8(buf, MESSAGE_HEADER_LEN + 22, side as u8);
    Ok(LEN)
}

// --- ModifyOrder ---------------------------------------------------

/// A resting order changes price or quantity
///
/// Borrows the datagram; decoding copies nothing.
#[derive(Debug, Clone, Copy)]
pub struct ModifyOrderDecoder<'a> {
    buf: &'a [u8],
    root_len: usize,
}

impl<'a> ModifyOrderDecoder<'a> {
    pub const TEMPLATE_ID: u16 = 2;
    pub const BLOCK_LENGTH: u16 = 24;

    /// Wraps a buffer whose first byte is the message header.
    ///
    /// The root block length comes from the wire, not from the constant,
    /// so a newer publisher that appended fields is skipped correctly
    /// rather than misparsed.
    #[inline]
    pub fn wrap(buf: &'a [u8]) -> Result<Self, WireError> {
        let hdr = MessageHeaderDecoder::wrap(buf)?;
        if hdr.template_id() != Self::TEMPLATE_ID {
            return Err(WireError::TemplateMismatch {
                expected: Self::TEMPLATE_ID,
                got: hdr.template_id(),
            });
        }
        let root_len = hdr.block_length() as usize;
        if root_len < Self::BLOCK_LENGTH as usize {
            return Err(WireError::BlockTooSmall {
                message: "ModifyOrder",
                needed: Self::BLOCK_LENGTH,
                got: hdr.block_length(),
            });
        }
        let need = MESSAGE_HEADER_LEN + root_len;
        if buf.len() < need {
            return Err(WireError::ShortBuffer {
                needed: need,
                got: buf.len(),
            });
        }
        let d = Self { buf, root_len };
        Ok(d)
    }

    #[inline(always)]
    pub fn order_id(&self) -> u64 {
        le_u64(self.buf, MESSAGE_HEADER_LEN)
    }

    /// Fixed point, scaled by 10^-4.
    #[inline(always)]
    pub fn new_price(&self) -> i64 {
        le_i64(self.buf, MESSAGE_HEADER_LEN + 8)
    }

    #[inline(always)]
    pub fn new_quantity(&self) -> u32 {
        le_u32(self.buf, MESSAGE_HEADER_LEN + 16)
    }

    #[inline(always)]
    pub fn symbol_id(&self) -> u16 {
        le_u16(self.buf, MESSAGE_HEADER_LEN + 20)
    }

    #[inline(always)]
    pub fn side_raw(&self) -> u8 {
        le_u8(self.buf, MESSAGE_HEADER_LEN + 22)
    }

    /// Validating accessor. Use `side_raw()` on the hot path.
    #[inline]
    pub fn side(&self) -> Result<Side, WireError> {
        Side::from_u8(self.side_raw())
    }

    #[inline(always)]
    pub fn reason_raw(&self) -> u8 {
        le_u8(self.buf, MESSAGE_HEADER_LEN + 23)
    }

    /// Validating accessor. Use `reason_raw()` on the hot path.
    #[inline]
    pub fn reason(&self) -> Result<ModifyReason, WireError> {
        ModifyReason::from_u8(self.reason_raw())
    }

    /// Total bytes, header included.
    #[inline(always)]
    pub fn total_len(&self) -> usize {
        MESSAGE_HEADER_LEN + self.root_len
    }
}

/// Encodes a `ModifyOrder` at `buf[0]`, header included.
///
/// Returns the bytes written. Reserved bytes are zeroed, which is what
/// makes a re-encode byte-identical to the golden vector.
#[inline]
pub fn encode_modify_order(
    buf: &mut [u8],
    order_id: u64,
    new_price: i64,
    new_quantity: u32,
    symbol_id: u16,
    side: Side,
    reason: ModifyReason,
) -> Result<usize, WireError> {
    const LEN: usize = MESSAGE_HEADER_LEN + 24;
    if buf.len() < LEN {
        return Err(WireError::ShortBuffer {
            needed: LEN,
            got: buf.len(),
        });
    }
    buf[..LEN].fill(0);
    write_message_header(buf, 24, template::MODIFY_ORDER);
    put_u64(buf, MESSAGE_HEADER_LEN, order_id);
    put_i64(buf, MESSAGE_HEADER_LEN + 8, new_price);
    put_u32(buf, MESSAGE_HEADER_LEN + 16, new_quantity);
    put_u16(buf, MESSAGE_HEADER_LEN + 20, symbol_id);
    put_u8(buf, MESSAGE_HEADER_LEN + 22, side as u8);
    put_u8(buf, MESSAGE_HEADER_LEN + 23, reason as u8);
    Ok(LEN)
}

// --- DeleteOrder ---------------------------------------------------

/// A resting order leaves the book
///
/// Borrows the datagram; decoding copies nothing.
#[derive(Debug, Clone, Copy)]
pub struct DeleteOrderDecoder<'a> {
    buf: &'a [u8],
    root_len: usize,
}

impl<'a> DeleteOrderDecoder<'a> {
    pub const TEMPLATE_ID: u16 = 3;
    pub const BLOCK_LENGTH: u16 = 12;

    /// Wraps a buffer whose first byte is the message header.
    ///
    /// The root block length comes from the wire, not from the constant,
    /// so a newer publisher that appended fields is skipped correctly
    /// rather than misparsed.
    #[inline]
    pub fn wrap(buf: &'a [u8]) -> Result<Self, WireError> {
        let hdr = MessageHeaderDecoder::wrap(buf)?;
        if hdr.template_id() != Self::TEMPLATE_ID {
            return Err(WireError::TemplateMismatch {
                expected: Self::TEMPLATE_ID,
                got: hdr.template_id(),
            });
        }
        let root_len = hdr.block_length() as usize;
        if root_len < Self::BLOCK_LENGTH as usize {
            return Err(WireError::BlockTooSmall {
                message: "DeleteOrder",
                needed: Self::BLOCK_LENGTH,
                got: hdr.block_length(),
            });
        }
        let need = MESSAGE_HEADER_LEN + root_len;
        if buf.len() < need {
            return Err(WireError::ShortBuffer {
                needed: need,
                got: buf.len(),
            });
        }
        let d = Self { buf, root_len };
        Ok(d)
    }

    #[inline(always)]
    pub fn order_id(&self) -> u64 {
        le_u64(self.buf, MESSAGE_HEADER_LEN)
    }

    #[inline(always)]
    pub fn symbol_id(&self) -> u16 {
        le_u16(self.buf, MESSAGE_HEADER_LEN + 8)
    }

    #[inline(always)]
    pub fn side_raw(&self) -> u8 {
        le_u8(self.buf, MESSAGE_HEADER_LEN + 10)
    }

    /// Validating accessor. Use `side_raw()` on the hot path.
    #[inline]
    pub fn side(&self) -> Result<Side, WireError> {
        Side::from_u8(self.side_raw())
    }

    /// Total bytes, header included.
    #[inline(always)]
    pub fn total_len(&self) -> usize {
        MESSAGE_HEADER_LEN + self.root_len
    }
}

/// Encodes a `DeleteOrder` at `buf[0]`, header included.
///
/// Returns the bytes written. Reserved bytes are zeroed, which is what
/// makes a re-encode byte-identical to the golden vector.
#[inline]
pub fn encode_delete_order(
    buf: &mut [u8],
    order_id: u64,
    symbol_id: u16,
    side: Side,
) -> Result<usize, WireError> {
    const LEN: usize = MESSAGE_HEADER_LEN + 12;
    if buf.len() < LEN {
        return Err(WireError::ShortBuffer {
            needed: LEN,
            got: buf.len(),
        });
    }
    buf[..LEN].fill(0);
    write_message_header(buf, 12, template::DELETE_ORDER);
    put_u64(buf, MESSAGE_HEADER_LEN, order_id);
    put_u16(buf, MESSAGE_HEADER_LEN + 8, symbol_id);
    put_u8(buf, MESSAGE_HEADER_LEN + 10, side as u8);
    Ok(LEN)
}

// --- Trade ---------------------------------------------------------

/// An aggressing order crossed with a resting order
///
/// Borrows the datagram; decoding copies nothing.
#[derive(Debug, Clone, Copy)]
pub struct TradeDecoder<'a> {
    buf: &'a [u8],
    root_len: usize,
}

impl<'a> TradeDecoder<'a> {
    pub const TEMPLATE_ID: u16 = 4;
    pub const BLOCK_LENGTH: u16 = 40;

    /// Wraps a buffer whose first byte is the message header.
    ///
    /// The root block length comes from the wire, not from the constant,
    /// so a newer publisher that appended fields is skipped correctly
    /// rather than misparsed.
    #[inline]
    pub fn wrap(buf: &'a [u8]) -> Result<Self, WireError> {
        let hdr = MessageHeaderDecoder::wrap(buf)?;
        if hdr.template_id() != Self::TEMPLATE_ID {
            return Err(WireError::TemplateMismatch {
                expected: Self::TEMPLATE_ID,
                got: hdr.template_id(),
            });
        }
        let root_len = hdr.block_length() as usize;
        if root_len < Self::BLOCK_LENGTH as usize {
            return Err(WireError::BlockTooSmall {
                message: "Trade",
                needed: Self::BLOCK_LENGTH,
                got: hdr.block_length(),
            });
        }
        let need = MESSAGE_HEADER_LEN + root_len;
        if buf.len() < need {
            return Err(WireError::ShortBuffer {
                needed: need,
                got: buf.len(),
            });
        }
        let d = Self { buf, root_len };
        Ok(d)
    }

    #[inline(always)]
    pub fn trade_id(&self) -> u64 {
        le_u64(self.buf, MESSAGE_HEADER_LEN)
    }

    #[inline(always)]
    pub fn aggressor_order_id(&self) -> u64 {
        le_u64(self.buf, MESSAGE_HEADER_LEN + 8)
    }

    #[inline(always)]
    pub fn resting_order_id(&self) -> u64 {
        le_u64(self.buf, MESSAGE_HEADER_LEN + 16)
    }

    /// Fixed point, scaled by 10^-4.
    #[inline(always)]
    pub fn price(&self) -> i64 {
        le_i64(self.buf, MESSAGE_HEADER_LEN + 24)
    }

    #[inline(always)]
    pub fn quantity(&self) -> u32 {
        le_u32(self.buf, MESSAGE_HEADER_LEN + 32)
    }

    #[inline(always)]
    pub fn symbol_id(&self) -> u16 {
        le_u16(self.buf, MESSAGE_HEADER_LEN + 36)
    }

    #[inline(always)]
    pub fn aggressor_side_raw(&self) -> u8 {
        le_u8(self.buf, MESSAGE_HEADER_LEN + 38)
    }

    /// Validating accessor. Use `aggressor_side_raw()` on the hot path.
    #[inline]
    pub fn aggressor_side(&self) -> Result<Side, WireError> {
        Side::from_u8(self.aggressor_side_raw())
    }

    /// Total bytes, header included.
    #[inline(always)]
    pub fn total_len(&self) -> usize {
        MESSAGE_HEADER_LEN + self.root_len
    }
}

/// Encodes a `Trade` at `buf[0]`, header included.
///
/// Returns the bytes written. Reserved bytes are zeroed, which is what
/// makes a re-encode byte-identical to the golden vector.
#[inline]
pub fn encode_trade(
    buf: &mut [u8],
    trade_id: u64,
    aggressor_order_id: u64,
    resting_order_id: u64,
    price: i64,
    quantity: u32,
    symbol_id: u16,
    aggressor_side: Side,
) -> Result<usize, WireError> {
    const LEN: usize = MESSAGE_HEADER_LEN + 40;
    if buf.len() < LEN {
        return Err(WireError::ShortBuffer {
            needed: LEN,
            got: buf.len(),
        });
    }
    buf[..LEN].fill(0);
    write_message_header(buf, 40, template::TRADE);
    put_u64(buf, MESSAGE_HEADER_LEN, trade_id);
    put_u64(buf, MESSAGE_HEADER_LEN + 8, aggressor_order_id);
    put_u64(buf, MESSAGE_HEADER_LEN + 16, resting_order_id);
    put_i64(buf, MESSAGE_HEADER_LEN + 24, price);
    put_u32(buf, MESSAGE_HEADER_LEN + 32, quantity);
    put_u16(buf, MESSAGE_HEADER_LEN + 36, symbol_id);
    put_u8(buf, MESSAGE_HEADER_LEN + 38, aggressor_side as u8);
    Ok(LEN)
}

// --- Snapshot ------------------------------------------------------

/// Full book state for one symbol, consistent as of lastSequence
///
/// Borrows the datagram; decoding copies nothing.
#[derive(Debug, Clone, Copy)]
pub struct SnapshotDecoder<'a> {
    buf: &'a [u8],
    root_len: usize,
}

impl<'a> SnapshotDecoder<'a> {
    pub const TEMPLATE_ID: u16 = 5;
    pub const BLOCK_LENGTH: u16 = 12;

    /// Wraps a buffer whose first byte is the message header.
    ///
    /// The root block length comes from the wire, not from the constant,
    /// so a newer publisher that appended fields is skipped correctly
    /// rather than misparsed.
    #[inline]
    pub fn wrap(buf: &'a [u8]) -> Result<Self, WireError> {
        let hdr = MessageHeaderDecoder::wrap(buf)?;
        if hdr.template_id() != Self::TEMPLATE_ID {
            return Err(WireError::TemplateMismatch {
                expected: Self::TEMPLATE_ID,
                got: hdr.template_id(),
            });
        }
        let root_len = hdr.block_length() as usize;
        if root_len < Self::BLOCK_LENGTH as usize {
            return Err(WireError::BlockTooSmall {
                message: "Snapshot",
                needed: Self::BLOCK_LENGTH,
                got: hdr.block_length(),
            });
        }
        let need = MESSAGE_HEADER_LEN + root_len;
        if buf.len() < need {
            return Err(WireError::ShortBuffer {
                needed: need,
                got: buf.len(),
            });
        }
        let d = Self { buf, root_len };
        // The group header has to be proved present before it can be
        // read: `total_len` reads it, so calling that first on a
        // truncated datagram would panic instead of returning an error.
        let with_group_header = need + GROUP_SIZE_ENCODING_LEN;
        if buf.len() < with_group_header {
            return Err(WireError::ShortBuffer {
                needed: with_group_header,
                got: buf.len(),
            });
        }
        // Now the entry count is readable, so the full extent is known.
        let total = d.total_len();
        if buf.len() < total {
            return Err(WireError::ShortBuffer {
                needed: total,
                got: buf.len(),
            });
        }
        Ok(d)
    }

    /// The snapshot reflects every message up to and including this sequence
    #[inline(always)]
    pub fn last_sequence(&self) -> u64 {
        le_u64(self.buf, MESSAGE_HEADER_LEN)
    }

    #[inline(always)]
    pub fn symbol_id(&self) -> u16 {
        le_u16(self.buf, MESSAGE_HEADER_LEN + 8)
    }

    /// bit0 = last fragment for this symbol in this cycle
    #[inline(always)]
    pub fn flags(&self) -> u8 {
        le_u8(self.buf, MESSAGE_HEADER_LEN + 10)
    }

    /// Bytes per entry of the `orders` group, read from the wire.
    #[inline(always)]
    pub fn orders_block_length(&self) -> u16 {
        le_u16(self.buf, MESSAGE_HEADER_LEN + self.root_len)
    }

    /// Number of `orders` entries.
    #[inline(always)]
    pub fn orders_count(&self) -> u16 {
        le_u16(self.buf, MESSAGE_HEADER_LEN + self.root_len + 2)
    }

    /// Iterates the `orders` group. Resting orders in queue order, best price first within each side
    #[inline]
    pub fn orders(&self) -> SnapshotOrdersIter<'a> {
        SnapshotOrdersIter {
            buf: self.buf,
            pos: MESSAGE_HEADER_LEN + self.root_len + GROUP_SIZE_ENCODING_LEN,
            block_len: self.orders_block_length() as usize,
            remaining: self.orders_count(),
        }
    }

    /// Total bytes, header and group included.
    #[inline(always)]
    pub fn total_len(&self) -> usize {
        MESSAGE_HEADER_LEN
            + self.root_len
            + GROUP_SIZE_ENCODING_LEN
            + self.orders_count() as usize * self.orders_block_length() as usize
    }
}

/// One entry of the `Snapshot.orders` group.
#[derive(Debug, Clone, Copy)]
pub struct SnapshotOrderDecoder<'a> {
    buf: &'a [u8],
}

impl<'a> SnapshotOrderDecoder<'a> {
    pub const BLOCK_LENGTH: u16 = 24;

    #[inline(always)]
    pub fn order_id(&self) -> u64 {
        le_u64(self.buf, 0)
    }

    /// Fixed point, scaled by 10^-4.
    #[inline(always)]
    pub fn price(&self) -> i64 {
        le_i64(self.buf, 8)
    }

    #[inline(always)]
    pub fn quantity(&self) -> u32 {
        le_u32(self.buf, 16)
    }

    #[inline(always)]
    pub fn side_raw(&self) -> u8 {
        le_u8(self.buf, 20)
    }

    /// Validating accessor. Use `side_raw()` on the hot path.
    #[inline]
    pub fn side(&self) -> Result<Side, WireError> {
        Side::from_u8(self.side_raw())
    }
}

/// Iterator over `Snapshot.orders`.
#[derive(Debug, Clone, Copy)]
pub struct SnapshotOrdersIter<'a> {
    buf: &'a [u8],
    pos: usize,
    block_len: usize,
    remaining: u16,
}

impl<'a> Iterator for SnapshotOrdersIter<'a> {
    type Item = SnapshotOrderDecoder<'a>;

    #[inline]
    fn next(&mut self) -> Option<Self::Item> {
        if self.remaining == 0 {
            return None;
        }
        self.remaining -= 1;
        let start = self.pos;
        self.pos += self.block_len;
        Some(SnapshotOrderDecoder {
            buf: &self.buf[start..self.pos],
        })
    }

    #[inline]
    fn size_hint(&self) -> (usize, Option<usize>) {
        (self.remaining as usize, Some(self.remaining as usize))
    }
}

impl<'a> ExactSizeIterator for SnapshotOrdersIter<'a> {}

/// Two-phase encoder for `Snapshot`, which carries a repeating group.
///
/// Writes straight into a caller-owned buffer: `start`, then one
/// `push_order` per entry, then `finish`. No allocation anywhere.
#[derive(Debug)]
pub struct SnapshotEncoder<'a> {
    buf: &'a mut [u8],
    pos: usize,
    count: u16,
}

impl<'a> SnapshotEncoder<'a> {
    #[inline]
    pub fn start(
        buf: &'a mut [u8],
        last_sequence: u64,
        symbol_id: u16,
        flags: u8,
    ) -> Result<Self, WireError> {
        const HEAD: usize = MESSAGE_HEADER_LEN + 12 + GROUP_SIZE_ENCODING_LEN;
        if buf.len() < HEAD {
            return Err(WireError::ShortBuffer {
                needed: HEAD,
                got: buf.len(),
            });
        }
        buf[..HEAD].fill(0);
        write_message_header(buf, 12, template::SNAPSHOT);
        put_u64(buf, MESSAGE_HEADER_LEN, last_sequence);
        put_u16(buf, MESSAGE_HEADER_LEN + 8, symbol_id);
        put_u8(buf, MESSAGE_HEADER_LEN + 10, flags);
        put_u16(buf, MESSAGE_HEADER_LEN + 12, 24);
        Ok(Self {
            buf,
            pos: HEAD,
            count: 0,
        })
    }

    /// Appends one `orders` entry.
    #[inline]
    pub fn push_order(
        &mut self,
        order_id: u64,
        price: i64,
        quantity: u32,
        side: Side,
    ) -> Result<(), WireError> {
        const ENTRY: usize = 24;
        if self.buf.len() < self.pos + ENTRY {
            return Err(WireError::ShortBuffer {
                needed: self.pos + ENTRY,
                got: self.buf.len(),
            });
        }
        if self.count == u16::MAX {
            return Err(WireError::GroupOverflow { group: "orders" });
        }
        let base = self.pos;
        self.buf[base..base + ENTRY].fill(0);
        put_u64(self.buf, base, order_id);
        put_i64(self.buf, base + 8, price);
        put_u32(self.buf, base + 16, quantity);
        put_u8(self.buf, base + 20, side as u8);
        self.pos += ENTRY;
        self.count += 1;
        Ok(())
    }

    /// Patches the group count and returns the total bytes written.
    #[inline]
    pub fn finish(self) -> usize {
        put_u16(self.buf, MESSAGE_HEADER_LEN + 12 + 2, self.count);
        self.pos
    }
}

// --- Heartbeat -----------------------------------------------------

/// Published on an idle channel so a handler can tell quiet from dead
///
/// Borrows the datagram; decoding copies nothing.
#[derive(Debug, Clone, Copy)]
pub struct HeartbeatDecoder<'a> {
    buf: &'a [u8],
    root_len: usize,
}

impl<'a> HeartbeatDecoder<'a> {
    pub const TEMPLATE_ID: u16 = 6;
    pub const BLOCK_LENGTH: u16 = 8;

    /// Wraps a buffer whose first byte is the message header.
    ///
    /// The root block length comes from the wire, not from the constant,
    /// so a newer publisher that appended fields is skipped correctly
    /// rather than misparsed.
    #[inline]
    pub fn wrap(buf: &'a [u8]) -> Result<Self, WireError> {
        let hdr = MessageHeaderDecoder::wrap(buf)?;
        if hdr.template_id() != Self::TEMPLATE_ID {
            return Err(WireError::TemplateMismatch {
                expected: Self::TEMPLATE_ID,
                got: hdr.template_id(),
            });
        }
        let root_len = hdr.block_length() as usize;
        if root_len < Self::BLOCK_LENGTH as usize {
            return Err(WireError::BlockTooSmall {
                message: "Heartbeat",
                needed: Self::BLOCK_LENGTH,
                got: hdr.block_length(),
            });
        }
        let need = MESSAGE_HEADER_LEN + root_len;
        if buf.len() < need {
            return Err(WireError::ShortBuffer {
                needed: need,
                got: buf.len(),
            });
        }
        let d = Self { buf, root_len };
        Ok(d)
    }

    /// Highest sequence published so far on this channel
    #[inline(always)]
    pub fn last_sequence(&self) -> u64 {
        le_u64(self.buf, MESSAGE_HEADER_LEN)
    }

    /// Total bytes, header included.
    #[inline(always)]
    pub fn total_len(&self) -> usize {
        MESSAGE_HEADER_LEN + self.root_len
    }
}

/// Encodes a `Heartbeat` at `buf[0]`, header included.
///
/// Returns the bytes written. Reserved bytes are zeroed, which is what
/// makes a re-encode byte-identical to the golden vector.
#[inline]
pub fn encode_heartbeat(buf: &mut [u8], last_sequence: u64) -> Result<usize, WireError> {
    const LEN: usize = MESSAGE_HEADER_LEN + 8;
    if buf.len() < LEN {
        return Err(WireError::ShortBuffer {
            needed: LEN,
            got: buf.len(),
        });
    }
    buf[..LEN].fill(0);
    write_message_header(buf, 8, template::HEARTBEAT);
    put_u64(buf, MESSAGE_HEADER_LEN, last_sequence);
    Ok(LEN)
}

// --- SequenceReset -------------------------------------------------

/// The publisher restarts its sequence; the handler must resynchronise
///
/// Borrows the datagram; decoding copies nothing.
#[derive(Debug, Clone, Copy)]
pub struct SequenceResetDecoder<'a> {
    buf: &'a [u8],
    root_len: usize,
}

impl<'a> SequenceResetDecoder<'a> {
    pub const TEMPLATE_ID: u16 = 7;
    pub const BLOCK_LENGTH: u16 = 8;

    /// Wraps a buffer whose first byte is the message header.
    ///
    /// The root block length comes from the wire, not from the constant,
    /// so a newer publisher that appended fields is skipped correctly
    /// rather than misparsed.
    #[inline]
    pub fn wrap(buf: &'a [u8]) -> Result<Self, WireError> {
        let hdr = MessageHeaderDecoder::wrap(buf)?;
        if hdr.template_id() != Self::TEMPLATE_ID {
            return Err(WireError::TemplateMismatch {
                expected: Self::TEMPLATE_ID,
                got: hdr.template_id(),
            });
        }
        let root_len = hdr.block_length() as usize;
        if root_len < Self::BLOCK_LENGTH as usize {
            return Err(WireError::BlockTooSmall {
                message: "SequenceReset",
                needed: Self::BLOCK_LENGTH,
                got: hdr.block_length(),
            });
        }
        let need = MESSAGE_HEADER_LEN + root_len;
        if buf.len() < need {
            return Err(WireError::ShortBuffer {
                needed: need,
                got: buf.len(),
            });
        }
        let d = Self { buf, root_len };
        Ok(d)
    }

    /// The sequence the next message will carry
    #[inline(always)]
    pub fn new_sequence(&self) -> u64 {
        le_u64(self.buf, MESSAGE_HEADER_LEN)
    }

    /// Total bytes, header included.
    #[inline(always)]
    pub fn total_len(&self) -> usize {
        MESSAGE_HEADER_LEN + self.root_len
    }
}

/// Encodes a `SequenceReset` at `buf[0]`, header included.
///
/// Returns the bytes written. Reserved bytes are zeroed, which is what
/// makes a re-encode byte-identical to the golden vector.
#[inline]
pub fn encode_sequence_reset(buf: &mut [u8], new_sequence: u64) -> Result<usize, WireError> {
    const LEN: usize = MESSAGE_HEADER_LEN + 8;
    if buf.len() < LEN {
        return Err(WireError::ShortBuffer {
            needed: LEN,
            got: buf.len(),
        });
    }
    buf[..LEN].fill(0);
    write_message_header(buf, 8, template::SEQUENCE_RESET);
    put_u64(buf, MESSAGE_HEADER_LEN, new_sequence);
    Ok(LEN)
}

/// One decoded message, still borrowing the datagram buffer.
#[derive(Debug, Clone, Copy)]
pub enum Message<'a> {
    AddOrder(AddOrderDecoder<'a>),
    ModifyOrder(ModifyOrderDecoder<'a>),
    DeleteOrder(DeleteOrderDecoder<'a>),
    Trade(TradeDecoder<'a>),
    Snapshot(SnapshotDecoder<'a>),
    Heartbeat(HeartbeatDecoder<'a>),
    SequenceReset(SequenceResetDecoder<'a>),
}

impl<'a> Message<'a> {
    /// Total bytes this message occupies, header included.
    #[inline(always)]
    pub fn total_len(&self) -> usize {
        match self {
            Self::AddOrder(d) => d.total_len(),
            Self::ModifyOrder(d) => d.total_len(),
            Self::DeleteOrder(d) => d.total_len(),
            Self::Trade(d) => d.total_len(),
            Self::Snapshot(d) => d.total_len(),
            Self::Heartbeat(d) => d.total_len(),
            Self::SequenceReset(d) => d.total_len(),
        }
    }

    #[inline(always)]
    pub fn template_id(&self) -> u16 {
        match self {
            Self::AddOrder(_) => template::ADD_ORDER,
            Self::ModifyOrder(_) => template::MODIFY_ORDER,
            Self::DeleteOrder(_) => template::DELETE_ORDER,
            Self::Trade(_) => template::TRADE,
            Self::Snapshot(_) => template::SNAPSHOT,
            Self::Heartbeat(_) => template::HEARTBEAT,
            Self::SequenceReset(_) => template::SEQUENCE_RESET,
        }
    }
}

/// Decodes the message starting at `buf[0]`.
#[inline]
pub fn decode_message(buf: &[u8]) -> Result<Message<'_>, WireError> {
    let hdr = MessageHeaderDecoder::wrap(buf)?;
    if hdr.schema_id() != SCHEMA_ID {
        return Err(WireError::SchemaMismatch {
            expected: SCHEMA_ID,
            got: hdr.schema_id(),
        });
    }
    match hdr.template_id() {
        template::ADD_ORDER => Ok(Message::AddOrder(AddOrderDecoder::wrap(buf)?)),
        template::MODIFY_ORDER => Ok(Message::ModifyOrder(ModifyOrderDecoder::wrap(buf)?)),
        template::DELETE_ORDER => Ok(Message::DeleteOrder(DeleteOrderDecoder::wrap(buf)?)),
        template::TRADE => Ok(Message::Trade(TradeDecoder::wrap(buf)?)),
        template::SNAPSHOT => Ok(Message::Snapshot(SnapshotDecoder::wrap(buf)?)),
        template::HEARTBEAT => Ok(Message::Heartbeat(HeartbeatDecoder::wrap(buf)?)),
        template::SEQUENCE_RESET => Ok(Message::SequenceReset(SequenceResetDecoder::wrap(buf)?)),
        other => Err(WireError::UnknownTemplate(other)),
    }
}

/// Walks the messages in one datagram.
///
/// The sequence of message `i` is `firstSequence + i`; nothing on the wire
/// repeats it, which is what keeps the per-message framing at 8 bytes.
#[derive(Debug, Clone, Copy)]
pub struct PacketReader<'a> {
    buf: &'a [u8],
    header: PacketHeaderDecoder<'a>,
}

impl<'a> PacketReader<'a> {
    #[inline]
    pub fn new(buf: &'a [u8]) -> Result<Self, WireError> {
        let header = PacketHeaderDecoder::wrap(buf)?;
        Ok(Self { buf, header })
    }

    #[inline(always)]
    pub fn header(&self) -> PacketHeaderDecoder<'a> {
        self.header
    }

    #[inline]
    pub fn messages(&self) -> PacketMessageIter<'a> {
        PacketMessageIter {
            buf: self.buf,
            pos: PACKET_HEADER_LEN,
            sequence: self.header.first_sequence(),
            remaining: self.header.message_count(),
            failed: false,
        }
    }
}

/// Yields `(sequence, message)` pairs, or the first decode error and
/// then nothing -- a truncated datagram must not look like a short one.
#[derive(Debug, Clone, Copy)]
pub struct PacketMessageIter<'a> {
    buf: &'a [u8],
    pos: usize,
    sequence: u64,
    remaining: u16,
    failed: bool,
}

impl<'a> Iterator for PacketMessageIter<'a> {
    type Item = Result<(u64, Message<'a>), WireError>;

    #[inline]
    fn next(&mut self) -> Option<Self::Item> {
        if self.failed || self.remaining == 0 {
            return None;
        }
        match decode_message(&self.buf[self.pos..]) {
            Ok(msg) => {
                let seq = self.sequence;
                self.pos += msg.total_len();
                self.sequence += 1;
                self.remaining -= 1;
                Some(Ok((seq, msg)))
            }
            Err(e) => {
                self.failed = true;
                Some(Err(e))
            }
        }
    }
}

/// Packs messages into one datagram buffer.
///
/// Batching is not a detail here: at one message per datagram the kernel
/// UDP path is the ceiling, so the publisher packs many messages behind a
/// single header and reads the clock once. See docs/WIRE.md.
#[derive(Debug)]
pub struct PacketWriter<'a> {
    buf: &'a mut [u8],
    pos: usize,
    count: u16,
}

impl<'a> PacketWriter<'a> {
    #[inline]
    pub fn new(
        buf: &'a mut [u8],
        channel: u8,
        flags: u8,
        first_sequence: u64,
        send_timestamp_ns: u64,
    ) -> Result<Self, WireError> {
        encode_packet_header(buf, channel, flags, first_sequence, send_timestamp_ns)?;
        Ok(Self {
            buf,
            pos: PACKET_HEADER_LEN,
            count: 0,
        })
    }

    /// Bytes still free in the datagram.
    #[inline(always)]
    pub fn remaining(&self) -> usize {
        self.buf.len() - self.pos
    }

    #[inline(always)]
    pub fn message_count(&self) -> u16 {
        self.count
    }

    /// The unwritten tail, for encoders that write themselves.
    #[inline(always)]
    pub fn tail(&mut self) -> &mut [u8] {
        &mut self.buf[self.pos..]
    }

    /// Records `n` bytes written into [`tail`](Self::tail) as one message.
    #[inline]
    pub fn commit(&mut self, n: usize) -> Result<(), WireError> {
        if self.pos + n > self.buf.len() {
            return Err(WireError::ShortBuffer {
                needed: self.pos + n,
                got: self.buf.len(),
            });
        }
        if self.count == u16::MAX {
            return Err(WireError::GroupOverflow { group: "packet" });
        }
        self.pos += n;
        self.count += 1;
        Ok(())
    }

    /// Appends a `AddOrder`.
    #[inline]
    pub fn add_order(
        &mut self,
        order_id: u64,
        price: i64,
        quantity: u32,
        symbol_id: u16,
        side: Side,
    ) -> Result<(), WireError> {
        let n = encode_add_order(
            &mut self.buf[self.pos..],
            order_id,
            price,
            quantity,
            symbol_id,
            side,
        )?;
        self.pos += n;
        self.count += 1;
        Ok(())
    }

    /// Appends a `ModifyOrder`.
    #[inline]
    pub fn modify_order(
        &mut self,
        order_id: u64,
        new_price: i64,
        new_quantity: u32,
        symbol_id: u16,
        side: Side,
        reason: ModifyReason,
    ) -> Result<(), WireError> {
        let n = encode_modify_order(
            &mut self.buf[self.pos..],
            order_id,
            new_price,
            new_quantity,
            symbol_id,
            side,
            reason,
        )?;
        self.pos += n;
        self.count += 1;
        Ok(())
    }

    /// Appends a `DeleteOrder`.
    #[inline]
    pub fn delete_order(
        &mut self,
        order_id: u64,
        symbol_id: u16,
        side: Side,
    ) -> Result<(), WireError> {
        let n = encode_delete_order(&mut self.buf[self.pos..], order_id, symbol_id, side)?;
        self.pos += n;
        self.count += 1;
        Ok(())
    }

    /// Appends a `Trade`.
    #[inline]
    pub fn trade(
        &mut self,
        trade_id: u64,
        aggressor_order_id: u64,
        resting_order_id: u64,
        price: i64,
        quantity: u32,
        symbol_id: u16,
        aggressor_side: Side,
    ) -> Result<(), WireError> {
        let n = encode_trade(
            &mut self.buf[self.pos..],
            trade_id,
            aggressor_order_id,
            resting_order_id,
            price,
            quantity,
            symbol_id,
            aggressor_side,
        )?;
        self.pos += n;
        self.count += 1;
        Ok(())
    }

    /// Appends a `Heartbeat`.
    #[inline]
    pub fn heartbeat(&mut self, last_sequence: u64) -> Result<(), WireError> {
        let n = encode_heartbeat(&mut self.buf[self.pos..], last_sequence)?;
        self.pos += n;
        self.count += 1;
        Ok(())
    }

    /// Appends a `SequenceReset`.
    #[inline]
    pub fn sequence_reset(&mut self, new_sequence: u64) -> Result<(), WireError> {
        let n = encode_sequence_reset(&mut self.buf[self.pos..], new_sequence)?;
        self.pos += n;
        self.count += 1;
        Ok(())
    }

    /// Patches `messageCount` and returns the datagram length.
    #[inline]
    pub fn finish(self) -> usize {
        let count = self.count;
        let pos = self.pos;
        // `new` wrote the header, so the buffer is known long enough.
        put_u16(self.buf, 4, count);
        pos
    }
}
