#!/usr/bin/env python3
"""Generate the Rust codec and the C++ header from schema/market-data.xml.

    python3 schema/codegen.py            # write the generated files
    python3 schema/codegen.py --check    # fail if the committed files are stale

Nothing outside this script and the schema knows a field offset. If the two
generated files ever disagree about a byte, it is a bug in here rather than a
divergence between two hand-written codecs -- which is the whole point, because
cross-language wire drift shows up as a corrupted field under load rather than
as a compile error.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
import xml.etree.ElementTree as ET
from dataclasses import dataclass, field as dc_field
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SCHEMA_PATH = REPO / "schema" / "market-data.xml"
RUST_OUT = REPO / "crates" / "wire" / "src" / "generated.rs"
CPP_OUT = REPO / "cpp" / "wire" / "include" / "wire" / "generated.hpp"

BANNER_LINES = [
    "@generated by schema/codegen.py from schema/market-data.xml -- do not edit.",
    "",
    "Edit the schema and run `make codegen`. CI regenerates and diffs, so a",
    "hand-edit here fails the build rather than silently surviving.",
]

# ---------------------------------------------------------------------------
# schema model
# ---------------------------------------------------------------------------

PRIMITIVES = {
    "uint8": (1, "u8", "std::uint8_t"),
    "uint16": (2, "u16", "std::uint16_t"),
    "uint32": (4, "u32", "std::uint32_t"),
    "uint64": (8, "u64", "std::uint64_t"),
    "int8": (1, "i8", "std::int8_t"),
    "int16": (2, "i16", "std::int16_t"),
    "int32": (4, "i32", "std::int32_t"),
    "int64": (8, "i64", "std::int64_t"),
}


@dataclass
class Field:
    name: str
    type_name: str
    offset: int
    description: str = ""
    semantic_type: str = ""

    @property
    def is_reserved(self) -> bool:
        return self.name.startswith("reserved")


@dataclass
class Enum:
    name: str
    encoding: str
    values: list[tuple[str, int]]


@dataclass
class Composite:
    name: str
    fields: list[Field]
    description: str = ""

    @property
    def length(self) -> int:
        return max(f.offset + size_of(f.type_name, {}) for f in self.fields)


@dataclass
class Group:
    name: str
    id: int
    block_length: int
    fields: list[Field]
    description: str = ""


@dataclass
class Message:
    name: str
    id: int
    block_length: int
    fields: list[Field]
    description: str = ""
    group: Group | None = None


@dataclass
class Schema:
    package: str
    id: int
    version: int
    semantic_version: str
    byte_order: str
    description: str
    constants: dict[str, str] = dc_field(default_factory=dict)
    enums: dict[str, Enum] = dc_field(default_factory=dict)
    composites: dict[str, Composite] = dc_field(default_factory=dict)
    messages: list[Message] = dc_field(default_factory=list)


def size_of(type_name: str, enums: dict[str, Enum]) -> int:
    if type_name in PRIMITIVES:
        return PRIMITIVES[type_name][0]
    if type_name in enums:
        return PRIMITIVES[enums[type_name].encoding][0]
    raise SchemaError(f"unknown type {type_name!r}")


class SchemaError(Exception):
    pass


def _fields(node: ET.Element) -> list[Field]:
    out = []
    for f in node.findall("field"):
        out.append(
            Field(
                name=f.attrib["name"],
                type_name=f.attrib["type"],
                offset=int(f.attrib["offset"]),
                description=f.attrib.get("description", ""),
                semantic_type=f.attrib.get("semanticType", ""),
            )
        )
    return out


def parse_schema(path: Path = SCHEMA_PATH) -> Schema:
    root = ET.parse(path).getroot()
    schema = Schema(
        package=root.attrib["package"],
        id=int(root.attrib["id"]),
        version=int(root.attrib["version"]),
        semantic_version=root.attrib.get("semanticVersion", ""),
        byte_order=root.attrib.get("byteOrder", "littleEndian"),
        description=root.attrib.get("description", ""),
    )
    if schema.byte_order != "littleEndian":
        raise SchemaError("only littleEndian is supported")

    types = root.find("types")
    if types is None:
        raise SchemaError("schema has no <types>")

    for c in types.findall("constant"):
        schema.constants[c.attrib["name"]] = c.attrib["value"]

    for e in types.findall("enum"):
        values = [(v.attrib["name"], int(v.text.strip())) for v in e.findall("validValue")]
        schema.enums[e.attrib["name"]] = Enum(
            name=e.attrib["name"], encoding=e.attrib["encodingType"], values=values
        )

    for c in types.findall("composite"):
        schema.composites[c.attrib["name"]] = Composite(
            name=c.attrib["name"],
            fields=_fields(c),
            description=c.attrib.get("description", ""),
        )

    for m in root.findall("message"):
        group = None
        g = m.find("group")
        if g is not None:
            group = Group(
                name=g.attrib["name"],
                id=int(g.attrib["id"]),
                block_length=int(g.attrib["blockLength"]),
                fields=_fields(g),
                description=g.attrib.get("description", ""),
            )
        schema.messages.append(
            Message(
                name=m.attrib["name"],
                id=int(m.attrib["id"]),
                block_length=int(m.attrib["blockLength"]),
                fields=_fields(m),
                description=m.attrib.get("description", ""),
                group=group,
            )
        )

    validate(schema)
    return schema


def validate(schema: Schema) -> None:
    """Catch the layout mistakes that would otherwise surface as corrupt fields."""
    for required in ("packetHeader", "messageHeader", "groupSizeEncoding"):
        if required not in schema.composites:
            raise SchemaError(f"schema is missing the {required} composite")

    def check_block(what: str, fields: list[Field], declared: int) -> None:
        if not fields:
            raise SchemaError(f"{what} has no fields")
        seen: dict[int, str] = {}
        for f in fields:
            width = size_of(f.type_name, schema.enums)
            for b in range(f.offset, f.offset + width):
                if b in seen:
                    raise SchemaError(
                        f"{what}: {f.name} overlaps {seen[b]} at byte {b}"
                    )
                seen[b] = f.name
            if f.offset % width != 0:
                raise SchemaError(
                    f"{what}: {f.name} at offset {f.offset} is not {width}-byte aligned "
                    f"within its block"
                )
        extent = max(f.offset + size_of(f.type_name, schema.enums) for f in fields)
        if extent != declared:
            raise SchemaError(
                f"{what}: fields extend to {extent} bytes but blockLength says {declared}. "
                f"Every byte of a block must be named, padding included."
            )

    for c in schema.composites.values():
        check_block(f"composite {c.name}", c.fields, c.length)

    ids: dict[int, str] = {}
    names: set[str] = set()
    for m in schema.messages:
        if m.id in ids:
            raise SchemaError(f"template id {m.id} used by both {ids[m.id]} and {m.name}")
        ids[m.id] = m.name
        if m.name in names:
            raise SchemaError(f"duplicate message name {m.name}")
        names.add(m.name)
        check_block(f"message {m.name}", m.fields, m.block_length)
        if m.group is not None:
            check_block(
                f"message {m.name} group {m.group.name}",
                m.group.fields,
                m.group.block_length,
            )


# ---------------------------------------------------------------------------
# naming
# ---------------------------------------------------------------------------


def snake(name: str) -> str:
    out = []
    for i, ch in enumerate(name):
        if ch.isupper() and i > 0 and not name[i - 1].isupper():
            out.append("_")
        out.append(ch.lower())
    return "".join(out)


def screaming(name: str) -> str:
    return snake(name).upper()


def pascal(name: str) -> str:
    return name[0].upper() + name[1:]


def singular(name: str) -> str:
    return name[:-1] if name.endswith("s") else name


def off_expr(base: str, offset: int) -> str:
    """`base + offset` without the `+ 0` that clippy's identity_op rejects."""
    if offset == 0:
        return base
    if base == "0":
        return str(offset)
    return f"{base} + {offset}"


# ---------------------------------------------------------------------------
# Rust emitter
# ---------------------------------------------------------------------------


def rust_type(type_name: str, schema: Schema) -> str:
    if type_name in PRIMITIVES:
        return PRIMITIVES[type_name][1]
    if type_name in schema.enums:
        return PRIMITIVES[schema.enums[type_name].encoding][1]
    raise SchemaError(f"unknown type {type_name!r}")


def rust_accessors(
    out: list[str],
    fields: list[Field],
    schema: Schema,
    base: str,
    indent: str = "    ",
) -> None:
    """Emit read accessors for one block. `base` is a Rust expression for the
    byte offset of the block within `self.buf`."""
    for f in fields:
        if f.is_reserved:
            continue
        prim = rust_type(f.type_name, schema)
        name = snake(f.name)
        doc = f.description
        is_enum = f.type_name in schema.enums
        if doc:
            out.append(f"{indent}/// {doc}")
        if f.semantic_type == "Price":
            out.append(
                f"{indent}/// Fixed point, scaled by 10^{schema.constants['priceExponent']}."
            )
        raw_name = f"{name}_raw" if is_enum else name
        out.append(f"{indent}#[inline(always)]")
        out.append(f"{indent}pub fn {raw_name}(&self) -> {prim} {{")
        out.append(f"{indent}    le_{prim}(self.buf, {off_expr(base, f.offset)})")
        out.append(f"{indent}}}")
        out.append("")
        if is_enum:
            enum_name = pascal(f.type_name)
            out.append(f"{indent}/// Validating accessor. Use `{raw_name}()` on the hot path.")
            out.append(f"{indent}#[inline]")
            out.append(
                f"{indent}pub fn {name}(&self) -> Result<{enum_name}, WireError> {{"
            )
            out.append(f"{indent}    {enum_name}::from_{prim}(self.{raw_name}())")
            out.append(f"{indent}}}")
            out.append("")


def rust_param_list(fields: list[Field], schema: Schema) -> list[tuple[str, str, Field]]:
    params = []
    for f in fields:
        if f.is_reserved:
            continue
        if f.type_name in schema.enums:
            params.append((snake(f.name), pascal(f.type_name), f))
        else:
            params.append((snake(f.name), rust_type(f.type_name, schema), f))
    return params


def rust_write_field(
    out: list[str], f: Field, schema: Schema, base: str, indent: str, buf: str = "buf"
) -> None:
    prim = rust_type(f.type_name, schema)
    name = snake(f.name)
    value = f"{name} as {prim}" if f.type_name in schema.enums else name
    out.append(f"{indent}put_{prim}({buf}, {off_expr(base, f.offset)}, {value});")


def used_rust_prims(schema: Schema) -> list[str]:
    """Only emit the little-endian helpers the schema actually uses; an unused
    private fn is a dead_code warning, and this crate builds with -D warnings."""
    used = {"u16"}  # both framing headers are u16-only
    blocks: list[list[Field]] = [c.fields for c in schema.composites.values()]
    for m in schema.messages:
        blocks.append(m.fields)
        if m.group is not None:
            blocks.append(m.group.fields)
    for fields in blocks:
        for f in fields:
            used.add(rust_type(f.type_name, schema))
    order = ["u8", "i8", "u16", "i16", "u32", "i32", "u64", "i64"]
    return [t for t in order if t in used]


def emit_rust(schema: Schema) -> str:
    o: list[str] = []
    for line in BANNER_LINES:
        o.append(f"//! {line}" if line else "//!")
    o.append("")
    o.append("#![allow(clippy::too_many_arguments)]")
    o.append("")
    o.append("use crate::error::WireError;")
    o.append("")

    ph = schema.composites["packetHeader"]
    mh = schema.composites["messageHeader"]
    gse = schema.composites["groupSizeEncoding"]

    o.append("/// Schema identity, checked on every datagram.")
    o.append(f"pub const SCHEMA_ID: u16 = {schema.id};")
    o.append(f"pub const SCHEMA_VERSION: u16 = {schema.version};")
    o.append(f'pub const SEMANTIC_VERSION: &str = "{schema.semantic_version}";')
    o.append("")
    for k, v in schema.constants.items():
        o.append(f"/// Schema constant `{k}`.")
        o.append(f"pub const {screaming(k)}: i8 = {v};")
    o.append("")
    o.append("/// Bytes of per-datagram framing.")
    o.append(f"pub const PACKET_HEADER_LEN: usize = {ph.length};")
    o.append("/// Bytes of per-message framing.")
    o.append(f"pub const MESSAGE_HEADER_LEN: usize = {mh.length};")
    o.append("/// Bytes of per-group framing.")
    o.append(f"pub const GROUP_SIZE_ENCODING_LEN: usize = {gse.length};")
    o.append("")
    o.append("/// `packetHeader.flags` bit 0: this datagram belongs to a snapshot cycle.")
    o.append("pub const PACKET_FLAG_SNAPSHOT: u8 = 0x01;")
    o.append("")

    # --- little-endian helpers -------------------------------------------
    o.append("// Unaligned-safe little-endian access. Messages are packed back to back")
    o.append("// inside a datagram, so a block can start at any byte offset; every read")
    o.append("// and write below goes through a fixed-size copy, which the compiler")
    o.append("// lowers to a single instruction on x86-64 and aarch64.")
    for t in used_rust_prims(schema):
        width = int(t[1:]) // 8
        o.append("#[inline(always)]")
        o.append(f"fn le_{t}(b: &[u8], o: usize) -> {t} {{")
        if t == "u8":
            o.append("    b[o]")
        elif width == 1:
            o.append(f"    b[o] as {t}")
        else:
            o.append(f"    let mut a = [0u8; {width}];")
            o.append(f"    a.copy_from_slice(&b[o..o + {width}]);")
            o.append(f"    {t}::from_le_bytes(a)")
        o.append("}")
        o.append("")
        o.append("#[inline(always)]")
        o.append(f"fn put_{t}(b: &mut [u8], o: usize, v: {t}) {{")
        if t == "u8":
            o.append("    b[o] = v;")
        elif width == 1:
            o.append("    b[o] = v as u8;")
        else:
            o.append(f"    b[o..o + {width}].copy_from_slice(&v.to_le_bytes());")
        o.append("}")
        o.append("")

    # --- enums ------------------------------------------------------------
    for e in schema.enums.values():
        prim = PRIMITIVES[e.encoding][1]
        o.append(f"/// `{e.name}` as encoded on the wire.")
        o.append("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]")
        o.append(f"#[repr({prim})]")
        o.append(f"pub enum {pascal(e.name)} {{")
        for vname, vval in e.values:
            o.append(f"    {pascal(vname)} = {vval},")
        o.append("}")
        o.append("")
        o.append(f"impl {pascal(e.name)} {{")
        o.append("    /// Reject anything the schema does not define rather than")
        o.append("    /// transmuting an unknown discriminant.")
        o.append("    #[inline]")
        o.append(f"    pub fn from_{prim}(v: {prim}) -> Result<Self, WireError> {{")
        o.append("        match v {")
        for vname, vval in e.values:
            o.append(f"            {vval} => Ok(Self::{pascal(vname)}),")
        o.append(
            f'            other => Err(WireError::InvalidEnum {{ name: "{e.name}", value: other as u64 }}),'
        )
        o.append("        }")
        o.append("    }")
        o.append("")
        o.append("    #[inline(always)]")
        o.append(f"    pub fn to_{prim}(self) -> {prim} {{")
        o.append(f"        self as {prim}")
        o.append("    }")
        o.append("}")
        o.append("")

    # --- template ids -----------------------------------------------------
    o.append("/// Template ids, as they appear in `messageHeader.templateId`.")
    o.append("pub mod template {")
    for m in schema.messages:
        o.append(f"    /// {m.description}")
        o.append(f"    pub const {screaming(m.name)}: u16 = {m.id};")
    o.append("}")
    o.append("")

    # --- packet header ----------------------------------------------------
    o.append("/// Read-only view over the 24-byte datagram header.")
    o.append("#[derive(Debug, Clone, Copy)]")
    o.append("pub struct PacketHeaderDecoder<'a> {")
    o.append("    buf: &'a [u8],")
    o.append("}")
    o.append("")
    o.append("impl<'a> PacketHeaderDecoder<'a> {")
    o.append("    /// Wraps a datagram. Fails on a short buffer or a foreign schema,")
    o.append("    /// which is the only place a wrong-feed datagram gets rejected.")
    o.append("    #[inline]")
    o.append("    pub fn wrap(buf: &'a [u8]) -> Result<Self, WireError> {")
    o.append("        if buf.len() < PACKET_HEADER_LEN {")
    o.append("            return Err(WireError::ShortBuffer {")
    o.append("                needed: PACKET_HEADER_LEN,")
    o.append("                got: buf.len(),")
    o.append("            });")
    o.append("        }")
    o.append("        let d = Self { buf };")
    o.append("        if d.schema_id() != SCHEMA_ID {")
    o.append("            return Err(WireError::SchemaMismatch {")
    o.append("                expected: SCHEMA_ID,")
    o.append("                got: d.schema_id(),")
    o.append("            });")
    o.append("        }")
    o.append("        Ok(d)")
    o.append("    }")
    o.append("")
    rust_accessors(o, ph.fields, schema, "0")
    o.append("    /// True when this datagram is part of a snapshot cycle.")
    o.append("    #[inline(always)]")
    o.append("    pub fn is_snapshot(&self) -> bool {")
    o.append("        self.flags() & PACKET_FLAG_SNAPSHOT != 0")
    o.append("    }")
    o.append("}")
    o.append("")
    o.append("/// Writes the datagram header. `message_count` is patched by")
    o.append("/// [`patch_message_count`] once the messages have been written.")
    o.append("#[inline]")
    o.append("pub fn encode_packet_header(")
    o.append("    buf: &mut [u8],")
    for f in ph.fields:
        if f.name in ("schemaId", "version", "messageCount"):
            continue
        o.append(f"    {snake(f.name)}: {rust_type(f.type_name, schema)},")
    o.append(") -> Result<usize, WireError> {")
    o.append("    if buf.len() < PACKET_HEADER_LEN {")
    o.append("        return Err(WireError::ShortBuffer {")
    o.append("            needed: PACKET_HEADER_LEN,")
    o.append("            got: buf.len(),")
    o.append("        });")
    o.append("    }")
    o.append("    buf[..PACKET_HEADER_LEN].fill(0);")
    for f in ph.fields:
        if f.name == "schemaId":
            o.append(f"    put_u16(buf, {f.offset}, SCHEMA_ID);")
        elif f.name == "version":
            o.append(f"    put_u16(buf, {f.offset}, SCHEMA_VERSION);")
        elif f.name == "messageCount":
            o.append(f"    put_u16(buf, {f.offset}, 0);")
        else:
            rust_write_field(o, f, schema, "0", "    ")
    o.append("    Ok(PACKET_HEADER_LEN)")
    o.append("}")
    o.append("")
    mc_off = next(f.offset for f in ph.fields if f.name == "messageCount")
    o.append("/// Patches `messageCount` in a header written by [`encode_packet_header`].")
    o.append("#[inline]")
    o.append("pub fn patch_message_count(buf: &mut [u8], count: u16) -> Result<(), WireError> {")
    o.append("    if buf.len() < PACKET_HEADER_LEN {")
    o.append("        return Err(WireError::ShortBuffer {")
    o.append("            needed: PACKET_HEADER_LEN,")
    o.append("            got: buf.len(),")
    o.append("        });")
    o.append("    }")
    o.append(f"    put_u16(buf, {mc_off}, count);")
    o.append("    Ok(())")
    o.append("}")
    o.append("")

    # --- message header ---------------------------------------------------
    o.append("/// Read-only view over the 8-byte message header.")
    o.append("#[derive(Debug, Clone, Copy)]")
    o.append("pub struct MessageHeaderDecoder<'a> {")
    o.append("    buf: &'a [u8],")
    o.append("}")
    o.append("")
    o.append("impl<'a> MessageHeaderDecoder<'a> {")
    o.append("    #[inline]")
    o.append("    pub fn wrap(buf: &'a [u8]) -> Result<Self, WireError> {")
    o.append("        if buf.len() < MESSAGE_HEADER_LEN {")
    o.append("            return Err(WireError::ShortBuffer {")
    o.append("                needed: MESSAGE_HEADER_LEN,")
    o.append("                got: buf.len(),")
    o.append("            });")
    o.append("        }")
    o.append("        Ok(Self { buf })")
    o.append("    }")
    o.append("")
    rust_accessors(o, mh.fields, schema, "0")
    o.append("}")
    o.append("")
    o.append("#[inline(always)]")
    o.append("fn write_message_header(buf: &mut [u8], block_length: u16, template_id: u16) {")
    for f in mh.fields:
        src = {
            "blockLength": "block_length",
            "templateId": "template_id",
            "schemaId": "SCHEMA_ID",
            "version": "SCHEMA_VERSION",
        }[f.name]
        o.append(f"    put_u16(buf, {f.offset}, {src});")
    o.append("}")
    o.append("")

    # --- per-message decoders and encoders --------------------------------
    for m in schema.messages:
        emit_rust_message(o, m, schema)

    # --- dispatch ---------------------------------------------------------
    o.append("/// One decoded message, still borrowing the datagram buffer.")
    o.append("#[derive(Debug, Clone, Copy)]")
    o.append("pub enum Message<'a> {")
    for m in schema.messages:
        o.append(f"    {m.name}({m.name}Decoder<'a>),")
    o.append("}")
    o.append("")
    o.append("impl<'a> Message<'a> {")
    o.append("    /// Total bytes this message occupies, header included.")
    o.append("    #[inline(always)]")
    o.append("    pub fn total_len(&self) -> usize {")
    o.append("        match self {")
    for m in schema.messages:
        o.append(f"            Self::{m.name}(d) => d.total_len(),")
    o.append("        }")
    o.append("    }")
    o.append("")
    o.append("    #[inline(always)]")
    o.append("    pub fn template_id(&self) -> u16 {")
    o.append("        match self {")
    for m in schema.messages:
        o.append(f"            Self::{m.name}(_) => template::{screaming(m.name)},")
    o.append("        }")
    o.append("    }")
    o.append("}")
    o.append("")
    o.append("/// Decodes the message starting at `buf[0]`.")
    o.append("#[inline]")
    o.append("pub fn decode_message(buf: &[u8]) -> Result<Message<'_>, WireError> {")
    o.append("    let hdr = MessageHeaderDecoder::wrap(buf)?;")
    o.append("    if hdr.schema_id() != SCHEMA_ID {")
    o.append("        return Err(WireError::SchemaMismatch {")
    o.append("            expected: SCHEMA_ID,")
    o.append("            got: hdr.schema_id(),")
    o.append("        });")
    o.append("    }")
    o.append("    match hdr.template_id() {")
    for m in schema.messages:
        o.append(
            f"        template::{screaming(m.name)} => "
            f"Ok(Message::{m.name}({m.name}Decoder::wrap(buf)?)),"
        )
    o.append("        other => Err(WireError::UnknownTemplate(other)),")
    o.append("    }")
    o.append("}")
    o.append("")

    emit_rust_packet_reader(o, schema)
    emit_rust_packet_writer(o, schema)

    return "\n".join(o).rstrip() + "\n"


def emit_rust_message(o: list[str], m: Message, schema: Schema) -> None:
    dec = f"{m.name}Decoder"
    o.append(f"// --- {m.name} " + "-" * max(0, 62 - len(m.name)))
    o.append("")
    o.append(f"/// {m.description}")
    o.append("///")
    o.append("/// Borrows the datagram; decoding copies nothing.")
    o.append("#[derive(Debug, Clone, Copy)]")
    o.append(f"pub struct {dec}<'a> {{")
    o.append("    buf: &'a [u8],")
    o.append("    root_len: usize,")
    o.append("}")
    o.append("")
    o.append(f"impl<'a> {dec}<'a> {{")
    o.append(f"    pub const TEMPLATE_ID: u16 = {m.id};")
    o.append(f"    pub const BLOCK_LENGTH: u16 = {m.block_length};")
    o.append("")
    o.append("    /// Wraps a buffer whose first byte is the message header.")
    o.append("    ///")
    o.append("    /// The root block length comes from the wire, not from the constant,")
    o.append("    /// so a newer publisher that appended fields is skipped correctly")
    o.append("    /// rather than misparsed.")
    o.append("    #[inline]")
    o.append("    pub fn wrap(buf: &'a [u8]) -> Result<Self, WireError> {")
    o.append("        let hdr = MessageHeaderDecoder::wrap(buf)?;")
    o.append("        if hdr.template_id() != Self::TEMPLATE_ID {")
    o.append("            return Err(WireError::TemplateMismatch {")
    o.append("                expected: Self::TEMPLATE_ID,")
    o.append("                got: hdr.template_id(),")
    o.append("            });")
    o.append("        }")
    o.append("        let root_len = hdr.block_length() as usize;")
    o.append("        if root_len < Self::BLOCK_LENGTH as usize {")
    o.append("            return Err(WireError::BlockTooSmall {")
    o.append('                message: "' + m.name + '",')
    o.append("                needed: Self::BLOCK_LENGTH,")
    o.append("                got: hdr.block_length(),")
    o.append("            });")
    o.append("        }")
    o.append("        let need = MESSAGE_HEADER_LEN + root_len;")
    o.append("        if buf.len() < need {")
    o.append("            return Err(WireError::ShortBuffer {")
    o.append("                needed: need,")
    o.append("                got: buf.len(),")
    o.append("            });")
    o.append("        }")
    o.append("        let d = Self { buf, root_len };")
    if m.group is not None:
        o.append("        // The group header has to be proved present before it can be")
        o.append("        // read: `total_len` reads it, so calling that first on a")
        o.append("        // truncated datagram would panic instead of returning an error.")
        o.append("        let with_group_header = need + GROUP_SIZE_ENCODING_LEN;")
        o.append("        if buf.len() < with_group_header {")
        o.append("            return Err(WireError::ShortBuffer {")
        o.append("                needed: with_group_header,")
        o.append("                got: buf.len(),")
        o.append("            });")
        o.append("        }")
        o.append("        // Now the entry count is readable, so the full extent is known.")
        o.append("        let total = d.total_len();")
        o.append("        if buf.len() < total {")
        o.append("            return Err(WireError::ShortBuffer {")
        o.append("                needed: total,")
        o.append("                got: buf.len(),")
        o.append("            });")
        o.append("        }")
    o.append("        Ok(d)")
    o.append("    }")
    o.append("")
    rust_accessors(o, m.fields, schema, "MESSAGE_HEADER_LEN")

    if m.group is None:
        o.append("    /// Total bytes, header included.")
        o.append("    #[inline(always)]")
        o.append("    pub fn total_len(&self) -> usize {")
        o.append("        MESSAGE_HEADER_LEN + self.root_len")
        o.append("    }")
        o.append("}")
        o.append("")
        emit_rust_plain_encoder(o, m, schema)
    else:
        g = m.group
        entry = f"{m.name}{pascal(singular(g.name))}Decoder"
        gse_off = "MESSAGE_HEADER_LEN + self.root_len"
        o.append(f"    /// Bytes per entry of the `{g.name}` group, read from the wire.")
        o.append("    #[inline(always)]")
        o.append(f"    pub fn {snake(g.name)}_block_length(&self) -> u16 {{")
        o.append(f"        le_u16(self.buf, {gse_off})")
        o.append("    }")
        o.append("")
        o.append(f"    /// Number of `{g.name}` entries.")
        o.append("    #[inline(always)]")
        o.append(f"    pub fn {snake(g.name)}_count(&self) -> u16 {{")
        o.append(f"        le_u16(self.buf, {gse_off} + 2)")
        o.append("    }")
        o.append("")
        o.append(f"    /// Iterates the `{g.name}` group. {g.description}")
        o.append("    #[inline]")
        o.append(f"    pub fn {snake(g.name)}(&self) -> {m.name}{pascal(g.name)}Iter<'a> {{")
        o.append(f"        {m.name}{pascal(g.name)}Iter {{")
        o.append(f"            buf: self.buf,")
        o.append(f"            pos: {gse_off} + GROUP_SIZE_ENCODING_LEN,")
        o.append(f"            block_len: self.{snake(g.name)}_block_length() as usize,")
        o.append(f"            remaining: self.{snake(g.name)}_count(),")
        o.append("        }")
        o.append("    }")
        o.append("")
        o.append("    /// Total bytes, header and group included.")
        o.append("    #[inline(always)]")
        o.append("    pub fn total_len(&self) -> usize {")
        o.append(f"        MESSAGE_HEADER_LEN")
        o.append("            + self.root_len")
        o.append("            + GROUP_SIZE_ENCODING_LEN")
        o.append(
            f"            + self.{snake(g.name)}_count() as usize "
            f"* self.{snake(g.name)}_block_length() as usize"
        )
        o.append("    }")
        o.append("}")
        o.append("")
        # group entry decoder
        o.append(f"/// One entry of the `{m.name}.{g.name}` group.")
        o.append("#[derive(Debug, Clone, Copy)]")
        o.append(f"pub struct {entry}<'a> {{")
        o.append("    buf: &'a [u8],")
        o.append("}")
        o.append("")
        o.append(f"impl<'a> {entry}<'a> {{")
        o.append(f"    pub const BLOCK_LENGTH: u16 = {g.block_length};")
        o.append("")
        rust_accessors(o, g.fields, schema, "0")
        o.append("}")
        o.append("")
        o.append(f"/// Iterator over `{m.name}.{g.name}`.")
        o.append("#[derive(Debug, Clone, Copy)]")
        o.append(f"pub struct {m.name}{pascal(g.name)}Iter<'a> {{")
        o.append("    buf: &'a [u8],")
        o.append("    pos: usize,")
        o.append("    block_len: usize,")
        o.append("    remaining: u16,")
        o.append("}")
        o.append("")
        o.append(f"impl<'a> Iterator for {m.name}{pascal(g.name)}Iter<'a> {{")
        o.append(f"    type Item = {entry}<'a>;")
        o.append("")
        o.append("    #[inline]")
        o.append("    fn next(&mut self) -> Option<Self::Item> {")
        o.append("        if self.remaining == 0 {")
        o.append("            return None;")
        o.append("        }")
        o.append("        self.remaining -= 1;")
        o.append("        let start = self.pos;")
        o.append("        self.pos += self.block_len;")
        o.append(f"        Some({entry} {{")
        o.append("            buf: &self.buf[start..self.pos],")
        o.append("        })")
        o.append("    }")
        o.append("")
        o.append("    #[inline]")
        o.append("    fn size_hint(&self) -> (usize, Option<usize>) {")
        o.append("        (self.remaining as usize, Some(self.remaining as usize))")
        o.append("    }")
        o.append("}")
        o.append("")
        o.append(
            f"impl<'a> ExactSizeIterator for {m.name}{pascal(g.name)}Iter<'a> {{}}"
        )
        o.append("")
        emit_rust_group_encoder(o, m, schema)


def emit_rust_plain_encoder(o: list[str], m: Message, schema: Schema) -> None:
    params = rust_param_list(m.fields, schema)
    o.append(f"/// Encodes a `{m.name}` at `buf[0]`, header included.")
    o.append("///")
    o.append("/// Returns the bytes written. Reserved bytes are zeroed, which is what")
    o.append("/// makes a re-encode byte-identical to the golden vector.")
    o.append("#[inline]")
    o.append(f"pub fn encode_{snake(m.name)}(")
    o.append("    buf: &mut [u8],")
    for name, ty, _ in params:
        o.append(f"    {name}: {ty},")
    o.append(") -> Result<usize, WireError> {")
    o.append(f"    const LEN: usize = MESSAGE_HEADER_LEN + {m.block_length};")
    o.append("    if buf.len() < LEN {")
    o.append("        return Err(WireError::ShortBuffer {")
    o.append("            needed: LEN,")
    o.append("            got: buf.len(),")
    o.append("        });")
    o.append("    }")
    o.append("    buf[..LEN].fill(0);")
    o.append(
        f"    write_message_header(buf, {m.block_length}, template::{screaming(m.name)});"
    )
    for f in m.fields:
        if f.is_reserved:
            continue
        rust_write_field(o, f, schema, "MESSAGE_HEADER_LEN", "    ")
    o.append("    Ok(LEN)")
    o.append("}")
    o.append("")


def emit_rust_group_encoder(o: list[str], m: Message, schema: Schema) -> None:
    g = m.group
    assert g is not None
    enc = f"{m.name}Encoder"
    root_params = rust_param_list(m.fields, schema)
    entry_params = rust_param_list(g.fields, schema)
    o.append(f"/// Two-phase encoder for `{m.name}`, which carries a repeating group.")
    o.append("///")
    o.append("/// Writes straight into a caller-owned buffer: `start`, then one")
    o.append(f"/// `push_{snake(singular(g.name))}` per entry, then `finish`. No allocation anywhere.")
    o.append("#[derive(Debug)]")
    o.append(f"pub struct {enc}<'a> {{")
    o.append("    buf: &'a mut [u8],")
    o.append("    pos: usize,")
    o.append("    count: u16,")
    o.append("}")
    o.append("")
    o.append(f"impl<'a> {enc}<'a> {{")
    o.append("    #[inline]")
    o.append("    pub fn start(")
    o.append("        buf: &'a mut [u8],")
    for name, ty, _ in root_params:
        o.append(f"        {name}: {ty},")
    o.append("    ) -> Result<Self, WireError> {")
    o.append(
        f"        const HEAD: usize = MESSAGE_HEADER_LEN + {m.block_length} + GROUP_SIZE_ENCODING_LEN;"
    )
    o.append("        if buf.len() < HEAD {")
    o.append("            return Err(WireError::ShortBuffer {")
    o.append("                needed: HEAD,")
    o.append("                got: buf.len(),")
    o.append("            });")
    o.append("        }")
    o.append("        buf[..HEAD].fill(0);")
    o.append(
        f"        write_message_header(buf, {m.block_length}, template::{screaming(m.name)});"
    )
    for f in m.fields:
        if f.is_reserved:
            continue
        rust_write_field(o, f, schema, "MESSAGE_HEADER_LEN", "        ")
    o.append(
        f"        put_u16(buf, MESSAGE_HEADER_LEN + {m.block_length}, {g.block_length});"
    )
    o.append("        Ok(Self {")
    o.append("            buf,")
    o.append("            pos: HEAD,")
    o.append("            count: 0,")
    o.append("        })")
    o.append("    }")
    o.append("")
    o.append(f"    /// Appends one `{g.name}` entry.")
    o.append("    #[inline]")
    o.append(f"    pub fn push_{snake(singular(g.name))}(")
    o.append("        &mut self,")
    for name, ty, _ in entry_params:
        o.append(f"        {name}: {ty},")
    o.append("    ) -> Result<(), WireError> {")
    o.append(f"        const ENTRY: usize = {g.block_length};")
    o.append("        if self.buf.len() < self.pos + ENTRY {")
    o.append("            return Err(WireError::ShortBuffer {")
    o.append("                needed: self.pos + ENTRY,")
    o.append("                got: self.buf.len(),")
    o.append("            });")
    o.append("        }")
    o.append("        if self.count == u16::MAX {")
    o.append("            return Err(WireError::GroupOverflow {")
    o.append('                group: "' + g.name + '",')
    o.append("            });")
    o.append("        }")
    o.append("        let base = self.pos;")
    o.append("        self.buf[base..base + ENTRY].fill(0);")
    for f in g.fields:
        if f.is_reserved:
            continue
        rust_write_field(o, f, schema, "base", "        ", buf="self.buf")
    o.append("        self.pos += ENTRY;")
    o.append("        self.count += 1;")
    o.append("        Ok(())")
    o.append("    }")
    o.append("")
    o.append("    /// Patches the group count and returns the total bytes written.")
    o.append("    #[inline]")
    o.append("    pub fn finish(self) -> usize {")
    o.append(
        f"        put_u16(self.buf, MESSAGE_HEADER_LEN + {m.block_length} + 2, self.count);"
    )
    o.append("        self.pos")
    o.append("    }")
    o.append("}")
    o.append("")


def emit_rust_packet_reader(o: list[str], schema: Schema) -> None:
    o.append("/// Walks the messages in one datagram.")
    o.append("///")
    o.append("/// The sequence of message `i` is `firstSequence + i`; nothing on the wire")
    o.append("/// repeats it, which is what keeps the per-message framing at 8 bytes.")
    o.append("#[derive(Debug, Clone, Copy)]")
    o.append("pub struct PacketReader<'a> {")
    o.append("    buf: &'a [u8],")
    o.append("    header: PacketHeaderDecoder<'a>,")
    o.append("}")
    o.append("")
    o.append("impl<'a> PacketReader<'a> {")
    o.append("    #[inline]")
    o.append("    pub fn new(buf: &'a [u8]) -> Result<Self, WireError> {")
    o.append("        let header = PacketHeaderDecoder::wrap(buf)?;")
    o.append("        Ok(Self { buf, header })")
    o.append("    }")
    o.append("")
    o.append("    #[inline(always)]")
    o.append("    pub fn header(&self) -> PacketHeaderDecoder<'a> {")
    o.append("        self.header")
    o.append("    }")
    o.append("")
    o.append("    #[inline]")
    o.append("    pub fn messages(&self) -> PacketMessageIter<'a> {")
    o.append("        PacketMessageIter {")
    o.append("            buf: self.buf,")
    o.append("            pos: PACKET_HEADER_LEN,")
    o.append("            sequence: self.header.first_sequence(),")
    o.append("            remaining: self.header.message_count(),")
    o.append("            failed: false,")
    o.append("        }")
    o.append("    }")
    o.append("}")
    o.append("")
    o.append("/// Yields `(sequence, message)` pairs, or the first decode error and")
    o.append("/// then nothing -- a truncated datagram must not look like a short one.")
    o.append("#[derive(Debug, Clone, Copy)]")
    o.append("pub struct PacketMessageIter<'a> {")
    o.append("    buf: &'a [u8],")
    o.append("    pos: usize,")
    o.append("    sequence: u64,")
    o.append("    remaining: u16,")
    o.append("    failed: bool,")
    o.append("}")
    o.append("")
    o.append("impl<'a> Iterator for PacketMessageIter<'a> {")
    o.append("    type Item = Result<(u64, Message<'a>), WireError>;")
    o.append("")
    o.append("    #[inline]")
    o.append("    fn next(&mut self) -> Option<Self::Item> {")
    o.append("        if self.failed || self.remaining == 0 {")
    o.append("            return None;")
    o.append("        }")
    o.append("        match decode_message(&self.buf[self.pos..]) {")
    o.append("            Ok(msg) => {")
    o.append("                let seq = self.sequence;")
    o.append("                self.pos += msg.total_len();")
    o.append("                self.sequence += 1;")
    o.append("                self.remaining -= 1;")
    o.append("                Some(Ok((seq, msg)))")
    o.append("            }")
    o.append("            Err(e) => {")
    o.append("                self.failed = true;")
    o.append("                Some(Err(e))")
    o.append("            }")
    o.append("        }")
    o.append("    }")
    o.append("}")
    o.append("")


def emit_rust_packet_writer(o: list[str], schema: Schema) -> None:
    mc_off = next(
        f.offset
        for f in schema.composites["packetHeader"].fields
        if f.name == "messageCount"
    )
    o.append("/// Packs messages into one datagram buffer.")
    o.append("///")
    o.append("/// Batching is not a detail here: at one message per datagram the kernel")
    o.append("/// UDP path is the ceiling, so the publisher packs many messages behind a")
    o.append("/// single header and reads the clock once. See docs/WIRE.md.")
    o.append("#[derive(Debug)]")
    o.append("pub struct PacketWriter<'a> {")
    o.append("    buf: &'a mut [u8],")
    o.append("    pos: usize,")
    o.append("    count: u16,")
    o.append("}")
    o.append("")
    o.append("impl<'a> PacketWriter<'a> {")
    o.append("    #[inline]")
    o.append("    pub fn new(")
    o.append("        buf: &'a mut [u8],")
    ph = schema.composites["packetHeader"]
    for f in ph.fields:
        if f.name in ("schemaId", "version", "messageCount"):
            continue
        o.append(f"        {snake(f.name)}: {rust_type(f.type_name, schema)},")
    o.append("    ) -> Result<Self, WireError> {")
    args = ", ".join(
        snake(f.name)
        for f in ph.fields
        if f.name not in ("schemaId", "version", "messageCount")
    )
    o.append(f"        encode_packet_header(buf, {args})?;")
    o.append("        Ok(Self {")
    o.append("            buf,")
    o.append("            pos: PACKET_HEADER_LEN,")
    o.append("            count: 0,")
    o.append("        })")
    o.append("    }")
    o.append("")
    o.append("    /// Bytes still free in the datagram.")
    o.append("    #[inline(always)]")
    o.append("    pub fn remaining(&self) -> usize {")
    o.append("        self.buf.len() - self.pos")
    o.append("    }")
    o.append("")
    o.append("    #[inline(always)]")
    o.append("    pub fn message_count(&self) -> u16 {")
    o.append("        self.count")
    o.append("    }")
    o.append("")
    o.append("    /// The unwritten tail, for encoders that write themselves.")
    o.append("    #[inline(always)]")
    o.append("    pub fn tail(&mut self) -> &mut [u8] {")
    o.append("        &mut self.buf[self.pos..]")
    o.append("    }")
    o.append("")
    o.append("    /// Records `n` bytes written into [`tail`](Self::tail) as one message.")
    o.append("    #[inline]")
    o.append("    pub fn commit(&mut self, n: usize) -> Result<(), WireError> {")
    o.append("        if self.pos + n > self.buf.len() {")
    o.append("            return Err(WireError::ShortBuffer {")
    o.append("                needed: self.pos + n,")
    o.append("                got: self.buf.len(),")
    o.append("            });")
    o.append("        }")
    o.append("        if self.count == u16::MAX {")
    o.append('            return Err(WireError::GroupOverflow { group: "packet" });')
    o.append("        }")
    o.append("        self.pos += n;")
    o.append("        self.count += 1;")
    o.append("        Ok(())")
    o.append("    }")
    o.append("")
    for m in schema.messages:
        if m.group is not None:
            continue
        params = rust_param_list(m.fields, schema)
        o.append(f"    /// Appends a `{m.name}`.")
        o.append("    #[inline]")
        o.append(f"    pub fn {snake(m.name)}(")
        o.append("        &mut self,")
        for name, ty, _ in params:
            o.append(f"        {name}: {ty},")
        o.append("    ) -> Result<(), WireError> {")
        call = ", ".join(name for name, _, _ in params)
        o.append(f"        let n = encode_{snake(m.name)}(&mut self.buf[self.pos..], {call})?;")
        o.append("        self.pos += n;")
        o.append("        self.count += 1;")
        o.append("        Ok(())")
        o.append("    }")
        o.append("")
    o.append("    /// Patches `messageCount` and returns the datagram length.")
    o.append("    #[inline]")
    o.append("    pub fn finish(self) -> usize {")
    o.append("        let count = self.count;")
    o.append("        let pos = self.pos;")
    o.append("        // `new` wrote the header, so the buffer is known long enough.")
    o.append(f"        put_u16(self.buf, {mc_off}, count);")
    o.append("        pos")
    o.append("    }")
    o.append("}")
    o.append("")


# ---------------------------------------------------------------------------
# C++ emitter
# ---------------------------------------------------------------------------


def cpp_type(type_name: str, schema: Schema) -> str:
    if type_name in PRIMITIVES:
        return PRIMITIVES[type_name][2]
    if type_name in schema.enums:
        return PRIMITIVES[schema.enums[type_name].encoding][2]
    raise SchemaError(f"unknown type {type_name!r}")


def cpp_accessors(
    out: list[str], fields: list[Field], schema: Schema, base: str, indent: str
) -> None:
    for f in fields:
        if f.is_reserved:
            continue
        prim = cpp_type(f.type_name, schema)
        name = snake(f.name)
        is_enum = f.type_name in schema.enums
        if f.description:
            out.append(f"{indent}/// {f.description}")
        if f.semantic_type == "Price":
            out.append(
                f"{indent}/// Fixed point, scaled by 10^{schema.constants['priceExponent']}."
            )
        raw = f"{name}_raw" if is_enum else name
        out.append(
            f"{indent}[[nodiscard]] {prim} {raw}() const noexcept "
            f"{{ return detail::load_le<{prim}>(p_ + {off_expr(base, f.offset)}); }}"
        )
        if is_enum:
            en = pascal(f.type_name)
            out.append(
                f"{indent}/// Validating accessor; returns nullopt on an undefined value."
            )
            out.append(
                f"{indent}[[nodiscard]] std::optional<{en}> {name}() const noexcept "
                f"{{ return {en}_from_raw({raw}()); }}"
            )


def emit_cpp(schema: Schema) -> str:
    o: list[str] = []
    for line in BANNER_LINES:
        o.append(f"// {line}" if line else "//")
    o.append("")
    o.append("#pragma once")
    o.append("")
    o.append("#include <bit>")
    o.append("#include <cstddef>")
    o.append("#include <cstdint>")
    o.append("#include <cstring>")
    o.append("#include <limits>")
    o.append("#include <optional>")
    o.append("")
    ns = schema.package.replace(".", "::")
    o.append(f"namespace {ns} {{")
    o.append("")
    o.append("static_assert(std::endian::native == std::endian::little,")
    o.append('              "This codec assumes a little-endian host. The wire format is '
             'little-endian; on a big-endian host every load_le would need a byteswap that '
             'has not been written or tested.");')
    o.append("")

    ph = schema.composites["packetHeader"]
    mh = schema.composites["messageHeader"]
    gse = schema.composites["groupSizeEncoding"]

    o.append(f"inline constexpr std::uint16_t kSchemaId = {schema.id};")
    o.append(f"inline constexpr std::uint16_t kSchemaVersion = {schema.version};")
    for k, v in schema.constants.items():
        o.append(f"inline constexpr std::int8_t k{pascal(k)} = {v};")
    o.append(f"inline constexpr std::size_t kPacketHeaderLen = {ph.length};")
    o.append(f"inline constexpr std::size_t kMessageHeaderLen = {mh.length};")
    o.append(f"inline constexpr std::size_t kGroupSizeEncodingLen = {gse.length};")
    o.append("inline constexpr std::uint8_t kPacketFlagSnapshot = 0x01;")
    o.append("")

    o.append("namespace detail {")
    o.append("")
    o.append("// Unaligned-safe. Messages are packed back to back inside a datagram, so a")
    o.append("// block can start at any byte offset; memcpy of a fixed size lowers to a")
    o.append("// single instruction and is the only well-defined way to do this in C++.")
    o.append("template <typename T>")
    o.append("[[nodiscard]] inline T load_le(const std::byte* p) noexcept {")
    o.append("    T v{};")
    o.append("    std::memcpy(&v, p, sizeof(T));")
    o.append("    return v;")
    o.append("}")
    o.append("")
    o.append("template <typename T>")
    o.append("inline void store_le(std::byte* p, T v) noexcept {")
    o.append("    std::memcpy(p, &v, sizeof(T));")
    o.append("}")
    o.append("")
    o.append("}  // namespace detail")
    o.append("")

    for e in schema.enums.values():
        prim = cpp_type(e.encoding, schema)
        o.append(f"enum class {pascal(e.name)} : {prim} {{")
        for vname, vval in e.values:
            o.append(f"    k{pascal(vname)} = {vval},")
        o.append("};")
        o.append("")
        o.append(
            f"[[nodiscard]] inline std::optional<{pascal(e.name)}> "
            f"{pascal(e.name)}_from_raw({prim} v) noexcept {{"
        )
        o.append("    switch (v) {")
        for vname, vval in e.values:
            o.append(f"        case {vval}: return {pascal(e.name)}::k{pascal(vname)};")
        o.append("        default: return std::nullopt;")
        o.append("    }")
        o.append("}")
        o.append("")

    o.append("namespace tmpl {")
    for m in schema.messages:
        o.append(f"inline constexpr std::uint16_t k{m.name} = {m.id};")
    o.append("}  // namespace tmpl")
    o.append("")

    # packet header
    o.append("/// Read-only view over the datagram header.")
    o.append("class PacketHeaderDecoder {")
    o.append("  public:")
    o.append(
        "    [[nodiscard]] static std::optional<PacketHeaderDecoder> "
        "wrap(const std::byte* p, std::size_t len) noexcept {"
    )
    o.append("        if (len < kPacketHeaderLen) return std::nullopt;")
    o.append("        PacketHeaderDecoder d(p);")
    o.append("        if (d.schema_id() != kSchemaId) return std::nullopt;")
    o.append("        return d;")
    o.append("    }")
    o.append("")
    o.append("    explicit PacketHeaderDecoder(const std::byte* p) noexcept : p_(p) {}")
    o.append("")
    cpp_accessors(o, ph.fields, schema, "0", "    ")
    o.append(
        "    [[nodiscard]] bool is_snapshot() const noexcept "
        "{ return (flags() & kPacketFlagSnapshot) != 0; }"
    )
    o.append("")
    o.append("  private:")
    o.append("    const std::byte* p_;")
    o.append("};")
    o.append("")
    o.append("/// Writes the datagram header, leaving messageCount at zero.")
    o.append("[[nodiscard]] inline std::optional<std::size_t> encode_packet_header(")
    o.append("    std::byte* buf, std::size_t cap")
    for f in ph.fields:
        if f.name in ("schemaId", "version", "messageCount"):
            continue
        o.append(f"    , {cpp_type(f.type_name, schema)} {snake(f.name)}")
    o.append(") noexcept {")
    o.append("    if (cap < kPacketHeaderLen) return std::nullopt;")
    o.append("    std::memset(buf, 0, kPacketHeaderLen);")
    for f in ph.fields:
        prim = cpp_type(f.type_name, schema)
        if f.name == "schemaId":
            o.append(f"    detail::store_le<{prim}>(buf + {f.offset}, kSchemaId);")
        elif f.name == "version":
            o.append(f"    detail::store_le<{prim}>(buf + {f.offset}, kSchemaVersion);")
        elif f.name == "messageCount":
            o.append(f"    detail::store_le<{prim}>(buf + {f.offset}, 0);")
        else:
            o.append(
                f"    detail::store_le<{prim}>(buf + {f.offset}, {snake(f.name)});"
            )
    o.append("    return kPacketHeaderLen;")
    o.append("}")
    o.append("")
    mc = next(f for f in ph.fields if f.name == "messageCount")
    o.append("inline bool patch_message_count(std::byte* buf, std::size_t cap,")
    o.append("                                std::uint16_t count) noexcept {")
    o.append("    if (cap < kPacketHeaderLen) return false;")
    o.append(f"    detail::store_le<std::uint16_t>(buf + {mc.offset}, count);")
    o.append("    return true;")
    o.append("}")
    o.append("")

    # message header
    o.append("/// Read-only view over the message header.")
    o.append("class MessageHeaderDecoder {")
    o.append("  public:")
    o.append(
        "    [[nodiscard]] static std::optional<MessageHeaderDecoder> "
        "wrap(const std::byte* p, std::size_t len) noexcept {"
    )
    o.append("        if (len < kMessageHeaderLen) return std::nullopt;")
    o.append("        return MessageHeaderDecoder(p);")
    o.append("    }")
    o.append("")
    o.append("    explicit MessageHeaderDecoder(const std::byte* p) noexcept : p_(p) {}")
    o.append("")
    cpp_accessors(o, mh.fields, schema, "0", "    ")
    o.append("")
    o.append("  private:")
    o.append("    const std::byte* p_;")
    o.append("};")
    o.append("")
    o.append("namespace detail {")
    o.append("inline void write_message_header(std::byte* buf, std::uint16_t block_length,")
    o.append("                                 std::uint16_t template_id) noexcept {")
    for f in mh.fields:
        src = {
            "blockLength": "block_length",
            "templateId": "template_id",
            "schemaId": "kSchemaId",
            "version": "kSchemaVersion",
        }[f.name]
        o.append(f"    store_le<std::uint16_t>(buf + {f.offset}, {src});")
    o.append("}")
    o.append("}  // namespace detail")
    o.append("")

    for m in schema.messages:
        emit_cpp_message(o, m, schema)

    o.append(f"}}  // namespace {ns}")
    return "\n".join(o).rstrip() + "\n"


def emit_cpp_message(o: list[str], m: Message, schema: Schema) -> None:
    o.append(f"// --- {m.name} " + "-" * max(0, 62 - len(m.name)))
    o.append("")
    o.append(f"/// {m.description}")
    o.append(f"class {m.name}Decoder {{")
    o.append("  public:")
    o.append(f"    static constexpr std::uint16_t kTemplateId = {m.id};")
    o.append(f"    static constexpr std::uint16_t kBlockLength = {m.block_length};")
    o.append("")
    o.append("    /// Wraps a buffer whose first byte is the message header. The root")
    o.append("    /// block length comes from the wire so a newer publisher that")
    o.append("    /// appended fields is skipped rather than misparsed.")
    o.append(
        f"    [[nodiscard]] static std::optional<{m.name}Decoder> "
        "wrap(const std::byte* p, std::size_t len) noexcept {"
    )
    o.append("        auto hdr = MessageHeaderDecoder::wrap(p, len);")
    o.append("        if (!hdr) return std::nullopt;")
    o.append("        if (hdr->template_id() != kTemplateId) return std::nullopt;")
    o.append("        const std::size_t root_len = hdr->block_length();")
    o.append("        if (root_len < kBlockLength) return std::nullopt;")
    o.append("        if (len < kMessageHeaderLen + root_len) return std::nullopt;")
    o.append(f"        {m.name}Decoder d(p, root_len);")
    if m.group is not None:
        o.append("        // total_len() reads the group header, so prove it is there first.")
        o.append(
            "        if (len < kMessageHeaderLen + root_len + kGroupSizeEncodingLen)"
        )
        o.append("            return std::nullopt;")
        o.append("        if (len < d.total_len()) return std::nullopt;")
    o.append("        return d;")
    o.append("    }")
    o.append("")
    o.append(
        f"    {m.name}Decoder(const std::byte* p, std::size_t root_len) noexcept"
    )
    o.append("        : p_(p), root_len_(root_len) {}")
    o.append("")
    cpp_accessors(o, m.fields, schema, "kMessageHeaderLen", "    ")
    o.append("")
    if m.group is None:
        o.append(
            "    [[nodiscard]] std::size_t total_len() const noexcept "
            "{ return kMessageHeaderLen + root_len_; }"
        )
        o.append("")
        o.append("  private:")
        o.append("    const std::byte* p_;")
        o.append("    std::size_t root_len_;")
        o.append("};")
        o.append("")
        emit_cpp_plain_encoder(o, m, schema)
    else:
        g = m.group
        entry = f"{m.name}{pascal(singular(g.name))}Decoder"
        o.append(f"    /// One entry of the `{g.name}` group.")
        o.append(f"    class {pascal(singular(g.name))} {{")
        o.append("      public:")
        o.append(f"        static constexpr std::uint16_t kBlockLength = {g.block_length};")
        o.append(f"        explicit {pascal(singular(g.name))}(const std::byte* p) noexcept : p_(p) {{}}")
        cpp_accessors(o, g.fields, schema, "0", "        ")
        o.append("")
        o.append("      private:")
        o.append("        const std::byte* p_;")
        o.append("    };")
        o.append("")
        o.append(
            f"    [[nodiscard]] std::uint16_t {snake(g.name)}_block_length() const noexcept {{"
        )
        o.append(
            "        return detail::load_le<std::uint16_t>(p_ + kMessageHeaderLen + root_len_);"
        )
        o.append("    }")
        o.append("")
        o.append(f"    [[nodiscard]] std::uint16_t {snake(g.name)}_count() const noexcept {{")
        o.append(
            "        return detail::load_le<std::uint16_t>(p_ + kMessageHeaderLen + root_len_ + 2);"
        )
        o.append("    }")
        o.append("")
        o.append(f"    /// Entry `i` of the `{g.name}` group. Caller checks `i` against the count.")
        o.append(
            f"    [[nodiscard]] {pascal(singular(g.name))} "
            f"{snake(singular(g.name))}(std::uint16_t i) const noexcept {{"
        )
        o.append("        const std::size_t base = kMessageHeaderLen + root_len_ +")
        o.append(
            f"                                 kGroupSizeEncodingLen + "
            f"static_cast<std::size_t>(i) * {snake(g.name)}_block_length();"
        )
        o.append(f"        return {pascal(singular(g.name))}(p_ + base);")
        o.append("    }")
        o.append("")
        o.append("    [[nodiscard]] std::size_t total_len() const noexcept {")
        o.append("        return kMessageHeaderLen + root_len_ + kGroupSizeEncodingLen +")
        o.append(
            f"               static_cast<std::size_t>({snake(g.name)}_count()) * "
            f"{snake(g.name)}_block_length();"
        )
        o.append("    }")
        o.append("")
        o.append("  private:")
        o.append("    const std::byte* p_;")
        o.append("    std::size_t root_len_;")
        o.append("};")
        o.append("")
        emit_cpp_group_encoder(o, m, schema)


def cpp_param_list(fields: list[Field], schema: Schema) -> list[tuple[str, str, Field]]:
    params = []
    for f in fields:
        if f.is_reserved:
            continue
        if f.type_name in schema.enums:
            params.append((snake(f.name), pascal(f.type_name), f))
        else:
            params.append((snake(f.name), cpp_type(f.type_name, schema), f))
    return params


def cpp_store(f: Field, schema: Schema, base: str, buf: str) -> str:
    prim = cpp_type(f.type_name, schema)
    name = snake(f.name)
    val = (
        f"static_cast<{prim}>({name})" if f.type_name in schema.enums else name
    )
    return f"detail::store_le<{prim}>({buf} + {off_expr(base, f.offset)}, {val});"


def emit_cpp_plain_encoder(o: list[str], m: Message, schema: Schema) -> None:
    params = cpp_param_list(m.fields, schema)
    o.append(f"/// Encodes a `{m.name}` at `buf[0]`, header included. Reserved bytes")
    o.append("/// are zeroed, which is what makes a re-encode byte-identical.")
    o.append(
        f"[[nodiscard]] inline std::optional<std::size_t> encode_{snake(m.name)}("
    )
    o.append("    std::byte* buf, std::size_t cap")
    for name, ty, _ in params:
        o.append(f"    , {ty} {name}")
    o.append(") noexcept {")
    o.append(
        f"    constexpr std::size_t kLen = kMessageHeaderLen + {m.block_length};"
    )
    o.append("    if (cap < kLen) return std::nullopt;")
    o.append("    std::memset(buf, 0, kLen);")
    o.append(
        f"    detail::write_message_header(buf, {m.block_length}, tmpl::k{m.name});"
    )
    for f in m.fields:
        if f.is_reserved:
            continue
        o.append("    " + cpp_store(f, schema, "kMessageHeaderLen", "buf"))
    o.append("    return kLen;")
    o.append("}")
    o.append("")


def emit_cpp_group_encoder(o: list[str], m: Message, schema: Schema) -> None:
    g = m.group
    assert g is not None
    root_params = cpp_param_list(m.fields, schema)
    entry_params = cpp_param_list(g.fields, schema)
    o.append(f"/// Two-phase encoder for `{m.name}`, which carries a repeating group.")
    o.append(f"class {m.name}Encoder {{")
    o.append("  public:")
    o.append(f"    [[nodiscard]] static std::optional<{m.name}Encoder> start(")
    o.append("        std::byte* buf, std::size_t cap")
    for name, ty, _ in root_params:
        o.append(f"        , {ty} {name}")
    o.append("    ) noexcept {")
    o.append(
        f"        constexpr std::size_t kHead = kMessageHeaderLen + {m.block_length} + "
        "kGroupSizeEncodingLen;"
    )
    o.append("        if (cap < kHead) return std::nullopt;")
    o.append("        std::memset(buf, 0, kHead);")
    o.append(
        f"        detail::write_message_header(buf, {m.block_length}, tmpl::k{m.name});"
    )
    for f in m.fields:
        if f.is_reserved:
            continue
        o.append("        " + cpp_store(f, schema, "kMessageHeaderLen", "buf"))
    o.append(
        f"        detail::store_le<std::uint16_t>(buf + kMessageHeaderLen + "
        f"{m.block_length}, {g.block_length});"
    )
    o.append(f"        return {m.name}Encoder(buf, cap, kHead);")
    o.append("    }")
    o.append("")
    o.append(f"    /// Appends one `{g.name}` entry.")
    o.append(f"    [[nodiscard]] bool push_{snake(singular(g.name))}(")
    first = True
    for name, ty, _ in entry_params:
        prefix = "        " if first else "        , "
        o.append(f"{prefix}{ty} {name}")
        first = False
    o.append("    ) noexcept {")
    o.append(f"        constexpr std::size_t kEntry = {g.block_length};")
    o.append("        if (pos_ + kEntry > cap_) return false;")
    o.append("        if (count_ == std::numeric_limits<std::uint16_t>::max()) return false;")
    o.append("        std::byte* e = buf_ + pos_;")
    o.append("        std::memset(e, 0, kEntry);")
    for f in g.fields:
        if f.is_reserved:
            continue
        o.append("        " + cpp_store(f, schema, "0", "e"))
    o.append("        pos_ += kEntry;")
    o.append("        ++count_;")
    o.append("        return true;")
    o.append("    }")
    o.append("")
    o.append("    /// Patches the group count and returns the total bytes written.")
    o.append("    [[nodiscard]] std::size_t finish() noexcept {")
    o.append(
        f"        detail::store_le<std::uint16_t>(buf_ + kMessageHeaderLen + "
        f"{m.block_length} + 2, count_);"
    )
    o.append("        return pos_;")
    o.append("    }")
    o.append("")
    o.append("  private:")
    o.append(
        f"    {m.name}Encoder(std::byte* buf, std::size_t cap, std::size_t pos) noexcept"
    )
    o.append("        : buf_(buf), cap_(cap), pos_(pos) {}")
    o.append("")
    o.append("    std::byte* buf_;")
    o.append("    std::size_t cap_;")
    o.append("    std::size_t pos_;")
    o.append("    std::uint16_t count_ = 0;")
    o.append("};")
    o.append("")


# ---------------------------------------------------------------------------
# driver
# ---------------------------------------------------------------------------


def rustfmt(path: Path) -> None:
    exe = shutil.which("rustfmt")
    if exe is None:
        print("  note: rustfmt not found; generated Rust left unformatted", file=sys.stderr)
        return
    subprocess.run([exe, "--edition", "2021", str(path)], check=True)


def write_if_changed(path: Path, text: str, check: bool) -> bool:
    """Returns True when the file on disk already matched."""
    current = path.read_text(encoding="utf-8") if path.exists() else None
    if check:
        if current == text:
            print(f"  ok    {path.relative_to(REPO)}")
            return True
        print(f"  STALE {path.relative_to(REPO)}", file=sys.stderr)
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")
    print(f"  wrote {path.relative_to(REPO)}")
    return current == text


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit non-zero if a generated file is stale",
    )
    args = ap.parse_args()

    schema = parse_schema()
    print(
        f"schema {schema.package} id={schema.id} version={schema.version} "
        f"-- {len(schema.messages)} messages"
    )

    rust_text = emit_rust(schema)
    cpp_text = emit_cpp(schema)

    if args.check:
        # rustfmt is part of the output, so format a scratch copy before comparing.
        scratch = RUST_OUT.parent / ".generated.check.rs"
        scratch.write_text(rust_text, encoding="utf-8", newline="\n")
        try:
            rustfmt(scratch)
            rust_text = scratch.read_text(encoding="utf-8")
        finally:
            scratch.unlink(missing_ok=True)
        ok = write_if_changed(RUST_OUT, rust_text, True)
        ok = write_if_changed(CPP_OUT, cpp_text, True) and ok
        if not ok:
            print(
                "\ncodegen is stale: run `make codegen` and commit the result",
                file=sys.stderr,
            )
            return 1
        return 0

    write_if_changed(RUST_OUT, rust_text, False)
    rustfmt(RUST_OUT)
    write_if_changed(CPP_OUT, cpp_text, False)
    return 0


if __name__ == "__main__":
    sys.exit(main())
