#!/usr/bin/env python3
"""Build the golden byte vectors and the assertion code both test suites run.

    python3 schema/goldens.py            # write vectors and generated tests
    python3 schema/goldens.py --check    # fail if anything on disk is stale

Why this file does not import codegen.py
----------------------------------------
The whole point of a golden vector is to be an *independent* statement of what
the bytes are. If these files were produced by the Rust encoder, a wrong offset
in the generator would produce a wrong vector that the generated decoder would
then happily agree with, and the test would pass while the wire format was
broken. Cross-language wire drift fails exactly this way: silently, as a
corrupted field under load rather than as a compile error.

So the layout is written out here a third time, by hand, as explicit
`struct.pack` format strings taken from the table in docs/WIRE.md -- once in the
Rust emitter, once in the C++ emitter, once here. Three independent transcriptions
of the same table have to agree before a test can pass.

And to anchor those three against the specification itself, every message type
has one fully hand-typed hex literal below, checked against its packer at build
time. The values in those vectors were chosen to be readable in hex so a human
can verify the dump in schema/golden/*.txt against the spec table by eye.
Composite vectors (batches) are assembled from packers that have already been
anchored that way.
"""

from __future__ import annotations

import argparse
import shutil
import struct
import subprocess
import sys
from dataclasses import dataclass, field as dc_field
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
GOLDEN_DIR = REPO / "schema" / "golden"
RUST_OUT = REPO / "crates" / "wire" / "tests" / "golden_generated" / "mod.rs"
CPP_OUT = REPO / "cpp" / "wire" / "tests" / "golden_generated.hpp"

SCHEMA_ID = 1
SCHEMA_VERSION = 1

BANNER = [
    "@generated by schema/goldens.py -- do not edit.",
    "",
    "Both test suites assert these same field values against the same",
    "schema/golden/*.bin files, then re-encode and require the bytes back.",
]

# ---------------------------------------------------------------------------
# the layout, transcribed by hand from docs/WIRE.md
# ---------------------------------------------------------------------------

FMT_PACKET_HEADER = "<HHHBBQQ"   # schemaId version messageCount channel flags firstSeq sendTs
FMT_MESSAGE_HEADER = "<HHHH"     # blockLength templateId schemaId version
FMT_GROUP_HEADER = "<HH"         # blockLength numInGroup

FMT_ADD_ORDER = "<QqIHBB"        # orderId price quantity symbolId side reserved
FMT_MODIFY_ORDER = "<QqIHBB"     # orderId newPrice newQuantity symbolId side reason
FMT_DELETE_ORDER = "<QHBB"       # orderId symbolId side reserved
FMT_TRADE = "<QQQqIHBB"          # tradeId aggressorOrderId restingOrderId price qty symbolId side reserved
FMT_SNAPSHOT = "<QHBB"           # lastSequence symbolId flags reserved
FMT_SNAPSHOT_ORDER = "<QqIBBH"   # orderId price quantity side reserved reserved2
FMT_HEARTBEAT = "<Q"             # lastSequence
FMT_SEQUENCE_RESET = "<Q"        # newSequence

TEMPLATE = {
    "AddOrder": 1,
    "ModifyOrder": 2,
    "DeleteOrder": 3,
    "Trade": 4,
    "Snapshot": 5,
    "Heartbeat": 6,
    "SequenceReset": 7,
}

BLOCK_LENGTH = {
    "AddOrder": 24,
    "ModifyOrder": 24,
    "DeleteOrder": 12,
    "Trade": 40,
    "Snapshot": 12,
    "Heartbeat": 8,
    "SequenceReset": 8,
}

ORDER_BLOCK_LENGTH = 24

BID, ASK = 0, 1
REDUCE, REPLACE = 0, 1


def msg_header(name: str) -> bytes:
    return struct.pack(
        FMT_MESSAGE_HEADER, BLOCK_LENGTH[name], TEMPLATE[name], SCHEMA_ID, SCHEMA_VERSION
    )


# ---------------------------------------------------------------------------
# message model
# ---------------------------------------------------------------------------


@dataclass
class Msg:
    """One message: its wire bytes plus the field values both suites assert."""

    kind: str
    fields: dict[str, object]
    orders: list[dict[str, object]] = dc_field(default_factory=list)

    def pack(self) -> bytes:
        f = self.fields
        h = msg_header(self.kind)
        if self.kind == "AddOrder":
            return h + struct.pack(
                FMT_ADD_ORDER,
                f["order_id"], f["price"], f["quantity"], f["symbol_id"], f["side"], 0,
            )
        if self.kind == "ModifyOrder":
            return h + struct.pack(
                FMT_MODIFY_ORDER,
                f["order_id"], f["new_price"], f["new_quantity"], f["symbol_id"],
                f["side"], f["reason"],
            )
        if self.kind == "DeleteOrder":
            return h + struct.pack(
                FMT_DELETE_ORDER, f["order_id"], f["symbol_id"], f["side"], 0
            )
        if self.kind == "Trade":
            return h + struct.pack(
                FMT_TRADE,
                f["trade_id"], f["aggressor_order_id"], f["resting_order_id"],
                f["price"], f["quantity"], f["symbol_id"], f["aggressor_side"], 0,
            )
        if self.kind == "Heartbeat":
            return h + struct.pack(FMT_HEARTBEAT, f["last_sequence"])
        if self.kind == "SequenceReset":
            return h + struct.pack(FMT_SEQUENCE_RESET, f["new_sequence"])
        if self.kind == "Snapshot":
            body = struct.pack(
                FMT_SNAPSHOT, f["last_sequence"], f["symbol_id"], f["flags"], 0
            )
            group = struct.pack(FMT_GROUP_HEADER, ORDER_BLOCK_LENGTH, len(self.orders))
            for o in self.orders:
                group += struct.pack(
                    FMT_SNAPSHOT_ORDER,
                    o["order_id"], o["price"], o["quantity"], o["side"], 0, 0,
                )
            return h + body + group
        raise AssertionError(f"unhandled message kind {self.kind}")


@dataclass
class Vector:
    name: str
    why: str
    channel: int
    flags: int
    first_sequence: int
    send_timestamp_ns: int
    messages: list[Msg]

    def pack(self) -> bytes:
        body = b"".join(m.pack() for m in self.messages)
        head = struct.pack(
            FMT_PACKET_HEADER,
            SCHEMA_ID, SCHEMA_VERSION, len(self.messages),
            self.channel, self.flags, self.first_sequence, self.send_timestamp_ns,
        )
        return head + body


# ---------------------------------------------------------------------------
# hand-typed anchors
#
# One per message type. Written from the byte table in docs/WIRE.md, not from
# any encoder. If a packer above disagrees with one of these, the build stops.
# ---------------------------------------------------------------------------

HAND_TYPED: dict[str, str] = {
    # packetHeader: schemaId=1 version=1 count=1 channel=0 flags=0
    #               firstSequence=0x0000000000100000
    #               sendTimestampNs=0x17A0010203040506
    # messageHeader: blockLength=24(0x18) templateId=1 schemaId=1 version=1
    # AddOrder: orderId=0x0000000100000002 price=1012500(0x0F7314)
    #           quantity=250(0xFA) symbolId=7 side=Bid(0) reserved=0
    "add_order":
        "0100 0100 0100 00 00 0000100000000000 060504030201a017"
        "1800 0100 0100 0100"
        "0200000001000000 14730f0000000000 fa000000 0700 00 00",

    # ModifyOrder: blockLength=24 templateId=2
    #              orderId=0x0000000100000002 newPrice=1012600(0x0F7378)
    #              newQuantity=100(0x64) symbolId=7 side=Bid(0) reason=Replace(1)
    "modify_order":
        "0100 0100 0100 01 00 0100100000000000 060504030201a017"
        "1800 0200 0100 0100"
        "0200000001000000 78730f0000000000 64000000 0700 00 01",

    # DeleteOrder: blockLength=12(0x0C) templateId=3
    #              orderId=0x0000000100000002 symbolId=7 side=Ask(1) reserved=0
    "delete_order":
        "0100 0100 0100 00 00 0200100000000000 060504030201a017"
        "0c00 0300 0100 0100"
        "0200000001000000 0700 01 00",

    # Trade: blockLength=40(0x28) templateId=4
    #        tradeId=0x0000000000000011 aggressor=0x0000000100000002
    #        resting=0x0000000100000003 price=1012500 quantity=50(0x32)
    #        symbolId=7 aggressorSide=Ask(1) reserved=0
    "trade":
        "0100 0100 0100 00 00 0300100000000000 060504030201a017"
        "2800 0400 0100 0100"
        "1100000000000000 0200000001000000 0300000001000000"
        "14730f0000000000 32000000 0700 01 00",

    # Heartbeat: blockLength=8 templateId=6 lastSequence=0x0000000000100004
    "heartbeat":
        "0100 0100 0100 01 00 0400100000000000 060504030201a017"
        "0800 0600 0100 0100"
        "0400100000000000",

    # SequenceReset: blockLength=8 templateId=7 newSequence=0x0000000000200000
    "sequence_reset":
        "0100 0100 0100 00 00 0500100000000000 060504030201a017"
        "0800 0700 0100 0100"
        "0000200000000000",

    # Snapshot with two ORDERS. packetHeader.flags=1 marks the snapshot cycle,
    # and Snapshot.flags=1 marks this as the last fragment for the symbol.
    #   root: blockLength=12 templateId=5
    #         lastSequence=0x0000000000100000 symbolId=7 flags=1 reserved=0
    #   group header: blockLength=24(0x18) numInGroup=2
    #   order 0: orderId=0x0000000100000002 price=1012500 quantity=250(0xFA)
    #            side=Bid(0)
    #   order 1: orderId=0x0000000100000003 price=1012600 quantity=100(0x64)
    #            side=Ask(1)
    "snapshot_two_orders":
        "0100 0100 0100 00 01 0600100000000000 060504030201a017"
        "0c00 0500 0100 0100"
        "0000100000000000 0700 01 00"
        "1800 0200"
        "0200000001000000 14730f0000000000 fa000000 00 00 0000"
        "0300000001000000 78730f0000000000 64000000 01 00 0000",
}


def hexbytes(s: str) -> bytes:
    return bytes.fromhex(s.replace(" ", "").replace("\n", ""))


# ---------------------------------------------------------------------------
# the vectors
# ---------------------------------------------------------------------------

TS = 0x17A0010203040506
BASE = 0x0000000000100000


def vectors() -> list[Vector]:
    return [
        Vector(
            name="add_order",
            why="One AddOrder. Anchors the AddOrder block and the packet header.",
            channel=0, flags=0, first_sequence=BASE, send_timestamp_ns=TS,
            messages=[Msg("AddOrder", {
                "order_id": 0x0000000100000002, "price": 1_012_500,
                "quantity": 250, "symbol_id": 7, "side": BID,
            })],
        ),
        Vector(
            name="modify_order",
            why="A Replace, which loses queue priority. channel=1 exercises the B arm.",
            channel=1, flags=0, first_sequence=BASE + 1, send_timestamp_ns=TS,
            messages=[Msg("ModifyOrder", {
                "order_id": 0x0000000100000002, "new_price": 1_012_600,
                "new_quantity": 100, "symbol_id": 7, "side": BID, "reason": REPLACE,
            })],
        ),
        Vector(
            name="delete_order",
            why="The shortest message: a 12-byte block that leaves the next message 4-byte aligned.",
            channel=0, flags=0, first_sequence=BASE + 2, send_timestamp_ns=TS,
            messages=[Msg("DeleteOrder", {
                "order_id": 0x0000000100000002, "symbol_id": 7, "side": ASK,
            })],
        ),
        Vector(
            name="trade",
            why="The longest fixed block, and the only message naming two orders.",
            channel=0, flags=0, first_sequence=BASE + 3, send_timestamp_ns=TS,
            messages=[Msg("Trade", {
                "trade_id": 0x11, "aggressor_order_id": 0x0000000100000002,
                "resting_order_id": 0x0000000100000003, "price": 1_012_500,
                "quantity": 50, "symbol_id": 7, "aggressor_side": ASK,
            })],
        ),
        Vector(
            name="heartbeat",
            why="Idle-channel keepalive; the handler uses it to tell quiet from dead.",
            channel=1, flags=0, first_sequence=BASE + 4, send_timestamp_ns=TS,
            messages=[Msg("Heartbeat", {"last_sequence": BASE + 4})],
        ),
        Vector(
            name="sequence_reset",
            why="The publisher restarts its numbering.",
            channel=0, flags=0, first_sequence=BASE + 5, send_timestamp_ns=TS,
            messages=[Msg("SequenceReset", {"new_sequence": 0x0000000000200000})],
        ),
        Vector(
            name="snapshot_two_orders",
            why=(
                "The repeating group, the snapshot flag on the packet header, and the "
                "last-fragment flag on the message. Orders are listed in queue order: a "
                "consumer that re-adds them in this order reproduces price-time priority "
                "exactly, which an aggregated snapshot could never do."
            ),
            channel=0, flags=1, first_sequence=BASE + 6, send_timestamp_ns=TS,
            messages=[Msg("Snapshot", {
                "last_sequence": BASE, "symbol_id": 7, "flags": 1,
            }, orders=[
                {"order_id": 0x0000000100000002, "price": 1_012_500, "quantity": 250, "side": BID},
                {"order_id": 0x0000000100000003, "price": 1_012_600, "quantity": 100, "side": ASK},
            ])],
        ),
        Vector(
            name="snapshot_empty_group",
            why=(
                "A snapshot of an empty book. numInGroup=0 must still carry the group "
                "header, or total_len walks the reader into the next message."
            ),
            channel=0, flags=1, first_sequence=BASE + 7, send_timestamp_ns=TS,
            messages=[Msg("Snapshot", {
                "last_sequence": BASE + 7, "symbol_id": 9, "flags": 1,
            }, orders=[])],
        ),
        Vector(
            name="batch_mixed",
            why=(
                "Six messages of five types behind one header, including a "
                "variable-length snapshot in the middle. This is the vector that "
                "proves a decoder can walk a batch: get any total_len wrong and "
                "every message after it is garbage. Batching is not an optimisation "
                "here, it is the framing the throughput target depends on."
            ),
            channel=0, flags=0, first_sequence=0x00000000FFFFFFFE, send_timestamp_ns=TS,
            messages=[
                Msg("AddOrder", {
                    "order_id": 0x0000000200000001, "price": 990_000,
                    "quantity": 1000, "symbol_id": 3, "side": BID,
                }),
                Msg("DeleteOrder", {
                    "order_id": 0x0000000200000002, "symbol_id": 3, "side": ASK,
                }),
                Msg("Snapshot", {
                    "last_sequence": 0x00000000FFFFFFFF, "symbol_id": 3, "flags": 0,
                }, orders=[
                    {"order_id": 0x0000000200000001, "price": 990_000, "quantity": 1000, "side": BID},
                    {"order_id": 0x0000000200000004, "price": 990_100, "quantity": 400, "side": ASK},
                    {"order_id": 0x0000000200000005, "price": 990_200, "quantity": 700, "side": ASK},
                ]),
                Msg("Trade", {
                    "trade_id": 0x2A, "aggressor_order_id": 0x0000000200000003,
                    "resting_order_id": 0x0000000200000001, "price": 990_000,
                    "quantity": 400, "symbol_id": 3, "aggressor_side": ASK,
                }),
                Msg("ModifyOrder", {
                    "order_id": 0x0000000200000001, "new_price": 990_000,
                    "new_quantity": 600, "symbol_id": 3, "side": BID, "reason": REDUCE,
                }),
                Msg("Heartbeat", {"last_sequence": 0x0000000100000003}),
            ],
        ),
        Vector(
            name="negative_price",
            why=(
                "Prices are signed on the wire. Spreads, settlement marks and a few "
                "real contracts go below zero, and a decoder that reads the field as "
                "unsigned looks correct until the day one does."
            ),
            channel=0, flags=0, first_sequence=BASE + 16, send_timestamp_ns=TS,
            messages=[Msg("AddOrder", {
                "order_id": 0x0000000300000001, "price": -12_500,
                "quantity": 5, "symbol_id": 11, "side": ASK,
            })],
        ),
        Vector(
            name="sequence_wrap_high",
            why=(
                "firstSequence near 2^64. The sequence of message i is firstSequence+i, "
                "so a reader that widens through i32 or i64 breaks here and nowhere else."
            ),
            channel=1, flags=0,
            first_sequence=0xFFFFFFFFFFFFFFFD, send_timestamp_ns=TS,
            messages=[
                Msg("Heartbeat", {"last_sequence": 0xFFFFFFFFFFFFFFFD}),
                Msg("Heartbeat", {"last_sequence": 0xFFFFFFFFFFFFFFFE}),
            ],
        ),
    ]


# ---------------------------------------------------------------------------
# annotated dump
# ---------------------------------------------------------------------------


def annotate(v: Vector) -> str:
    out: list[str] = []
    out.append(f"{v.name}.bin")
    out.append("=" * (len(v.name) + 4))
    out.append("")
    out.append(v.why)
    out.append("")
    out.append("Generated by schema/goldens.py. This dump exists so the vector can be")
    out.append("checked against the byte table in docs/WIRE.md by eye rather than by")
    out.append("running the code that is supposed to be under test.")
    out.append("")

    data = v.pack()
    pos = 0

    def row(n: int, label: str) -> None:
        nonlocal pos
        chunk = data[pos : pos + n]
        out.append(f"  {pos:04x}  {chunk.hex(' '):<48}  {label}")
        pos += n

    out.append("packetHeader")
    row(2, f"schemaId = {SCHEMA_ID}")
    row(2, f"version = {SCHEMA_VERSION}")
    row(2, f"messageCount = {len(v.messages)}")
    row(1, f"channel = {v.channel}")
    row(1, f"flags = 0x{v.flags:02x}")
    row(8, f"firstSequence = {v.first_sequence} (0x{v.first_sequence:016x})")
    row(8, f"sendTimestampNs = {v.send_timestamp_ns} (0x{v.send_timestamp_ns:016x})")

    for i, m in enumerate(v.messages):
        out.append("")
        out.append(f"message {i}  sequence = {v.first_sequence + i}  {m.kind}")
        row(2, f"blockLength = {BLOCK_LENGTH[m.kind]}")
        row(2, f"templateId = {TEMPLATE[m.kind]}")
        row(2, f"schemaId = {SCHEMA_ID}")
        row(2, f"version = {SCHEMA_VERSION}")
        for fname, fval in m.fields.items():
            width = FIELD_WIDTH[m.kind][fname]
            row(width, f"{fname} = {fval}{signed_note(fval)}")
        if m.kind == "Snapshot":
            row(1, "reserved = 0")
            row(2, f"orders.blockLength = {ORDER_BLOCK_LENGTH}")
            row(2, f"orders.numInGroup = {len(m.orders)}")
            for j, lv in enumerate(m.orders):
                for fname, fval in lv.items():
                    width = ORDER_FIELD_WIDTH[fname]
                    row(width, f"orders[{j}].{fname} = {fval}")
                row(1, f"orders[{j}].reserved = 0")
                row(2, f"orders[{j}].reserved2 = 0")
        elif m.kind in ("AddOrder", "DeleteOrder", "Trade"):
            row(1, "reserved = 0")

    if pos != len(data):
        raise AssertionError(
            f"{v.name}: annotated {pos} bytes but the vector is {len(data)}. "
            "The dump and the packer disagree about the layout."
        )
    out.append("")
    out.append(f"total {len(data)} bytes")
    out.append("")
    return "\n".join(out)


def signed_note(v: object) -> str:
    return " (negative)" if isinstance(v, int) and v < 0 else ""


FIELD_WIDTH = {
    "AddOrder": {"order_id": 8, "price": 8, "quantity": 4, "symbol_id": 2, "side": 1},
    "ModifyOrder": {
        "order_id": 8, "new_price": 8, "new_quantity": 4, "symbol_id": 2,
        "side": 1, "reason": 1,
    },
    "DeleteOrder": {"order_id": 8, "symbol_id": 2, "side": 1},
    "Trade": {
        "trade_id": 8, "aggressor_order_id": 8, "resting_order_id": 8, "price": 8,
        "quantity": 4, "symbol_id": 2, "aggressor_side": 1,
    },
    "Snapshot": {"last_sequence": 8, "symbol_id": 2, "flags": 1},
    "Heartbeat": {"last_sequence": 8},
    "SequenceReset": {"new_sequence": 8},
}

ORDER_FIELD_WIDTH = {"order_id": 8, "price": 8, "quantity": 4, "side": 1}

# Snapshot's reserved byte sits between the root fields and the group header, so
# annotate() emits it there rather than at the end of the message.


# ---------------------------------------------------------------------------
# Rust emitter
# ---------------------------------------------------------------------------

RUST_SIDE = {BID: "Side::Bid", ASK: "Side::Ask"}
RUST_REASON = {REDUCE: "ModifyReason::Reduce", REPLACE: "ModifyReason::Replace"}

CPP_SIDE = {BID: "Side::kBid", ASK: "Side::kAsk"}
CPP_REASON = {REDUCE: "ModifyReason::kReduce", REPLACE: "ModifyReason::kReplace"}

# Which fields are enums, so the emitters compare against the enum rather than raw.
ENUM_FIELDS = {"side", "aggressor_side", "reason"}

RUST_SUFFIX = {
    "order_id": "u64", "price": "i64", "quantity": "u32", "symbol_id": "u16",
    "new_price": "i64", "new_quantity": "u32", "trade_id": "u64",
    "aggressor_order_id": "u64", "resting_order_id": "u64",
    "last_sequence": "u64", "new_sequence": "u64", "flags": "u8",
}


def rust_lit(name: str, value: object) -> str:
    suffix = RUST_SUFFIX.get(name, "")
    return f"{value}{suffix}"


def emit_rust(vs: list[Vector]) -> str:
    o: list[str] = []
    for line in BANNER:
        o.append(f"//! {line}" if line else "//!")
    o.append("")
    o.append("#![allow(clippy::unreadable_literal)]")
    o.append("")
    o.append("use wire::*;")
    o.append("")
    o.append("// Comparison helpers. Each names the field, because a golden-vector")
    o.append("// failure that says only \"mismatch\" costs more time than the test saved.")
    o.append("macro_rules! eq_fn {")
    o.append("    ($name:ident, $ty:ty) => {")
    o.append("        #[allow(dead_code)]")
    o.append("        fn $name(label: &str, actual: $ty, expected: $ty) -> Result<(), String> {")
    o.append("            if actual != expected {")
    o.append("                return Err(format!(\"{label}: expected {expected}, got {actual}\"));")
    o.append("            }")
    o.append("            Ok(())")
    o.append("        }")
    o.append("    };")
    o.append("}")
    o.append("")
    o.append("eq_fn!(eq_u8, u8);")
    o.append("eq_fn!(eq_u16, u16);")
    o.append("eq_fn!(eq_u32, u32);")
    o.append("eq_fn!(eq_u64, u64);")
    o.append("eq_fn!(eq_i64, i64);")
    o.append("eq_fn!(eq_bool, bool);")
    o.append("")
    o.append("/// One golden vector: the file, the field values, and the encoder path")
    o.append("/// that must reproduce the file byte for byte.")
    o.append("pub struct Vector {")
    o.append("    pub name: &'static str,")
    o.append("    pub file: &'static str,")
    o.append("    pub why: &'static str,")
    o.append("    pub check: fn(&[u8]) -> Result<(), String>,")
    o.append("    pub build: fn(&mut [u8]) -> Result<usize, WireError>,")
    o.append("}")
    o.append("")
    o.append("pub const VECTORS: &[Vector] = &[")
    for v in vs:
        o.append("    Vector {")
        o.append(f'        name: "{v.name}",')
        o.append(f'        file: "{v.name}.bin",')
        o.append(f'        why: "{v.why}",')
        o.append(f"        check: check_{v.name},")
        o.append(f"        build: build_{v.name},")
        o.append("    },")
    o.append("];")
    o.append("")
    for v in vs:
        emit_rust_check(o, v)
        emit_rust_build(o, v)
    return "\n".join(o).rstrip() + "\n"


def emit_rust_check(o: list[str], v: Vector) -> None:
    o.append(f"/// {v.why}")
    o.append(f"pub fn check_{v.name}(buf: &[u8]) -> Result<(), String> {{")
    o.append("    let r = PacketReader::new(buf).map_err(|e| format!(\"packet header: {e}\"))?;")
    o.append("    let h = r.header();")
    o.append(f"    eq_u16(\"packet.schemaId\", h.schema_id(), {SCHEMA_ID})?;")
    o.append(f"    eq_u16(\"packet.version\", h.version(), {SCHEMA_VERSION})?;")
    o.append(
        f'    eq_u16("packet.messageCount", h.message_count(), {len(v.messages)})?;'
    )
    o.append(f'    eq_u8("packet.channel", h.channel(), {v.channel})?;')
    o.append(f'    eq_u8("packet.flags", h.flags(), {v.flags})?;')
    o.append(
        f'    eq_u64("packet.firstSequence", h.first_sequence(), {v.first_sequence})?;'
    )
    o.append(
        f'    eq_u64("packet.sendTimestampNs", h.send_timestamp_ns(), '
        f"{v.send_timestamp_ns})?;"
    )
    snap = "true" if v.flags & 1 else "false"
    o.append(f'    eq_bool("packet.isSnapshot", h.is_snapshot(), {snap})?;')
    o.append("")
    o.append("    let mut it = r.messages();")
    for i, m in enumerate(v.messages):
        seq = (v.first_sequence + i) & 0xFFFFFFFFFFFFFFFF
        o.append(f"    // message {i}")
        o.append("    let (seq, msg) = it")
        o.append("        .next()")
        o.append(f'        .ok_or_else(|| "message {i}: missing".to_string())?')
        o.append(f'        .map_err(|e| format!("message {i}: {{e}}"))?;')
        o.append(f'    eq_u64("message {i} sequence", seq, {seq})?;')
        o.append(f"    let Message::{m.kind}(d) = msg else {{")
        o.append(
            f'        return Err(format!("message {i}: expected {m.kind}, got template {{}}", msg.template_id()));'
        )
        o.append("    };")
        for fname, fval in m.fields.items():
            emit_rust_field_check(o, f"message {i}.{fname}", "d", fname, fval, m.kind)
        if m.kind == "Snapshot":
            o.append(
                f'    eq_u16("message {i}.orders.numInGroup", d.orders_count(), {len(m.orders)})?;'
            )
            o.append(
                f'    eq_u16("message {i}.orders.blockLength", d.orders_block_length(), {ORDER_BLOCK_LENGTH})?;'
            )
            o.append("    let mut lv = d.orders();")
            for j, lvl in enumerate(m.orders):
                o.append(
                    f'    let l = lv.next().ok_or_else(|| "message {i}: level {j} missing".to_string())?;'
                )
                for fname, fval in lvl.items():
                    emit_rust_field_check(
                        o, f"message {i}.orders[{j}].{fname}", "l", fname, fval, "level"
                    )
            o.append(
                f'    if lv.next().is_some() {{ return Err("message {i}: extra levels".to_string()); }}'
            )
        o.append("")
    o.append('    if it.next().is_some() {')
    o.append('        return Err("extra messages past messageCount".to_string());')
    o.append("    }")
    o.append("    Ok(())")
    o.append("}")
    o.append("")


def emit_rust_field_check(
    o: list[str], label: str, var: str, fname: str, fval: object, kind: str
) -> None:
    if fname in ENUM_FIELDS:
        table = RUST_REASON if fname == "reason" else RUST_SIDE
        ty = "ModifyReason" if fname == "reason" else "Side"
        o.append(
            f'    if {var}.{fname}().map_err(|e| format!("{label}: {{e}}"))? != {table[fval]} {{'
        )
        o.append(
            f'        return Err(format!("{label}: expected {table[fval]}, got {{:?}}", {var}.{fname}()));'
        )
        o.append("    }")
        return
    width = {
        8: "eq_u64", 4: "eq_u32", 2: "eq_u16", 1: "eq_u8",
    }
    if kind == "level":
        w = ORDER_FIELD_WIDTH[fname]
    else:
        w = FIELD_WIDTH[kind][fname]
    if fname in ("price", "new_price"):
        o.append(f'    eq_i64("{label}", {var}.{fname}(), {fval})?;')
        return
    o.append(f'    {width[w]}("{label}", {var}.{fname}(), {rust_lit(fname, fval)})?;')


def emit_rust_build(o: list[str], v: Vector) -> None:
    o.append(f"/// Re-encodes `{v.name}` from the same values `check_{v.name}` asserts.")
    o.append(f"pub fn build_{v.name}(out: &mut [u8]) -> Result<usize, WireError> {{")
    o.append("    let mut w = PacketWriter::new(")
    o.append("        out,")
    o.append(f"        {v.channel},")
    o.append(f"        {v.flags},")
    o.append(f"        {v.first_sequence},")
    o.append(f"        {v.send_timestamp_ns},")
    o.append("    )?;")
    for m in v.messages:
        if m.kind == "Snapshot":
            f = m.fields
            o.append("    let n = {")
            # A group with no entries never mutates the encoder, and clippy
            # rejects an unnecessary `mut` under -D warnings.
            binding = "let mut e" if m.orders else "let e"
            o.append(f"        {binding} = SnapshotEncoder::start(")
            o.append("            w.tail(),")
            o.append(f"            {f['last_sequence']},")
            o.append(f"            {f['symbol_id']},")
            o.append(f"            {f['flags']},")
            o.append("        )?;")
            for lv in m.orders:
                o.append("        e.push_order(")
                o.append(f"            {lv['order_id']},")
                o.append(f"            {lv['price']},")
                o.append(f"            {lv['quantity']},")
                o.append(f"            {RUST_SIDE[lv['side']]},")
                o.append("        )?;")
            o.append("        e.finish()")
            o.append("    };")
            o.append("    w.commit(n)?;")
            continue
        args = []
        for fname, fval in m.fields.items():
            if fname in ENUM_FIELDS:
                table = RUST_REASON if fname == "reason" else RUST_SIDE
                args.append(table[fval])
            else:
                args.append(str(fval))
        method = {
            "AddOrder": "add_order", "ModifyOrder": "modify_order",
            "DeleteOrder": "delete_order", "Trade": "trade",
            "Heartbeat": "heartbeat", "SequenceReset": "sequence_reset",
        }[m.kind]
        o.append(f"    w.{method}({', '.join(args)})?;")
    o.append("    Ok(w.finish())")
    o.append("}")
    o.append("")


# ---------------------------------------------------------------------------
# C++ emitter
# ---------------------------------------------------------------------------


def emit_cpp(vs: list[Vector]) -> str:
    o: list[str] = []
    for line in BANNER:
        o.append(f"// {line}" if line else "//")
    o.append("")
    o.append("#pragma once")
    o.append("")
    o.append("#include <cstddef>")
    o.append("#include <cstdint>")
    o.append("#include <string>")
    o.append("")
    o.append('#include "wire/generated.hpp"')
    o.append('#include "golden_support.hpp"')
    o.append("")
    o.append("namespace mdstack::golden {")
    o.append("")
    o.append("using namespace mdstack::wire;")
    o.append("")
    for v in vs:
        emit_cpp_check(o, v)
        emit_cpp_build(o, v)
    o.append("struct Vector {")
    o.append("    const char* name;")
    o.append("    const char* file;")
    o.append("    const char* why;")
    o.append("    std::string (*check)(const std::byte*, std::size_t);")
    o.append("    std::size_t (*build)(std::byte*, std::size_t, std::string&);")
    o.append("};")
    o.append("")
    o.append("inline constexpr Vector kVectors[] = {")
    for v in vs:
        why = v.why.replace('"', '\\"')
        o.append(
            f'    {{"{v.name}", "{v.name}.bin", "{why}", check_{v.name}, build_{v.name}}},'
        )
    o.append("};")
    o.append("")
    o.append("}  // namespace mdstack::golden")
    return "\n".join(o).rstrip() + "\n"


def emit_cpp_check(o: list[str], v: Vector) -> None:
    o.append(f"// {v.why}")
    o.append(
        f"inline std::string check_{v.name}(const std::byte* buf, std::size_t len) {{"
    )
    o.append("    auto h = PacketHeaderDecoder::wrap(buf, len);")
    o.append('    if (!h) return "packet header: wrap failed";')
    o.append(f'    CHECK_EQ("packet.schemaId", h->schema_id(), {SCHEMA_ID});')
    o.append(f'    CHECK_EQ("packet.version", h->version(), {SCHEMA_VERSION});')
    o.append(
        f'    CHECK_EQ("packet.messageCount", h->message_count(), {len(v.messages)});'
    )
    o.append(f'    CHECK_EQ("packet.channel", h->channel(), {v.channel});')
    o.append(f'    CHECK_EQ("packet.flags", h->flags(), {v.flags});')
    o.append(
        f'    CHECK_EQ("packet.firstSequence", h->first_sequence(), '
        f"{v.first_sequence}ULL);"
    )
    o.append(
        f'    CHECK_EQ("packet.sendTimestampNs", h->send_timestamp_ns(), '
        f"{v.send_timestamp_ns}ULL);"
    )
    o.append(
        f'    CHECK_EQ("packet.isSnapshot", h->is_snapshot(), '
        f'{"true" if v.flags & 1 else "false"});'
    )
    o.append("    std::size_t pos = kPacketHeaderLen;")
    o.append(f"    const std::uint64_t first_seq = {v.first_sequence}ULL;")
    for i, m in enumerate(v.messages):
        o.append(f"    // message {i}")
        o.append("    {")
        o.append(
            f"        auto d = {m.kind}Decoder::wrap(buf + pos, len - pos);"
        )
        o.append(f'        if (!d) return "message {i}: not a decodable {m.kind}";')
        o.append(
            f'        CHECK_EQ("message {i} sequence", '
            f"static_cast<std::uint64_t>(first_seq + {i}ULL), "
            f"{(v.first_sequence + i) & 0xFFFFFFFFFFFFFFFF}ULL);"
        )
        for fname, fval in m.fields.items():
            emit_cpp_field_check(o, f"message {i}.{fname}", "d->", fname, fval)
        if m.kind == "Snapshot":
            o.append(
                f'        CHECK_EQ("message {i}.orders.numInGroup", d->orders_count(), {len(m.orders)});'
            )
            o.append(
                f'        CHECK_EQ("message {i}.orders.blockLength", d->orders_block_length(), {ORDER_BLOCK_LENGTH});'
            )
            for j, lvl in enumerate(m.orders):
                o.append(f"        {{")
                o.append(f"            auto l = d->order({j});")
                for fname, fval in lvl.items():
                    emit_cpp_field_check(
                        o, f"message {i}.orders[{j}].{fname}", "l.", fname, fval,
                        indent="            ",
                    )
                o.append("        }")
        o.append("        pos += d->total_len();")
        o.append("    }")
    o.append('    if (pos != len) return "trailing bytes past the last message";')
    o.append('    return "";')
    o.append("}")
    o.append("")


def emit_cpp_field_check(
    o: list[str], label: str, var: str, fname: str, fval: object,
    indent: str = "        ",
) -> None:
    if fname in ENUM_FIELDS:
        table = CPP_REASON if fname == "reason" else CPP_SIDE
        o.append(f"{indent}{{")
        o.append(f"{indent}    auto e = {var}{fname}();")
        o.append(f'{indent}    if (!e) return "{label}: undefined enum value";')
        o.append(
            f'{indent}    CHECK_EQ("{label}", static_cast<int>(*e), '
            f"static_cast<int>({table[fval]}));"
        )
        o.append(f"{indent}}}")
        return
    if isinstance(fval, int) and fval < 0:
        o.append(
            f'{indent}CHECK_EQ("{label}", {var}{fname}(), '
            f"static_cast<std::int64_t>({fval}));"
        )
        return
    suffix = "ULL" if isinstance(fval, int) and fval > 0xFFFFFFFF else ""
    o.append(f'{indent}CHECK_EQ("{label}", {var}{fname}(), {fval}{suffix});')


def emit_cpp_build(o: list[str], v: Vector) -> None:
    o.append(f"// Re-encodes `{v.name}` from the same values check_{v.name} asserts.")
    o.append(
        f"inline std::size_t build_{v.name}(std::byte* out, std::size_t cap, "
        "std::string& err) {"
    )
    o.append("    auto ph = encode_packet_header(out, cap")
    o.append(f"        , static_cast<std::uint8_t>({v.channel})")
    o.append(f"        , static_cast<std::uint8_t>({v.flags})")
    o.append(f"        , {v.first_sequence}ULL")
    o.append(f"        , {v.send_timestamp_ns}ULL")
    o.append("    );")
    o.append('    if (!ph) { err = "packet header did not fit"; return 0; }')
    o.append("    std::size_t pos = *ph;")
    for idx, m in enumerate(v.messages):
        o.append(f"    // message {idx}")
        if m.kind == "Snapshot":
            f = m.fields
            o.append("    {")
            o.append(
                f"        auto e = {m.kind}Encoder::start(out + pos, cap - pos"
            )
            o.append(f"            , {f['last_sequence']}ULL")
            o.append(f"            , static_cast<std::uint16_t>({f['symbol_id']})")
            o.append(f"            , static_cast<std::uint8_t>({f['flags']})")
            o.append("        );")
            o.append(f'        if (!e) {{ err = "message {idx} did not fit"; return 0; }}')
            for j, lv in enumerate(m.orders):
                o.append("        if (!e->push_order(")
                o.append(f"                static_cast<std::uint64_t>({lv['order_id']}ULL)")
                o.append(f"                , static_cast<std::int64_t>({lv['price']})")
                o.append(f"                , static_cast<std::uint32_t>({lv['quantity']})")
                o.append(f"                , {CPP_SIDE[lv['side']]}")
                o.append(
                    f'        )) {{ err = "message {idx} order {j} did not fit"; return 0; }}'
                )
            o.append("        pos += e->finish();")
            o.append("    }")
            continue
        fn = {
            "AddOrder": "encode_add_order", "ModifyOrder": "encode_modify_order",
            "DeleteOrder": "encode_delete_order", "Trade": "encode_trade",
            "Heartbeat": "encode_heartbeat", "SequenceReset": "encode_sequence_reset",
        }[m.kind]
        o.append("    {")
        o.append(f"        auto n = {fn}(out + pos, cap - pos")
        for fname, fval in m.fields.items():
            if fname in ENUM_FIELDS:
                table = CPP_REASON if fname == "reason" else CPP_SIDE
                o.append(f"            , {table[fval]}")
            else:
                o.append(f"            , {cpp_arg(m.kind, fname, fval)}")
        o.append("        );")
        o.append(f'        if (!n) {{ err = "message {idx} did not fit"; return 0; }}')
        o.append("        pos += *n;")
        o.append("    }")
    o.append(
        f"    if (!patch_message_count(out, cap, "
        f"static_cast<std::uint16_t>({len(v.messages)})))"
    )
    o.append('        { err = "could not patch messageCount"; return 0; }')
    o.append("    return pos;")
    o.append("}")
    o.append("")


CPP_CAST = {8: "std::uint64_t", 4: "std::uint32_t", 2: "std::uint16_t", 1: "std::uint8_t"}


def cpp_arg(kind: str, fname: str, fval: object) -> str:
    if fname in ("price", "new_price"):
        return f"static_cast<std::int64_t>({fval})"
    w = FIELD_WIDTH[kind][fname]
    assert isinstance(fval, int) and fval >= 0, f"{kind}.{fname} is unsigned on the wire"
    return f"static_cast<{CPP_CAST[w]}>({fval}ULL)"


# ---------------------------------------------------------------------------
# driver
# ---------------------------------------------------------------------------


def rustfmt(path: Path) -> None:
    """Format generated Rust in place.

    Duplicated from codegen.py rather than imported: this file deliberately does
    not depend on the emitters, and one four-line helper is a cheaper price than
    a caveat on that independence.
    """
    exe = shutil.which("rustfmt")
    if exe is None:
        print("  note: rustfmt not found; generated Rust left unformatted", file=sys.stderr)
        return
    subprocess.run([exe, "--edition", "2021", str(path)], check=True)


def format_rust_text(text: str, near: Path) -> str:
    """Return `text` as rustfmt would write it, without touching `near`."""
    scratch = near.parent / ".goldens.fmt.rs"
    scratch.parent.mkdir(parents=True, exist_ok=True)
    scratch.write_text(text, encoding="utf-8", newline="\n")
    try:
        rustfmt(scratch)
        return scratch.read_text(encoding="utf-8")
    finally:
        scratch.unlink(missing_ok=True)


def write(path: Path, data: bytes | str, check: bool, results: list[bool]) -> None:
    if isinstance(data, str):
        blob = data.encode("utf-8")
    else:
        blob = data
    current = path.read_bytes() if path.exists() else None
    rel = path.relative_to(REPO)
    if check:
        if current == blob:
            print(f"  ok    {rel}")
            results.append(True)
        else:
            print(f"  STALE {rel}", file=sys.stderr)
            results.append(False)
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(blob)
    print(f"  wrote {rel}")
    results.append(True)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="do not write; exit non-zero if stale")
    args = ap.parse_args()

    vs = vectors()

    # The hand-typed anchors come first: if a packer disagrees with the byte
    # table, nothing below is worth writing.
    by_name = {v.name: v for v in vs}
    for name, hexstr in HAND_TYPED.items():
        v = by_name.get(name)
        if v is None:
            raise SystemExit(f"HAND_TYPED names {name!r}, which is not a vector")
        expected = hexbytes(hexstr)
        actual = v.pack()
        if expected != actual:
            print(f"hand-typed anchor {name} does not match the packer:", file=sys.stderr)
            print(f"  hand-typed: {expected.hex(' ')}", file=sys.stderr)
            print(f"  packed:     {actual.hex(' ')}", file=sys.stderr)
            return 1
    covered = {m.kind for name in HAND_TYPED for m in by_name[name].messages}
    missing = set(TEMPLATE) - covered
    if missing:
        print(
            f"no hand-typed anchor covers: {', '.join(sorted(missing))}", file=sys.stderr
        )
        return 1
    print(f"{len(HAND_TYPED)} hand-typed anchors agree with the packers")

    results: list[bool] = []
    for v in vs:
        write(GOLDEN_DIR / f"{v.name}.bin", v.pack(), args.check, results)
        write(GOLDEN_DIR / f"{v.name}.txt", annotate(v), args.check, results)
    # rustfmt is part of the committed output, so --check has to compare against
    # formatted text or it would report a false staleness every run.
    write(RUST_OUT, format_rust_text(emit_rust(vs), RUST_OUT), args.check, results)
    write(CPP_OUT, emit_cpp(vs), args.check, results)

    if not all(results):
        print(
            "\ngolden vectors are stale: run `make goldens` and commit the result",
            file=sys.stderr,
        )
        return 1
    print(f"{len(vs)} vectors")
    return 0


if __name__ == "__main__":
    sys.exit(main())
