#!/usr/bin/env bash
#
# Milestone 7's second verifier: run this project's FIX session layer against
# QuickFIX and let QuickFIX judge it.
#
# # Why an independent implementation
#
# The 44 in-process session checks are a simulator this project wrote for
# itself. They are worth having — a scripted counterparty can construct inputs a
# real engine will not produce on demand — but they share an author with the
# code under test, so "correct" in them means "consistent with my own reading of
# the spec". This script removes that shared author. QuickFIX has no idea what
# `cpp/gateway` thinks FIX 4.4 says.
#
# Three things get exercised, in order, against one persistent QuickFIX store:
#
#   1. A clean session. Logon, five orders, heartbeats, logout. If any message
#      we build is malformed, misordered, short a required field, or carries a
#      bad BodyLength or CheckSum, QuickFIX answers with a Reject and this fails.
#   2. A gap we create on purpose, with `fix-seqtool`. QuickFIX must notice the
#      hole, ask for the range, and accept the SequenceReset-GapFill we answer
#      with. This is the half the kill-restart test cannot reach: over loopback
#      with a per-message fsync the two sides almost never disagree by
#      themselves.
#   3. A sequence reset. `--reset-seq` sends `ResetSeqNumFlag=Y`, and QuickFIX
#      has to accept it and follow us back to 1.
#
# # What it does not prove
#
# Debian's `libquickfix-dev` is a `+dfsg` package with the FIX XML dictionaries
# stripped, so the acceptor runs `UseDataDictionary=N`. QuickFIX still does the
# entire session layer — framing, checksums, sequence checking, resends, gap
# fill, heartbeats — which is what milestone 7 claims. It does not validate
# application message *content*, so nothing here says a NewOrderSingle carries
# every field FIX 4.4 requires of one. Said plainly rather than left implied.
#
#   scripts/quickfix-interop-test.sh
#   scripts/quickfix-interop-test.sh --keep    # leave logs, stores, observations
#
# Set QUICKFIX_REQUIRED=1 to turn "QuickFIX is not installed" from a skip into a
# failure. CI sets it, because a cross-check that silently skips is not one.

set -uo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO"

KEEP=0
[[ "${1:-}" == "--keep" ]] && KEEP=1

BUILD="${MDSTACK_BUILD_DIR:-$REPO/cpp/build}"
OUT="$REPO/results/quickfix-interop"
PORT=5511

rm -rf "$OUT"
mkdir -p "$OUT/qf-store" "$OUT/qf-log"

echo "building"
cmake -S cpp -B "$BUILD" -DCMAKE_BUILD_TYPE=RelWithDebInfo >"$OUT/cmake.log" 2>&1 || {
    cat "$OUT/cmake.log" >&2
    exit 1
}
cmake --build "$BUILD" --target fix-gateway fix-seqtool >>"$OUT/cmake.log" 2>&1 || {
    cat "$OUT/cmake.log" >&2
    exit 1
}
cmake --build "$BUILD" --target quickfix-acceptor >>"$OUT/cmake.log" 2>&1

GW="$BUILD/gateway/fix-gateway"
SEQTOOL="$BUILD/gateway/fix-seqtool"
QF="$BUILD/gateway/quickfix-acceptor"

if [[ ! -x "$QF" ]]; then
    echo
    echo "QuickFIX is not installed, so there is nothing independent to check against."
    echo "  Debian/Ubuntu:  sudo apt-get install -y libquickfix-dev"
    if [[ "${QUICKFIX_REQUIRED:-0}" == "1" ]]; then
        echo "quickfix-interop: FAIL — QUICKFIX_REQUIRED=1 and QuickFIX is missing" >&2
        exit 1
    fi
    echo "quickfix-interop: SKIPPED"
    exit 0
fi

GW_STORE="$OUT/gateway.seq"
CFG="$OUT/acceptor.cfg"

cat >"$CFG" <<EOF
# Generated by scripts/quickfix-interop-test.sh. Nothing here is tuned; it is
# the plainest FIX 4.4 acceptor QuickFIX will start, so that anything it
# complains about is our doing and not this file's.
[DEFAULT]
ConnectionType=acceptor
SocketAcceptPort=$PORT
StartTime=00:00:00
EndTime=00:00:00
UseDataDictionary=N
ValidateLengthAndChecksum=Y
PersistMessages=Y
FileStorePath=$OUT/qf-store
FileLogPath=$OUT/qf-log

[SESSION]
BeginString=FIX.4.4
SenderCompID=EXCHANGE
TargetCompID=GATEWAY
HeartBtInt=5
EOF

status=0
fail() {
    echo "  FAIL: $*" >&2
    status=1
}

# `key=value` out of an observations file; empty string if the key is absent,
# which every caller treats as a failure rather than a zero.
obs() {
    local key="$1" file="$2"
    grep -E "^$key=" "$file" 2>/dev/null | head -1 | cut -d= -f2-
}

expect_eq() {
    local what="$1" got="$2" want="$3"
    if [[ "$got" == "$want" ]]; then
        echo "  $what = $got"
    else
        fail "$what = ${got:-<missing>}, expected $want"
    fi
}

expect_at_least() {
    local what="$1" got="$2" want="$3"
    if [[ -n "$got" && "$got" -ge "$want" ]]; then
        echo "  $what = $got (needed at least $want)"
    else
        fail "$what = ${got:-<missing>}, expected at least $want"
    fi
}

# Run one scenario: start the acceptor, run the gateway against it, stop the
# acceptor politely so it writes what it saw.
run_scenario() {
    local name="$1"; shift
    local obs_file="$OUT/$name.obs"

    "$QF" "$CFG" 25 "$obs_file" >"$OUT/$name-quickfix.log" 2>&1 &
    local qf_pid=$!
    sleep 1.5

    "$GW" --connect "127.0.0.1:$PORT" --store "$GW_STORE" \
        --sender GATEWAY --target EXCHANGE --heartbeat 5 "$@" \
        >"$OUT/$name-gateway.log" 2>&1
    GW_STATUS=$?

    kill -TERM "$qf_pid" 2>/dev/null
    wait "$qf_pid" 2>/dev/null

    if [[ ! -s "$obs_file" ]]; then
        fail "$name: the acceptor wrote no observations"
        return 1
    fi
    return 0
}

# --------------------------------------------------------------------------
echo
echo "=============================================================="
echo " one: a clean session, judged by QuickFIX"
echo "=============================================================="
run_scenario clean --send-orders 5 --run-seconds 8
A="$OUT/clean.obs"
if [[ -s "$A" ]]; then
    expect_eq   "logons"       "$(obs logons "$A")" 1
    expect_eq   "app messages QuickFIX accepted" "$(obs app_messages "$A")" 5
    expect_eq   "rejects QuickFIX sent us"       "$(obs rejects_sent "$A")" 0
    [[ -n "$(obs error "$A")" ]] && fail "the acceptor reported: $(obs error "$A")"
    [[ $GW_STATUS -ne 0 ]] && fail "the gateway exited $GW_STATUS"
    echo "  admin messages QuickFIX accepted from us:"
    grep -E '^admin_' "$A" | sed 's/^/    /'
fi

# --------------------------------------------------------------------------
echo
echo "=============================================================="
echo " two: a gap on purpose — QuickFIX must ask, we must gap-fill"
echo "=============================================================="
before="$("$SEQTOOL" --store "$GW_STORE" | grep '^outbound=' | cut -d= -f2)"
"$SEQTOOL" --store "$GW_STORE" --set-outbound $((before + 5)) >/dev/null
echo "  moved the gateway's outbound from $before to $((before + 5)), leaving a"
echo "  five-message hole QuickFIX has no way of knowing about in advance"

run_scenario gap --send-orders 2 --run-seconds 10
B="$OUT/gap.obs"
if [[ -s "$B" ]]; then
    expect_at_least "resend requests QuickFIX sent"   "$(obs resend_requests_sent "$B")" 1
    expect_at_least "sequence resets QuickFIX took"   "$(obs sequence_resets_received "$B")" 1
    expect_at_least "of those, gap fills"             "$(obs gap_fills_received "$B")" 1
    expect_eq       "rejects QuickFIX sent us"        "$(obs rejects_sent "$B")" 0
    expect_eq       "logons"                          "$(obs logons "$B")" 1
    [[ -n "$(obs error "$B")" ]] && fail "the acceptor reported: $(obs error "$B")"
fi

# --------------------------------------------------------------------------
echo
echo "=============================================================="
echo " three: ResetSeqNumFlag — QuickFIX must follow us back to 1"
echo "=============================================================="
before_reset="$("$SEQTOOL" --store "$GW_STORE" | grep '^outbound=' | cut -d= -f2)"
run_scenario reset --reset-seq --send-orders 2 --run-seconds 8
C="$OUT/reset.obs"
if [[ -s "$C" ]]; then
    expect_eq "logons"                        "$(obs logons "$C")" 1
    expect_eq "app messages QuickFIX accepted" "$(obs app_messages "$C")" 2
    expect_eq "rejects QuickFIX sent us"      "$(obs rejects_sent "$C")" 0
    [[ -n "$(obs error "$C")" ]] && fail "the acceptor reported: $(obs error "$C")"
    # Not an exact number: how many heartbeats fit in the run is the runner's
    # business. What has to be true is that the counter went *backwards* over a
    # reset and is still in single figures rather than continuing from 18.
    after="$("$SEQTOOL" --store "$GW_STORE" | grep '^outbound=' | cut -d= -f2)"
    if [[ -n "$after" && "$after" -lt "$before_reset" && "$after" -le 10 ]]; then
        echo "  the gateway's outbound went from $before_reset back to 1, reaching $after"
    else
        fail "after a reset the gateway's outbound is $after (was $before_reset), so it did not restart at 1"
    fi
fi

# --------------------------------------------------------------------------
echo
if [[ $status -eq 0 ]]; then
    echo "quickfix-interop: PASS — an implementation this project did not write"
    echo "                  accepted its session layer, asked for the range it was"
    echo "                  missing, and took the gap fill and the reset"
    [[ $KEEP -eq 0 ]] && rm -rf "$OUT"
else
    echo "quickfix-interop: FAIL — artifacts in $OUT" >&2
    echo "                  QuickFIX's own log is the place to look:" >&2
    ls "$OUT/qf-log" 2>/dev/null | sed 's/^/                    /' >&2
fi
exit $status
