//! @generated by schema/goldens.py -- do not edit.
//!
//! Both test suites assert these same field values against the same
//! schema/golden/*.bin files, then re-encode and require the bytes back.

#![allow(clippy::unreadable_literal)]

use wire::*;

// Comparison helpers. Each names the field, because a golden-vector
// failure that says only "mismatch" costs more time than the test saved.
macro_rules! eq_fn {
    ($name:ident, $ty:ty) => {
        #[allow(dead_code)]
        fn $name(label: &str, actual: $ty, expected: $ty) -> Result<(), String> {
            if actual != expected {
                return Err(format!("{label}: expected {expected}, got {actual}"));
            }
            Ok(())
        }
    };
}

eq_fn!(eq_u8, u8);
eq_fn!(eq_u16, u16);
eq_fn!(eq_u32, u32);
eq_fn!(eq_u64, u64);
eq_fn!(eq_i64, i64);
eq_fn!(eq_bool, bool);

/// One golden vector: the file, the field values, and the encoder path
/// that must reproduce the file byte for byte.
pub struct Vector {
    pub name: &'static str,
    pub file: &'static str,
    pub why: &'static str,
    pub check: fn(&[u8]) -> Result<(), String>,
    pub build: fn(&mut [u8]) -> Result<usize, WireError>,
}

pub const VECTORS: &[Vector] = &[
    Vector {
        name: "add_order",
        file: "add_order.bin",
        why: "One AddOrder. Anchors the AddOrder block and the packet header.",
        check: check_add_order,
        build: build_add_order,
    },
    Vector {
        name: "modify_order",
        file: "modify_order.bin",
        why: "A Replace, which loses queue priority. channel=1 exercises the B arm.",
        check: check_modify_order,
        build: build_modify_order,
    },
    Vector {
        name: "delete_order",
        file: "delete_order.bin",
        why: "The shortest message: a 12-byte block that leaves the next message 4-byte aligned.",
        check: check_delete_order,
        build: build_delete_order,
    },
    Vector {
        name: "trade",
        file: "trade.bin",
        why: "The longest fixed block, and the only message naming two orders.",
        check: check_trade,
        build: build_trade,
    },
    Vector {
        name: "heartbeat",
        file: "heartbeat.bin",
        why: "Idle-channel keepalive; the handler uses it to tell quiet from dead.",
        check: check_heartbeat,
        build: build_heartbeat,
    },
    Vector {
        name: "sequence_reset",
        file: "sequence_reset.bin",
        why: "The publisher restarts its numbering.",
        check: check_sequence_reset,
        build: build_sequence_reset,
    },
    Vector {
        name: "snapshot_two_orders",
        file: "snapshot_two_orders.bin",
        why: "The repeating group, the snapshot flag on the packet header, and the last-fragment flag on the message. Orders are listed in queue order: a consumer that re-adds them in this order reproduces price-time priority exactly, which an aggregated snapshot could never do.",
        check: check_snapshot_two_orders,
        build: build_snapshot_two_orders,
    },
    Vector {
        name: "snapshot_empty_group",
        file: "snapshot_empty_group.bin",
        why: "A snapshot of an empty book. numInGroup=0 must still carry the group header, or total_len walks the reader into the next message.",
        check: check_snapshot_empty_group,
        build: build_snapshot_empty_group,
    },
    Vector {
        name: "batch_mixed",
        file: "batch_mixed.bin",
        why: "Six messages of five types behind one header, including a variable-length snapshot in the middle. This is the vector that proves a decoder can walk a batch: get any total_len wrong and every message after it is garbage. Batching is not an optimisation here, it is the framing the throughput target depends on.",
        check: check_batch_mixed,
        build: build_batch_mixed,
    },
    Vector {
        name: "negative_price",
        file: "negative_price.bin",
        why: "Prices are signed on the wire. Spreads, settlement marks and a few real contracts go below zero, and a decoder that reads the field as unsigned looks correct until the day one does.",
        check: check_negative_price,
        build: build_negative_price,
    },
    Vector {
        name: "sequence_wrap_high",
        file: "sequence_wrap_high.bin",
        why: "firstSequence near 2^64. The sequence of message i is firstSequence+i, so a reader that widens through i32 or i64 breaks here and nowhere else.",
        check: check_sequence_wrap_high,
        build: build_sequence_wrap_high,
    },
];

/// One AddOrder. Anchors the AddOrder block and the packet header.
pub fn check_add_order(buf: &[u8]) -> Result<(), String> {
    let r = PacketReader::new(buf).map_err(|e| format!("packet header: {e}"))?;
    let h = r.header();
    eq_u16("packet.schemaId", h.schema_id(), 1)?;
    eq_u16("packet.version", h.version(), 1)?;
    eq_u16("packet.messageCount", h.message_count(), 1)?;
    eq_u8("packet.channel", h.channel(), 0)?;
    eq_u8("packet.flags", h.flags(), 0)?;
    eq_u64("packet.firstSequence", h.first_sequence(), 1048576)?;
    eq_u64(
        "packet.sendTimestampNs",
        h.send_timestamp_ns(),
        1702361767298204934,
    )?;
    eq_bool("packet.isSnapshot", h.is_snapshot(), false)?;

    let mut it = r.messages();
    // message 0
    let (seq, msg) = it
        .next()
        .ok_or_else(|| "message 0: missing".to_string())?
        .map_err(|e| format!("message 0: {e}"))?;
    eq_u64("message 0 sequence", seq, 1048576)?;
    let Message::AddOrder(d) = msg else {
        return Err(format!(
            "message 0: expected AddOrder, got template {}",
            msg.template_id()
        ));
    };
    eq_u64("message 0.order_id", d.order_id(), 4294967298u64)?;
    eq_i64("message 0.price", d.price(), 1012500)?;
    eq_u32("message 0.quantity", d.quantity(), 250u32)?;
    eq_u16("message 0.symbol_id", d.symbol_id(), 7u16)?;
    if d.side().map_err(|e| format!("message 0.side: {e}"))? != Side::Bid {
        return Err(format!(
            "message 0.side: expected Side::Bid, got {:?}",
            d.side()
        ));
    }

    if it.next().is_some() {
        return Err("extra messages past messageCount".to_string());
    }
    Ok(())
}

/// Re-encodes `add_order` from the same values `check_add_order` asserts.
pub fn build_add_order(out: &mut [u8]) -> Result<usize, WireError> {
    let mut w = PacketWriter::new(out, 0, 0, 1048576, 1702361767298204934)?;
    w.add_order(4294967298, 1012500, 250, 7, Side::Bid)?;
    Ok(w.finish())
}

/// A Replace, which loses queue priority. channel=1 exercises the B arm.
pub fn check_modify_order(buf: &[u8]) -> Result<(), String> {
    let r = PacketReader::new(buf).map_err(|e| format!("packet header: {e}"))?;
    let h = r.header();
    eq_u16("packet.schemaId", h.schema_id(), 1)?;
    eq_u16("packet.version", h.version(), 1)?;
    eq_u16("packet.messageCount", h.message_count(), 1)?;
    eq_u8("packet.channel", h.channel(), 1)?;
    eq_u8("packet.flags", h.flags(), 0)?;
    eq_u64("packet.firstSequence", h.first_sequence(), 1048577)?;
    eq_u64(
        "packet.sendTimestampNs",
        h.send_timestamp_ns(),
        1702361767298204934,
    )?;
    eq_bool("packet.isSnapshot", h.is_snapshot(), false)?;

    let mut it = r.messages();
    // message 0
    let (seq, msg) = it
        .next()
        .ok_or_else(|| "message 0: missing".to_string())?
        .map_err(|e| format!("message 0: {e}"))?;
    eq_u64("message 0 sequence", seq, 1048577)?;
    let Message::ModifyOrder(d) = msg else {
        return Err(format!(
            "message 0: expected ModifyOrder, got template {}",
            msg.template_id()
        ));
    };
    eq_u64("message 0.order_id", d.order_id(), 4294967298u64)?;
    eq_i64("message 0.new_price", d.new_price(), 1012600)?;
    eq_u32("message 0.new_quantity", d.new_quantity(), 100u32)?;
    eq_u16("message 0.symbol_id", d.symbol_id(), 7u16)?;
    if d.side().map_err(|e| format!("message 0.side: {e}"))? != Side::Bid {
        return Err(format!(
            "message 0.side: expected Side::Bid, got {:?}",
            d.side()
        ));
    }
    if d.reason().map_err(|e| format!("message 0.reason: {e}"))? != ModifyReason::Replace {
        return Err(format!(
            "message 0.reason: expected ModifyReason::Replace, got {:?}",
            d.reason()
        ));
    }

    if it.next().is_some() {
        return Err("extra messages past messageCount".to_string());
    }
    Ok(())
}

/// Re-encodes `modify_order` from the same values `check_modify_order` asserts.
pub fn build_modify_order(out: &mut [u8]) -> Result<usize, WireError> {
    let mut w = PacketWriter::new(out, 1, 0, 1048577, 1702361767298204934)?;
    w.modify_order(
        4294967298,
        1012600,
        100,
        7,
        Side::Bid,
        ModifyReason::Replace,
    )?;
    Ok(w.finish())
}

/// The shortest message: a 12-byte block that leaves the next message 4-byte aligned.
pub fn check_delete_order(buf: &[u8]) -> Result<(), String> {
    let r = PacketReader::new(buf).map_err(|e| format!("packet header: {e}"))?;
    let h = r.header();
    eq_u16("packet.schemaId", h.schema_id(), 1)?;
    eq_u16("packet.version", h.version(), 1)?;
    eq_u16("packet.messageCount", h.message_count(), 1)?;
    eq_u8("packet.channel", h.channel(), 0)?;
    eq_u8("packet.flags", h.flags(), 0)?;
    eq_u64("packet.firstSequence", h.first_sequence(), 1048578)?;
    eq_u64(
        "packet.sendTimestampNs",
        h.send_timestamp_ns(),
        1702361767298204934,
    )?;
    eq_bool("packet.isSnapshot", h.is_snapshot(), false)?;

    let mut it = r.messages();
    // message 0
    let (seq, msg) = it
        .next()
        .ok_or_else(|| "message 0: missing".to_string())?
        .map_err(|e| format!("message 0: {e}"))?;
    eq_u64("message 0 sequence", seq, 1048578)?;
    let Message::DeleteOrder(d) = msg else {
        return Err(format!(
            "message 0: expected DeleteOrder, got template {}",
            msg.template_id()
        ));
    };
    eq_u64("message 0.order_id", d.order_id(), 4294967298u64)?;
    eq_u16("message 0.symbol_id", d.symbol_id(), 7u16)?;
    if d.side().map_err(|e| format!("message 0.side: {e}"))? != Side::Ask {
        return Err(format!(
            "message 0.side: expected Side::Ask, got {:?}",
            d.side()
        ));
    }

    if it.next().is_some() {
        return Err("extra messages past messageCount".to_string());
    }
    Ok(())
}

/// Re-encodes `delete_order` from the same values `check_delete_order` asserts.
pub fn build_delete_order(out: &mut [u8]) -> Result<usize, WireError> {
    let mut w = PacketWriter::new(out, 0, 0, 1048578, 1702361767298204934)?;
    w.delete_order(4294967298, 7, Side::Ask)?;
    Ok(w.finish())
}

/// The longest fixed block, and the only message naming two orders.
pub fn check_trade(buf: &[u8]) -> Result<(), String> {
    let r = PacketReader::new(buf).map_err(|e| format!("packet header: {e}"))?;
    let h = r.header();
    eq_u16("packet.schemaId", h.schema_id(), 1)?;
    eq_u16("packet.version", h.version(), 1)?;
    eq_u16("packet.messageCount", h.message_count(), 1)?;
    eq_u8("packet.channel", h.channel(), 0)?;
    eq_u8("packet.flags", h.flags(), 0)?;
    eq_u64("packet.firstSequence", h.first_sequence(), 1048579)?;
    eq_u64(
        "packet.sendTimestampNs",
        h.send_timestamp_ns(),
        1702361767298204934,
    )?;
    eq_bool("packet.isSnapshot", h.is_snapshot(), false)?;

    let mut it = r.messages();
    // message 0
    let (seq, msg) = it
        .next()
        .ok_or_else(|| "message 0: missing".to_string())?
        .map_err(|e| format!("message 0: {e}"))?;
    eq_u64("message 0 sequence", seq, 1048579)?;
    let Message::Trade(d) = msg else {
        return Err(format!(
            "message 0: expected Trade, got template {}",
            msg.template_id()
        ));
    };
    eq_u64("message 0.trade_id", d.trade_id(), 17u64)?;
    eq_u64(
        "message 0.aggressor_order_id",
        d.aggressor_order_id(),
        4294967298u64,
    )?;
    eq_u64(
        "message 0.resting_order_id",
        d.resting_order_id(),
        4294967299u64,
    )?;
    eq_i64("message 0.price", d.price(), 1012500)?;
    eq_u32("message 0.quantity", d.quantity(), 50u32)?;
    eq_u16("message 0.symbol_id", d.symbol_id(), 7u16)?;
    if d.aggressor_side()
        .map_err(|e| format!("message 0.aggressor_side: {e}"))?
        != Side::Ask
    {
        return Err(format!(
            "message 0.aggressor_side: expected Side::Ask, got {:?}",
            d.aggressor_side()
        ));
    }

    if it.next().is_some() {
        return Err("extra messages past messageCount".to_string());
    }
    Ok(())
}

/// Re-encodes `trade` from the same values `check_trade` asserts.
pub fn build_trade(out: &mut [u8]) -> Result<usize, WireError> {
    let mut w = PacketWriter::new(out, 0, 0, 1048579, 1702361767298204934)?;
    w.trade(17, 4294967298, 4294967299, 1012500, 50, 7, Side::Ask)?;
    Ok(w.finish())
}

/// Idle-channel keepalive; the handler uses it to tell quiet from dead.
pub fn check_heartbeat(buf: &[u8]) -> Result<(), String> {
    let r = PacketReader::new(buf).map_err(|e| format!("packet header: {e}"))?;
    let h = r.header();
    eq_u16("packet.schemaId", h.schema_id(), 1)?;
    eq_u16("packet.version", h.version(), 1)?;
    eq_u16("packet.messageCount", h.message_count(), 1)?;
    eq_u8("packet.channel", h.channel(), 1)?;
    eq_u8("packet.flags", h.flags(), 0)?;
    eq_u64("packet.firstSequence", h.first_sequence(), 1048580)?;
    eq_u64(
        "packet.sendTimestampNs",
        h.send_timestamp_ns(),
        1702361767298204934,
    )?;
    eq_bool("packet.isSnapshot", h.is_snapshot(), false)?;

    let mut it = r.messages();
    // message 0
    let (seq, msg) = it
        .next()
        .ok_or_else(|| "message 0: missing".to_string())?
        .map_err(|e| format!("message 0: {e}"))?;
    eq_u64("message 0 sequence", seq, 1048580)?;
    let Message::Heartbeat(d) = msg else {
        return Err(format!(
            "message 0: expected Heartbeat, got template {}",
            msg.template_id()
        ));
    };
    eq_u64("message 0.last_sequence", d.last_sequence(), 1048580u64)?;

    if it.next().is_some() {
        return Err("extra messages past messageCount".to_string());
    }
    Ok(())
}

/// Re-encodes `heartbeat` from the same values `check_heartbeat` asserts.
pub fn build_heartbeat(out: &mut [u8]) -> Result<usize, WireError> {
    let mut w = PacketWriter::new(out, 1, 0, 1048580, 1702361767298204934)?;
    w.heartbeat(1048580)?;
    Ok(w.finish())
}

/// The publisher restarts its numbering.
pub fn check_sequence_reset(buf: &[u8]) -> Result<(), String> {
    let r = PacketReader::new(buf).map_err(|e| format!("packet header: {e}"))?;
    let h = r.header();
    eq_u16("packet.schemaId", h.schema_id(), 1)?;
    eq_u16("packet.version", h.version(), 1)?;
    eq_u16("packet.messageCount", h.message_count(), 1)?;
    eq_u8("packet.channel", h.channel(), 0)?;
    eq_u8("packet.flags", h.flags(), 0)?;
    eq_u64("packet.firstSequence", h.first_sequence(), 1048581)?;
    eq_u64(
        "packet.sendTimestampNs",
        h.send_timestamp_ns(),
        1702361767298204934,
    )?;
    eq_bool("packet.isSnapshot", h.is_snapshot(), false)?;

    let mut it = r.messages();
    // message 0
    let (seq, msg) = it
        .next()
        .ok_or_else(|| "message 0: missing".to_string())?
        .map_err(|e| format!("message 0: {e}"))?;
    eq_u64("message 0 sequence", seq, 1048581)?;
    let Message::SequenceReset(d) = msg else {
        return Err(format!(
            "message 0: expected SequenceReset, got template {}",
            msg.template_id()
        ));
    };
    eq_u64("message 0.new_sequence", d.new_sequence(), 2097152u64)?;

    if it.next().is_some() {
        return Err("extra messages past messageCount".to_string());
    }
    Ok(())
}

/// Re-encodes `sequence_reset` from the same values `check_sequence_reset` asserts.
pub fn build_sequence_reset(out: &mut [u8]) -> Result<usize, WireError> {
    let mut w = PacketWriter::new(out, 0, 0, 1048581, 1702361767298204934)?;
    w.sequence_reset(2097152)?;
    Ok(w.finish())
}

/// The repeating group, the snapshot flag on the packet header, and the last-fragment flag on the message. Orders are listed in queue order: a consumer that re-adds them in this order reproduces price-time priority exactly, which an aggregated snapshot could never do.
pub fn check_snapshot_two_orders(buf: &[u8]) -> Result<(), String> {
    let r = PacketReader::new(buf).map_err(|e| format!("packet header: {e}"))?;
    let h = r.header();
    eq_u16("packet.schemaId", h.schema_id(), 1)?;
    eq_u16("packet.version", h.version(), 1)?;
    eq_u16("packet.messageCount", h.message_count(), 1)?;
    eq_u8("packet.channel", h.channel(), 0)?;
    eq_u8("packet.flags", h.flags(), 1)?;
    eq_u64("packet.firstSequence", h.first_sequence(), 1048582)?;
    eq_u64(
        "packet.sendTimestampNs",
        h.send_timestamp_ns(),
        1702361767298204934,
    )?;
    eq_bool("packet.isSnapshot", h.is_snapshot(), true)?;

    let mut it = r.messages();
    // message 0
    let (seq, msg) = it
        .next()
        .ok_or_else(|| "message 0: missing".to_string())?
        .map_err(|e| format!("message 0: {e}"))?;
    eq_u64("message 0 sequence", seq, 1048582)?;
    let Message::Snapshot(d) = msg else {
        return Err(format!(
            "message 0: expected Snapshot, got template {}",
            msg.template_id()
        ));
    };
    eq_u64("message 0.last_sequence", d.last_sequence(), 1048576u64)?;
    eq_u16("message 0.symbol_id", d.symbol_id(), 7u16)?;
    eq_u8("message 0.flags", d.flags(), 1u8)?;
    eq_u16("message 0.orders.numInGroup", d.orders_count(), 2)?;
    eq_u16("message 0.orders.blockLength", d.orders_block_length(), 24)?;
    let mut lv = d.orders();
    let l = lv
        .next()
        .ok_or_else(|| "message 0: level 0 missing".to_string())?;
    eq_u64("message 0.orders[0].order_id", l.order_id(), 4294967298u64)?;
    eq_i64("message 0.orders[0].price", l.price(), 1012500)?;
    eq_u32("message 0.orders[0].quantity", l.quantity(), 250u32)?;
    if l.side()
        .map_err(|e| format!("message 0.orders[0].side: {e}"))?
        != Side::Bid
    {
        return Err(format!(
            "message 0.orders[0].side: expected Side::Bid, got {:?}",
            l.side()
        ));
    }
    let l = lv
        .next()
        .ok_or_else(|| "message 0: level 1 missing".to_string())?;
    eq_u64("message 0.orders[1].order_id", l.order_id(), 4294967299u64)?;
    eq_i64("message 0.orders[1].price", l.price(), 1012600)?;
    eq_u32("message 0.orders[1].quantity", l.quantity(), 100u32)?;
    if l.side()
        .map_err(|e| format!("message 0.orders[1].side: {e}"))?
        != Side::Ask
    {
        return Err(format!(
            "message 0.orders[1].side: expected Side::Ask, got {:?}",
            l.side()
        ));
    }
    if lv.next().is_some() {
        return Err("message 0: extra levels".to_string());
    }

    if it.next().is_some() {
        return Err("extra messages past messageCount".to_string());
    }
    Ok(())
}

/// Re-encodes `snapshot_two_orders` from the same values `check_snapshot_two_orders` asserts.
pub fn build_snapshot_two_orders(out: &mut [u8]) -> Result<usize, WireError> {
    let mut w = PacketWriter::new(out, 0, 1, 1048582, 1702361767298204934)?;
    let n = {
        let mut e = SnapshotEncoder::start(w.tail(), 1048576, 7, 1)?;
        e.push_order(4294967298, 1012500, 250, Side::Bid)?;
        e.push_order(4294967299, 1012600, 100, Side::Ask)?;
        e.finish()
    };
    w.commit(n)?;
    Ok(w.finish())
}

/// A snapshot of an empty book. numInGroup=0 must still carry the group header, or total_len walks the reader into the next message.
pub fn check_snapshot_empty_group(buf: &[u8]) -> Result<(), String> {
    let r = PacketReader::new(buf).map_err(|e| format!("packet header: {e}"))?;
    let h = r.header();
    eq_u16("packet.schemaId", h.schema_id(), 1)?;
    eq_u16("packet.version", h.version(), 1)?;
    eq_u16("packet.messageCount", h.message_count(), 1)?;
    eq_u8("packet.channel", h.channel(), 0)?;
    eq_u8("packet.flags", h.flags(), 1)?;
    eq_u64("packet.firstSequence", h.first_sequence(), 1048583)?;
    eq_u64(
        "packet.sendTimestampNs",
        h.send_timestamp_ns(),
        1702361767298204934,
    )?;
    eq_bool("packet.isSnapshot", h.is_snapshot(), true)?;

    let mut it = r.messages();
    // message 0
    let (seq, msg) = it
        .next()
        .ok_or_else(|| "message 0: missing".to_string())?
        .map_err(|e| format!("message 0: {e}"))?;
    eq_u64("message 0 sequence", seq, 1048583)?;
    let Message::Snapshot(d) = msg else {
        return Err(format!(
            "message 0: expected Snapshot, got template {}",
            msg.template_id()
        ));
    };
    eq_u64("message 0.last_sequence", d.last_sequence(), 1048583u64)?;
    eq_u16("message 0.symbol_id", d.symbol_id(), 9u16)?;
    eq_u8("message 0.flags", d.flags(), 1u8)?;
    eq_u16("message 0.orders.numInGroup", d.orders_count(), 0)?;
    eq_u16("message 0.orders.blockLength", d.orders_block_length(), 24)?;
    let mut lv = d.orders();
    if lv.next().is_some() {
        return Err("message 0: extra levels".to_string());
    }

    if it.next().is_some() {
        return Err("extra messages past messageCount".to_string());
    }
    Ok(())
}

/// Re-encodes `snapshot_empty_group` from the same values `check_snapshot_empty_group` asserts.
pub fn build_snapshot_empty_group(out: &mut [u8]) -> Result<usize, WireError> {
    let mut w = PacketWriter::new(out, 0, 1, 1048583, 1702361767298204934)?;
    let n = {
        let e = SnapshotEncoder::start(w.tail(), 1048583, 9, 1)?;
        e.finish()
    };
    w.commit(n)?;
    Ok(w.finish())
}

/// Six messages of five types behind one header, including a variable-length snapshot in the middle. This is the vector that proves a decoder can walk a batch: get any total_len wrong and every message after it is garbage. Batching is not an optimisation here, it is the framing the throughput target depends on.
pub fn check_batch_mixed(buf: &[u8]) -> Result<(), String> {
    let r = PacketReader::new(buf).map_err(|e| format!("packet header: {e}"))?;
    let h = r.header();
    eq_u16("packet.schemaId", h.schema_id(), 1)?;
    eq_u16("packet.version", h.version(), 1)?;
    eq_u16("packet.messageCount", h.message_count(), 6)?;
    eq_u8("packet.channel", h.channel(), 0)?;
    eq_u8("packet.flags", h.flags(), 0)?;
    eq_u64("packet.firstSequence", h.first_sequence(), 4294967294)?;
    eq_u64(
        "packet.sendTimestampNs",
        h.send_timestamp_ns(),
        1702361767298204934,
    )?;
    eq_bool("packet.isSnapshot", h.is_snapshot(), false)?;

    let mut it = r.messages();
    // message 0
    let (seq, msg) = it
        .next()
        .ok_or_else(|| "message 0: missing".to_string())?
        .map_err(|e| format!("message 0: {e}"))?;
    eq_u64("message 0 sequence", seq, 4294967294)?;
    let Message::AddOrder(d) = msg else {
        return Err(format!(
            "message 0: expected AddOrder, got template {}",
            msg.template_id()
        ));
    };
    eq_u64("message 0.order_id", d.order_id(), 8589934593u64)?;
    eq_i64("message 0.price", d.price(), 990000)?;
    eq_u32("message 0.quantity", d.quantity(), 1000u32)?;
    eq_u16("message 0.symbol_id", d.symbol_id(), 3u16)?;
    if d.side().map_err(|e| format!("message 0.side: {e}"))? != Side::Bid {
        return Err(format!(
            "message 0.side: expected Side::Bid, got {:?}",
            d.side()
        ));
    }

    // message 1
    let (seq, msg) = it
        .next()
        .ok_or_else(|| "message 1: missing".to_string())?
        .map_err(|e| format!("message 1: {e}"))?;
    eq_u64("message 1 sequence", seq, 4294967295)?;
    let Message::DeleteOrder(d) = msg else {
        return Err(format!(
            "message 1: expected DeleteOrder, got template {}",
            msg.template_id()
        ));
    };
    eq_u64("message 1.order_id", d.order_id(), 8589934594u64)?;
    eq_u16("message 1.symbol_id", d.symbol_id(), 3u16)?;
    if d.side().map_err(|e| format!("message 1.side: {e}"))? != Side::Ask {
        return Err(format!(
            "message 1.side: expected Side::Ask, got {:?}",
            d.side()
        ));
    }

    // message 2
    let (seq, msg) = it
        .next()
        .ok_or_else(|| "message 2: missing".to_string())?
        .map_err(|e| format!("message 2: {e}"))?;
    eq_u64("message 2 sequence", seq, 4294967296)?;
    let Message::Snapshot(d) = msg else {
        return Err(format!(
            "message 2: expected Snapshot, got template {}",
            msg.template_id()
        ));
    };
    eq_u64("message 2.last_sequence", d.last_sequence(), 4294967295u64)?;
    eq_u16("message 2.symbol_id", d.symbol_id(), 3u16)?;
    eq_u8("message 2.flags", d.flags(), 0u8)?;
    eq_u16("message 2.orders.numInGroup", d.orders_count(), 3)?;
    eq_u16("message 2.orders.blockLength", d.orders_block_length(), 24)?;
    let mut lv = d.orders();
    let l = lv
        .next()
        .ok_or_else(|| "message 2: level 0 missing".to_string())?;
    eq_u64("message 2.orders[0].order_id", l.order_id(), 8589934593u64)?;
    eq_i64("message 2.orders[0].price", l.price(), 990000)?;
    eq_u32("message 2.orders[0].quantity", l.quantity(), 1000u32)?;
    if l.side()
        .map_err(|e| format!("message 2.orders[0].side: {e}"))?
        != Side::Bid
    {
        return Err(format!(
            "message 2.orders[0].side: expected Side::Bid, got {:?}",
            l.side()
        ));
    }
    let l = lv
        .next()
        .ok_or_else(|| "message 2: level 1 missing".to_string())?;
    eq_u64("message 2.orders[1].order_id", l.order_id(), 8589934596u64)?;
    eq_i64("message 2.orders[1].price", l.price(), 990100)?;
    eq_u32("message 2.orders[1].quantity", l.quantity(), 400u32)?;
    if l.side()
        .map_err(|e| format!("message 2.orders[1].side: {e}"))?
        != Side::Ask
    {
        return Err(format!(
            "message 2.orders[1].side: expected Side::Ask, got {:?}",
            l.side()
        ));
    }
    let l = lv
        .next()
        .ok_or_else(|| "message 2: level 2 missing".to_string())?;
    eq_u64("message 2.orders[2].order_id", l.order_id(), 8589934597u64)?;
    eq_i64("message 2.orders[2].price", l.price(), 990200)?;
    eq_u32("message 2.orders[2].quantity", l.quantity(), 700u32)?;
    if l.side()
        .map_err(|e| format!("message 2.orders[2].side: {e}"))?
        != Side::Ask
    {
        return Err(format!(
            "message 2.orders[2].side: expected Side::Ask, got {:?}",
            l.side()
        ));
    }
    if lv.next().is_some() {
        return Err("message 2: extra levels".to_string());
    }

    // message 3
    let (seq, msg) = it
        .next()
        .ok_or_else(|| "message 3: missing".to_string())?
        .map_err(|e| format!("message 3: {e}"))?;
    eq_u64("message 3 sequence", seq, 4294967297)?;
    let Message::Trade(d) = msg else {
        return Err(format!(
            "message 3: expected Trade, got template {}",
            msg.template_id()
        ));
    };
    eq_u64("message 3.trade_id", d.trade_id(), 42u64)?;
    eq_u64(
        "message 3.aggressor_order_id",
        d.aggressor_order_id(),
        8589934595u64,
    )?;
    eq_u64(
        "message 3.resting_order_id",
        d.resting_order_id(),
        8589934593u64,
    )?;
    eq_i64("message 3.price", d.price(), 990000)?;
    eq_u32("message 3.quantity", d.quantity(), 400u32)?;
    eq_u16("message 3.symbol_id", d.symbol_id(), 3u16)?;
    if d.aggressor_side()
        .map_err(|e| format!("message 3.aggressor_side: {e}"))?
        != Side::Ask
    {
        return Err(format!(
            "message 3.aggressor_side: expected Side::Ask, got {:?}",
            d.aggressor_side()
        ));
    }

    // message 4
    let (seq, msg) = it
        .next()
        .ok_or_else(|| "message 4: missing".to_string())?
        .map_err(|e| format!("message 4: {e}"))?;
    eq_u64("message 4 sequence", seq, 4294967298)?;
    let Message::ModifyOrder(d) = msg else {
        return Err(format!(
            "message 4: expected ModifyOrder, got template {}",
            msg.template_id()
        ));
    };
    eq_u64("message 4.order_id", d.order_id(), 8589934593u64)?;
    eq_i64("message 4.new_price", d.new_price(), 990000)?;
    eq_u32("message 4.new_quantity", d.new_quantity(), 600u32)?;
    eq_u16("message 4.symbol_id", d.symbol_id(), 3u16)?;
    if d.side().map_err(|e| format!("message 4.side: {e}"))? != Side::Bid {
        return Err(format!(
            "message 4.side: expected Side::Bid, got {:?}",
            d.side()
        ));
    }
    if d.reason().map_err(|e| format!("message 4.reason: {e}"))? != ModifyReason::Reduce {
        return Err(format!(
            "message 4.reason: expected ModifyReason::Reduce, got {:?}",
            d.reason()
        ));
    }

    // message 5
    let (seq, msg) = it
        .next()
        .ok_or_else(|| "message 5: missing".to_string())?
        .map_err(|e| format!("message 5: {e}"))?;
    eq_u64("message 5 sequence", seq, 4294967299)?;
    let Message::Heartbeat(d) = msg else {
        return Err(format!(
            "message 5: expected Heartbeat, got template {}",
            msg.template_id()
        ));
    };
    eq_u64("message 5.last_sequence", d.last_sequence(), 4294967299u64)?;

    if it.next().is_some() {
        return Err("extra messages past messageCount".to_string());
    }
    Ok(())
}

/// Re-encodes `batch_mixed` from the same values `check_batch_mixed` asserts.
pub fn build_batch_mixed(out: &mut [u8]) -> Result<usize, WireError> {
    let mut w = PacketWriter::new(out, 0, 0, 4294967294, 1702361767298204934)?;
    w.add_order(8589934593, 990000, 1000, 3, Side::Bid)?;
    w.delete_order(8589934594, 3, Side::Ask)?;
    let n = {
        let mut e = SnapshotEncoder::start(w.tail(), 4294967295, 3, 0)?;
        e.push_order(8589934593, 990000, 1000, Side::Bid)?;
        e.push_order(8589934596, 990100, 400, Side::Ask)?;
        e.push_order(8589934597, 990200, 700, Side::Ask)?;
        e.finish()
    };
    w.commit(n)?;
    w.trade(42, 8589934595, 8589934593, 990000, 400, 3, Side::Ask)?;
    w.modify_order(8589934593, 990000, 600, 3, Side::Bid, ModifyReason::Reduce)?;
    w.heartbeat(4294967299)?;
    Ok(w.finish())
}

/// Prices are signed on the wire. Spreads, settlement marks and a few real contracts go below zero, and a decoder that reads the field as unsigned looks correct until the day one does.
pub fn check_negative_price(buf: &[u8]) -> Result<(), String> {
    let r = PacketReader::new(buf).map_err(|e| format!("packet header: {e}"))?;
    let h = r.header();
    eq_u16("packet.schemaId", h.schema_id(), 1)?;
    eq_u16("packet.version", h.version(), 1)?;
    eq_u16("packet.messageCount", h.message_count(), 1)?;
    eq_u8("packet.channel", h.channel(), 0)?;
    eq_u8("packet.flags", h.flags(), 0)?;
    eq_u64("packet.firstSequence", h.first_sequence(), 1048592)?;
    eq_u64(
        "packet.sendTimestampNs",
        h.send_timestamp_ns(),
        1702361767298204934,
    )?;
    eq_bool("packet.isSnapshot", h.is_snapshot(), false)?;

    let mut it = r.messages();
    // message 0
    let (seq, msg) = it
        .next()
        .ok_or_else(|| "message 0: missing".to_string())?
        .map_err(|e| format!("message 0: {e}"))?;
    eq_u64("message 0 sequence", seq, 1048592)?;
    let Message::AddOrder(d) = msg else {
        return Err(format!(
            "message 0: expected AddOrder, got template {}",
            msg.template_id()
        ));
    };
    eq_u64("message 0.order_id", d.order_id(), 12884901889u64)?;
    eq_i64("message 0.price", d.price(), -12500)?;
    eq_u32("message 0.quantity", d.quantity(), 5u32)?;
    eq_u16("message 0.symbol_id", d.symbol_id(), 11u16)?;
    if d.side().map_err(|e| format!("message 0.side: {e}"))? != Side::Ask {
        return Err(format!(
            "message 0.side: expected Side::Ask, got {:?}",
            d.side()
        ));
    }

    if it.next().is_some() {
        return Err("extra messages past messageCount".to_string());
    }
    Ok(())
}

/// Re-encodes `negative_price` from the same values `check_negative_price` asserts.
pub fn build_negative_price(out: &mut [u8]) -> Result<usize, WireError> {
    let mut w = PacketWriter::new(out, 0, 0, 1048592, 1702361767298204934)?;
    w.add_order(12884901889, -12500, 5, 11, Side::Ask)?;
    Ok(w.finish())
}

/// firstSequence near 2^64. The sequence of message i is firstSequence+i, so a reader that widens through i32 or i64 breaks here and nowhere else.
pub fn check_sequence_wrap_high(buf: &[u8]) -> Result<(), String> {
    let r = PacketReader::new(buf).map_err(|e| format!("packet header: {e}"))?;
    let h = r.header();
    eq_u16("packet.schemaId", h.schema_id(), 1)?;
    eq_u16("packet.version", h.version(), 1)?;
    eq_u16("packet.messageCount", h.message_count(), 2)?;
    eq_u8("packet.channel", h.channel(), 1)?;
    eq_u8("packet.flags", h.flags(), 0)?;
    eq_u64(
        "packet.firstSequence",
        h.first_sequence(),
        18446744073709551613,
    )?;
    eq_u64(
        "packet.sendTimestampNs",
        h.send_timestamp_ns(),
        1702361767298204934,
    )?;
    eq_bool("packet.isSnapshot", h.is_snapshot(), false)?;

    let mut it = r.messages();
    // message 0
    let (seq, msg) = it
        .next()
        .ok_or_else(|| "message 0: missing".to_string())?
        .map_err(|e| format!("message 0: {e}"))?;
    eq_u64("message 0 sequence", seq, 18446744073709551613)?;
    let Message::Heartbeat(d) = msg else {
        return Err(format!(
            "message 0: expected Heartbeat, got template {}",
            msg.template_id()
        ));
    };
    eq_u64(
        "message 0.last_sequence",
        d.last_sequence(),
        18446744073709551613u64,
    )?;

    // message 1
    let (seq, msg) = it
        .next()
        .ok_or_else(|| "message 1: missing".to_string())?
        .map_err(|e| format!("message 1: {e}"))?;
    eq_u64("message 1 sequence", seq, 18446744073709551614)?;
    let Message::Heartbeat(d) = msg else {
        return Err(format!(
            "message 1: expected Heartbeat, got template {}",
            msg.template_id()
        ));
    };
    eq_u64(
        "message 1.last_sequence",
        d.last_sequence(),
        18446744073709551614u64,
    )?;

    if it.next().is_some() {
        return Err("extra messages past messageCount".to_string());
    }
    Ok(())
}

/// Re-encodes `sequence_wrap_high` from the same values `check_sequence_wrap_high` asserts.
pub fn build_sequence_wrap_high(out: &mut [u8]) -> Result<usize, WireError> {
    let mut w = PacketWriter::new(out, 1, 0, 18446744073709551613, 1702361767298204934)?;
    w.heartbeat(18446744073709551613)?;
    w.heartbeat(18446744073709551614)?;
    Ok(w.finish())
}
