// @generated by schema/codegen.py from schema/market-data.xml -- do not edit.
//
// Edit the schema and run `make codegen`. CI regenerates and diffs, so a
// hand-edit here fails the build rather than silently surviving.

#pragma once

#include <bit>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <limits>
#include <optional>

namespace mdstack::wire {

static_assert(std::endian::native == std::endian::little,
              "This codec assumes a little-endian host. The wire format is little-endian; on a big-endian host every load_le would need a byteswap that has not been written or tested.");

inline constexpr std::uint16_t kSchemaId = 1;
inline constexpr std::uint16_t kSchemaVersion = 1;
inline constexpr std::int8_t kPriceExponent = -4;
inline constexpr std::size_t kPacketHeaderLen = 24;
inline constexpr std::size_t kMessageHeaderLen = 8;
inline constexpr std::size_t kGroupSizeEncodingLen = 4;
inline constexpr std::uint8_t kPacketFlagSnapshot = 0x01;
inline constexpr std::uint8_t kSnapshotFlagLastFragment = 0x01;
inline constexpr std::uint8_t kSnapshotFlagCycleEnd = 0x02;
inline constexpr std::uint8_t kSnapshotFlagCycleStart = 0x04;

namespace detail {

// Unaligned-safe. Messages are packed back to back inside a datagram, so a
// block can start at any byte offset; memcpy of a fixed size lowers to a
// single instruction and is the only well-defined way to do this in C++.
template <typename T>
[[nodiscard]] inline T load_le(const std::byte* p) noexcept {
    T v{};
    std::memcpy(&v, p, sizeof(T));
    return v;
}

template <typename T>
inline void store_le(std::byte* p, T v) noexcept {
    std::memcpy(p, &v, sizeof(T));
}

}  // namespace detail

enum class Side : std::uint8_t {
    kBid = 0,
    kAsk = 1,
};

[[nodiscard]] inline std::optional<Side> Side_from_raw(std::uint8_t v) noexcept {
    switch (v) {
        case 0: return Side::kBid;
        case 1: return Side::kAsk;
        default: return std::nullopt;
    }
}

enum class ModifyReason : std::uint8_t {
    kReduce = 0,
    kReplace = 1,
};

[[nodiscard]] inline std::optional<ModifyReason> ModifyReason_from_raw(std::uint8_t v) noexcept {
    switch (v) {
        case 0: return ModifyReason::kReduce;
        case 1: return ModifyReason::kReplace;
        default: return std::nullopt;
    }
}

namespace tmpl {
inline constexpr std::uint16_t kAddOrder = 1;
inline constexpr std::uint16_t kModifyOrder = 2;
inline constexpr std::uint16_t kDeleteOrder = 3;
inline constexpr std::uint16_t kTrade = 4;
inline constexpr std::uint16_t kSnapshot = 5;
inline constexpr std::uint16_t kHeartbeat = 6;
inline constexpr std::uint16_t kSequenceReset = 7;
}  // namespace tmpl

/// Read-only view over the datagram header.
class PacketHeaderDecoder {
  public:
    [[nodiscard]] static std::optional<PacketHeaderDecoder> wrap(const std::byte* p, std::size_t len) noexcept {
        if (len < kPacketHeaderLen) return std::nullopt;
        PacketHeaderDecoder d(p);
        if (d.schema_id() != kSchemaId) return std::nullopt;
        return d;
    }

    explicit PacketHeaderDecoder(const std::byte* p) noexcept : p_(p) {}

    /// Must equal the schema id; a mismatch is a hard reject
    [[nodiscard]] std::uint16_t schema_id() const noexcept { return detail::load_le<std::uint16_t>(p_ + 0); }
    /// Schema version the publisher encoded with
    [[nodiscard]] std::uint16_t version() const noexcept { return detail::load_le<std::uint16_t>(p_ + 2); }
    /// Number of messages packed into this datagram
    [[nodiscard]] std::uint16_t message_count() const noexcept { return detail::load_le<std::uint16_t>(p_ + 4); }
    /// 0 = feed A, 1 = feed B; diagnostic only, arbitration keys on sequence
    [[nodiscard]] std::uint8_t channel() const noexcept { return detail::load_le<std::uint8_t>(p_ + 6); }
    /// bit0 = this datagram is part of a snapshot cycle
    [[nodiscard]] std::uint8_t flags() const noexcept { return detail::load_le<std::uint8_t>(p_ + 7); }
    /// Sequence of the first message; message i is firstSequence + i
    [[nodiscard]] std::uint64_t first_sequence() const noexcept { return detail::load_le<std::uint64_t>(p_ + 8); }
    /// Publisher clock at send, nanoseconds since the Unix epoch
    [[nodiscard]] std::uint64_t send_timestamp_ns() const noexcept { return detail::load_le<std::uint64_t>(p_ + 16); }
    [[nodiscard]] bool is_snapshot() const noexcept { return (flags() & kPacketFlagSnapshot) != 0; }

  private:
    const std::byte* p_;
};

/// Writes the datagram header, leaving messageCount at zero.
[[nodiscard]] inline std::optional<std::size_t> encode_packet_header(
    std::byte* buf, std::size_t cap
    , std::uint8_t channel
    , std::uint8_t flags
    , std::uint64_t first_sequence
    , std::uint64_t send_timestamp_ns
) noexcept {
    if (cap < kPacketHeaderLen) return std::nullopt;
    std::memset(buf, 0, kPacketHeaderLen);
    detail::store_le<std::uint16_t>(buf + 0, kSchemaId);
    detail::store_le<std::uint16_t>(buf + 2, kSchemaVersion);
    detail::store_le<std::uint16_t>(buf + 4, 0);
    detail::store_le<std::uint8_t>(buf + 6, channel);
    detail::store_le<std::uint8_t>(buf + 7, flags);
    detail::store_le<std::uint64_t>(buf + 8, first_sequence);
    detail::store_le<std::uint64_t>(buf + 16, send_timestamp_ns);
    return kPacketHeaderLen;
}

inline bool patch_message_count(std::byte* buf, std::size_t cap,
                                std::uint16_t count) noexcept {
    if (cap < kPacketHeaderLen) return false;
    detail::store_le<std::uint16_t>(buf + 4, count);
    return true;
}

/// Read-only view over the message header.
class MessageHeaderDecoder {
  public:
    [[nodiscard]] static std::optional<MessageHeaderDecoder> wrap(const std::byte* p, std::size_t len) noexcept {
        if (len < kMessageHeaderLen) return std::nullopt;
        return MessageHeaderDecoder(p);
    }

    explicit MessageHeaderDecoder(const std::byte* p) noexcept : p_(p) {}

    /// Bytes of root block following this header, excluding any group
    [[nodiscard]] std::uint16_t block_length() const noexcept { return detail::load_le<std::uint16_t>(p_ + 0); }
    /// Which message this is
    [[nodiscard]] std::uint16_t template_id() const noexcept { return detail::load_le<std::uint16_t>(p_ + 2); }
    [[nodiscard]] std::uint16_t schema_id() const noexcept { return detail::load_le<std::uint16_t>(p_ + 4); }
    [[nodiscard]] std::uint16_t version() const noexcept { return detail::load_le<std::uint16_t>(p_ + 6); }

  private:
    const std::byte* p_;
};

namespace detail {
inline void write_message_header(std::byte* buf, std::uint16_t block_length,
                                 std::uint16_t template_id) noexcept {
    store_le<std::uint16_t>(buf + 0, block_length);
    store_le<std::uint16_t>(buf + 2, template_id);
    store_le<std::uint16_t>(buf + 4, kSchemaId);
    store_le<std::uint16_t>(buf + 6, kSchemaVersion);
}
}  // namespace detail

// --- AddOrder ------------------------------------------------------

/// A new order rests on the book
class AddOrderDecoder {
  public:
    static constexpr std::uint16_t kTemplateId = 1;
    static constexpr std::uint16_t kBlockLength = 24;

    /// Wraps a buffer whose first byte is the message header. The root
    /// block length comes from the wire so a newer publisher that
    /// appended fields is skipped rather than misparsed.
    [[nodiscard]] static std::optional<AddOrderDecoder> wrap(const std::byte* p, std::size_t len) noexcept {
        auto hdr = MessageHeaderDecoder::wrap(p, len);
        if (!hdr) return std::nullopt;
        if (hdr->template_id() != kTemplateId) return std::nullopt;
        const std::size_t root_len = hdr->block_length();
        if (root_len < kBlockLength) return std::nullopt;
        if (len < kMessageHeaderLen + root_len) return std::nullopt;
        AddOrderDecoder d(p, root_len);
        return d;
    }

    AddOrderDecoder(const std::byte* p, std::size_t root_len) noexcept
        : p_(p), root_len_(root_len) {}

    [[nodiscard]] std::uint64_t order_id() const noexcept { return detail::load_le<std::uint64_t>(p_ + kMessageHeaderLen); }
    /// Fixed point, scaled by 10^-4.
    [[nodiscard]] std::int64_t price() const noexcept { return detail::load_le<std::int64_t>(p_ + kMessageHeaderLen + 8); }
    [[nodiscard]] std::uint32_t quantity() const noexcept { return detail::load_le<std::uint32_t>(p_ + kMessageHeaderLen + 16); }
    [[nodiscard]] std::uint16_t symbol_id() const noexcept { return detail::load_le<std::uint16_t>(p_ + kMessageHeaderLen + 20); }
    [[nodiscard]] std::uint8_t side_raw() const noexcept { return detail::load_le<std::uint8_t>(p_ + kMessageHeaderLen + 22); }
    /// Validating accessor; returns nullopt on an undefined value.
    [[nodiscard]] std::optional<Side> side() const noexcept { return Side_from_raw(side_raw()); }

    [[nodiscard]] std::size_t total_len() const noexcept { return kMessageHeaderLen + root_len_; }

  private:
    const std::byte* p_;
    std::size_t root_len_;
};

/// Encodes a `AddOrder` at `buf[0]`, header included. Reserved bytes
/// are zeroed, which is what makes a re-encode byte-identical.
[[nodiscard]] inline std::optional<std::size_t> encode_add_order(
    std::byte* buf, std::size_t cap
    , std::uint64_t order_id
    , std::int64_t price
    , std::uint32_t quantity
    , std::uint16_t symbol_id
    , Side side
) noexcept {
    constexpr std::size_t kLen = kMessageHeaderLen + 24;
    if (cap < kLen) return std::nullopt;
    std::memset(buf, 0, kLen);
    detail::write_message_header(buf, 24, tmpl::kAddOrder);
    detail::store_le<std::uint64_t>(buf + kMessageHeaderLen, order_id);
    detail::store_le<std::int64_t>(buf + kMessageHeaderLen + 8, price);
    detail::store_le<std::uint32_t>(buf + kMessageHeaderLen + 16, quantity);
    detail::store_le<std::uint16_t>(buf + kMessageHeaderLen + 20, symbol_id);
    detail::store_le<std::uint8_t>(buf + kMessageHeaderLen + 22, static_cast<std::uint8_t>(side));
    return kLen;
}

// --- ModifyOrder ---------------------------------------------------

/// A resting order changes price or quantity
class ModifyOrderDecoder {
  public:
    static constexpr std::uint16_t kTemplateId = 2;
    static constexpr std::uint16_t kBlockLength = 24;

    /// Wraps a buffer whose first byte is the message header. The root
    /// block length comes from the wire so a newer publisher that
    /// appended fields is skipped rather than misparsed.
    [[nodiscard]] static std::optional<ModifyOrderDecoder> wrap(const std::byte* p, std::size_t len) noexcept {
        auto hdr = MessageHeaderDecoder::wrap(p, len);
        if (!hdr) return std::nullopt;
        if (hdr->template_id() != kTemplateId) return std::nullopt;
        const std::size_t root_len = hdr->block_length();
        if (root_len < kBlockLength) return std::nullopt;
        if (len < kMessageHeaderLen + root_len) return std::nullopt;
        ModifyOrderDecoder d(p, root_len);
        return d;
    }

    ModifyOrderDecoder(const std::byte* p, std::size_t root_len) noexcept
        : p_(p), root_len_(root_len) {}

    [[nodiscard]] std::uint64_t order_id() const noexcept { return detail::load_le<std::uint64_t>(p_ + kMessageHeaderLen); }
    /// Fixed point, scaled by 10^-4.
    [[nodiscard]] std::int64_t new_price() const noexcept { return detail::load_le<std::int64_t>(p_ + kMessageHeaderLen + 8); }
    [[nodiscard]] std::uint32_t new_quantity() const noexcept { return detail::load_le<std::uint32_t>(p_ + kMessageHeaderLen + 16); }
    [[nodiscard]] std::uint16_t symbol_id() const noexcept { return detail::load_le<std::uint16_t>(p_ + kMessageHeaderLen + 20); }
    [[nodiscard]] std::uint8_t side_raw() const noexcept { return detail::load_le<std::uint8_t>(p_ + kMessageHeaderLen + 22); }
    /// Validating accessor; returns nullopt on an undefined value.
    [[nodiscard]] std::optional<Side> side() const noexcept { return Side_from_raw(side_raw()); }
    [[nodiscard]] std::uint8_t reason_raw() const noexcept { return detail::load_le<std::uint8_t>(p_ + kMessageHeaderLen + 23); }
    /// Validating accessor; returns nullopt on an undefined value.
    [[nodiscard]] std::optional<ModifyReason> reason() const noexcept { return ModifyReason_from_raw(reason_raw()); }

    [[nodiscard]] std::size_t total_len() const noexcept { return kMessageHeaderLen + root_len_; }

  private:
    const std::byte* p_;
    std::size_t root_len_;
};

/// Encodes a `ModifyOrder` at `buf[0]`, header included. Reserved bytes
/// are zeroed, which is what makes a re-encode byte-identical.
[[nodiscard]] inline std::optional<std::size_t> encode_modify_order(
    std::byte* buf, std::size_t cap
    , std::uint64_t order_id
    , std::int64_t new_price
    , std::uint32_t new_quantity
    , std::uint16_t symbol_id
    , Side side
    , ModifyReason reason
) noexcept {
    constexpr std::size_t kLen = kMessageHeaderLen + 24;
    if (cap < kLen) return std::nullopt;
    std::memset(buf, 0, kLen);
    detail::write_message_header(buf, 24, tmpl::kModifyOrder);
    detail::store_le<std::uint64_t>(buf + kMessageHeaderLen, order_id);
    detail::store_le<std::int64_t>(buf + kMessageHeaderLen + 8, new_price);
    detail::store_le<std::uint32_t>(buf + kMessageHeaderLen + 16, new_quantity);
    detail::store_le<std::uint16_t>(buf + kMessageHeaderLen + 20, symbol_id);
    detail::store_le<std::uint8_t>(buf + kMessageHeaderLen + 22, static_cast<std::uint8_t>(side));
    detail::store_le<std::uint8_t>(buf + kMessageHeaderLen + 23, static_cast<std::uint8_t>(reason));
    return kLen;
}

// --- DeleteOrder ---------------------------------------------------

/// A resting order leaves the book
class DeleteOrderDecoder {
  public:
    static constexpr std::uint16_t kTemplateId = 3;
    static constexpr std::uint16_t kBlockLength = 12;

    /// Wraps a buffer whose first byte is the message header. The root
    /// block length comes from the wire so a newer publisher that
    /// appended fields is skipped rather than misparsed.
    [[nodiscard]] static std::optional<DeleteOrderDecoder> wrap(const std::byte* p, std::size_t len) noexcept {
        auto hdr = MessageHeaderDecoder::wrap(p, len);
        if (!hdr) return std::nullopt;
        if (hdr->template_id() != kTemplateId) return std::nullopt;
        const std::size_t root_len = hdr->block_length();
        if (root_len < kBlockLength) return std::nullopt;
        if (len < kMessageHeaderLen + root_len) return std::nullopt;
        DeleteOrderDecoder d(p, root_len);
        return d;
    }

    DeleteOrderDecoder(const std::byte* p, std::size_t root_len) noexcept
        : p_(p), root_len_(root_len) {}

    [[nodiscard]] std::uint64_t order_id() const noexcept { return detail::load_le<std::uint64_t>(p_ + kMessageHeaderLen); }
    [[nodiscard]] std::uint16_t symbol_id() const noexcept { return detail::load_le<std::uint16_t>(p_ + kMessageHeaderLen + 8); }
    [[nodiscard]] std::uint8_t side_raw() const noexcept { return detail::load_le<std::uint8_t>(p_ + kMessageHeaderLen + 10); }
    /// Validating accessor; returns nullopt on an undefined value.
    [[nodiscard]] std::optional<Side> side() const noexcept { return Side_from_raw(side_raw()); }

    [[nodiscard]] std::size_t total_len() const noexcept { return kMessageHeaderLen + root_len_; }

  private:
    const std::byte* p_;
    std::size_t root_len_;
};

/// Encodes a `DeleteOrder` at `buf[0]`, header included. Reserved bytes
/// are zeroed, which is what makes a re-encode byte-identical.
[[nodiscard]] inline std::optional<std::size_t> encode_delete_order(
    std::byte* buf, std::size_t cap
    , std::uint64_t order_id
    , std::uint16_t symbol_id
    , Side side
) noexcept {
    constexpr std::size_t kLen = kMessageHeaderLen + 12;
    if (cap < kLen) return std::nullopt;
    std::memset(buf, 0, kLen);
    detail::write_message_header(buf, 12, tmpl::kDeleteOrder);
    detail::store_le<std::uint64_t>(buf + kMessageHeaderLen, order_id);
    detail::store_le<std::uint16_t>(buf + kMessageHeaderLen + 8, symbol_id);
    detail::store_le<std::uint8_t>(buf + kMessageHeaderLen + 10, static_cast<std::uint8_t>(side));
    return kLen;
}

// --- Trade ---------------------------------------------------------

/// An aggressing order crossed with a resting order
class TradeDecoder {
  public:
    static constexpr std::uint16_t kTemplateId = 4;
    static constexpr std::uint16_t kBlockLength = 40;

    /// Wraps a buffer whose first byte is the message header. The root
    /// block length comes from the wire so a newer publisher that
    /// appended fields is skipped rather than misparsed.
    [[nodiscard]] static std::optional<TradeDecoder> wrap(const std::byte* p, std::size_t len) noexcept {
        auto hdr = MessageHeaderDecoder::wrap(p, len);
        if (!hdr) return std::nullopt;
        if (hdr->template_id() != kTemplateId) return std::nullopt;
        const std::size_t root_len = hdr->block_length();
        if (root_len < kBlockLength) return std::nullopt;
        if (len < kMessageHeaderLen + root_len) return std::nullopt;
        TradeDecoder d(p, root_len);
        return d;
    }

    TradeDecoder(const std::byte* p, std::size_t root_len) noexcept
        : p_(p), root_len_(root_len) {}

    [[nodiscard]] std::uint64_t trade_id() const noexcept { return detail::load_le<std::uint64_t>(p_ + kMessageHeaderLen); }
    [[nodiscard]] std::uint64_t aggressor_order_id() const noexcept { return detail::load_le<std::uint64_t>(p_ + kMessageHeaderLen + 8); }
    [[nodiscard]] std::uint64_t resting_order_id() const noexcept { return detail::load_le<std::uint64_t>(p_ + kMessageHeaderLen + 16); }
    /// Fixed point, scaled by 10^-4.
    [[nodiscard]] std::int64_t price() const noexcept { return detail::load_le<std::int64_t>(p_ + kMessageHeaderLen + 24); }
    [[nodiscard]] std::uint32_t quantity() const noexcept { return detail::load_le<std::uint32_t>(p_ + kMessageHeaderLen + 32); }
    [[nodiscard]] std::uint16_t symbol_id() const noexcept { return detail::load_le<std::uint16_t>(p_ + kMessageHeaderLen + 36); }
    [[nodiscard]] std::uint8_t aggressor_side_raw() const noexcept { return detail::load_le<std::uint8_t>(p_ + kMessageHeaderLen + 38); }
    /// Validating accessor; returns nullopt on an undefined value.
    [[nodiscard]] std::optional<Side> aggressor_side() const noexcept { return Side_from_raw(aggressor_side_raw()); }

    [[nodiscard]] std::size_t total_len() const noexcept { return kMessageHeaderLen + root_len_; }

  private:
    const std::byte* p_;
    std::size_t root_len_;
};

/// Encodes a `Trade` at `buf[0]`, header included. Reserved bytes
/// are zeroed, which is what makes a re-encode byte-identical.
[[nodiscard]] inline std::optional<std::size_t> encode_trade(
    std::byte* buf, std::size_t cap
    , std::uint64_t trade_id
    , std::uint64_t aggressor_order_id
    , std::uint64_t resting_order_id
    , std::int64_t price
    , std::uint32_t quantity
    , std::uint16_t symbol_id
    , Side aggressor_side
) noexcept {
    constexpr std::size_t kLen = kMessageHeaderLen + 40;
    if (cap < kLen) return std::nullopt;
    std::memset(buf, 0, kLen);
    detail::write_message_header(buf, 40, tmpl::kTrade);
    detail::store_le<std::uint64_t>(buf + kMessageHeaderLen, trade_id);
    detail::store_le<std::uint64_t>(buf + kMessageHeaderLen + 8, aggressor_order_id);
    detail::store_le<std::uint64_t>(buf + kMessageHeaderLen + 16, resting_order_id);
    detail::store_le<std::int64_t>(buf + kMessageHeaderLen + 24, price);
    detail::store_le<std::uint32_t>(buf + kMessageHeaderLen + 32, quantity);
    detail::store_le<std::uint16_t>(buf + kMessageHeaderLen + 36, symbol_id);
    detail::store_le<std::uint8_t>(buf + kMessageHeaderLen + 38, static_cast<std::uint8_t>(aggressor_side));
    return kLen;
}

// --- Snapshot ------------------------------------------------------

/// Full book state for one symbol, consistent as of lastSequence
class SnapshotDecoder {
  public:
    static constexpr std::uint16_t kTemplateId = 5;
    static constexpr std::uint16_t kBlockLength = 12;

    /// Wraps a buffer whose first byte is the message header. The root
    /// block length comes from the wire so a newer publisher that
    /// appended fields is skipped rather than misparsed.
    [[nodiscard]] static std::optional<SnapshotDecoder> wrap(const std::byte* p, std::size_t len) noexcept {
        auto hdr = MessageHeaderDecoder::wrap(p, len);
        if (!hdr) return std::nullopt;
        if (hdr->template_id() != kTemplateId) return std::nullopt;
        const std::size_t root_len = hdr->block_length();
        if (root_len < kBlockLength) return std::nullopt;
        if (len < kMessageHeaderLen + root_len) return std::nullopt;
        SnapshotDecoder d(p, root_len);
        // total_len() reads the group header, so prove it is there first.
        if (len < kMessageHeaderLen + root_len + kGroupSizeEncodingLen)
            return std::nullopt;
        if (len < d.total_len()) return std::nullopt;
        return d;
    }

    SnapshotDecoder(const std::byte* p, std::size_t root_len) noexcept
        : p_(p), root_len_(root_len) {}

    /// The snapshot reflects every message up to and including this sequence
    [[nodiscard]] std::uint64_t last_sequence() const noexcept { return detail::load_le<std::uint64_t>(p_ + kMessageHeaderLen); }
    [[nodiscard]] std::uint16_t symbol_id() const noexcept { return detail::load_le<std::uint16_t>(p_ + kMessageHeaderLen + 8); }
    /// bit0 = last fragment for this symbol in this cycle
    [[nodiscard]] std::uint8_t flags() const noexcept { return detail::load_le<std::uint8_t>(p_ + kMessageHeaderLen + 10); }

    /// One entry of the `orders` group.
    class Order {
      public:
        static constexpr std::uint16_t kBlockLength = 24;
        explicit Order(const std::byte* p) noexcept : p_(p) {}
        [[nodiscard]] std::uint64_t order_id() const noexcept { return detail::load_le<std::uint64_t>(p_ + 0); }
        /// Fixed point, scaled by 10^-4.
        [[nodiscard]] std::int64_t price() const noexcept { return detail::load_le<std::int64_t>(p_ + 8); }
        [[nodiscard]] std::uint32_t quantity() const noexcept { return detail::load_le<std::uint32_t>(p_ + 16); }
        [[nodiscard]] std::uint8_t side_raw() const noexcept { return detail::load_le<std::uint8_t>(p_ + 20); }
        /// Validating accessor; returns nullopt on an undefined value.
        [[nodiscard]] std::optional<Side> side() const noexcept { return Side_from_raw(side_raw()); }

      private:
        const std::byte* p_;
    };

    [[nodiscard]] std::uint16_t orders_block_length() const noexcept {
        return detail::load_le<std::uint16_t>(p_ + kMessageHeaderLen + root_len_);
    }

    [[nodiscard]] std::uint16_t orders_count() const noexcept {
        return detail::load_le<std::uint16_t>(p_ + kMessageHeaderLen + root_len_ + 2);
    }

    /// Entry `i` of the `orders` group. Caller checks `i` against the count.
    [[nodiscard]] Order order(std::uint16_t i) const noexcept {
        const std::size_t base = kMessageHeaderLen + root_len_ +
                                 kGroupSizeEncodingLen + static_cast<std::size_t>(i) * orders_block_length();
        return Order(p_ + base);
    }

    [[nodiscard]] std::size_t total_len() const noexcept {
        return kMessageHeaderLen + root_len_ + kGroupSizeEncodingLen +
               static_cast<std::size_t>(orders_count()) * orders_block_length();
    }

  private:
    const std::byte* p_;
    std::size_t root_len_;
};

/// Two-phase encoder for `Snapshot`, which carries a repeating group.
class SnapshotEncoder {
  public:
    [[nodiscard]] static std::optional<SnapshotEncoder> start(
        std::byte* buf, std::size_t cap
        , std::uint64_t last_sequence
        , std::uint16_t symbol_id
        , std::uint8_t flags
    ) noexcept {
        constexpr std::size_t kHead = kMessageHeaderLen + 12 + kGroupSizeEncodingLen;
        if (cap < kHead) return std::nullopt;
        std::memset(buf, 0, kHead);
        detail::write_message_header(buf, 12, tmpl::kSnapshot);
        detail::store_le<std::uint64_t>(buf + kMessageHeaderLen, last_sequence);
        detail::store_le<std::uint16_t>(buf + kMessageHeaderLen + 8, symbol_id);
        detail::store_le<std::uint8_t>(buf + kMessageHeaderLen + 10, flags);
        detail::store_le<std::uint16_t>(buf + kMessageHeaderLen + 12, 24);
        return SnapshotEncoder(buf, cap, kHead);
    }

    /// Appends one `orders` entry.
    [[nodiscard]] bool push_order(
        std::uint64_t order_id
        , std::int64_t price
        , std::uint32_t quantity
        , Side side
    ) noexcept {
        constexpr std::size_t kEntry = 24;
        if (pos_ + kEntry > cap_) return false;
        if (count_ == std::numeric_limits<std::uint16_t>::max()) return false;
        std::byte* e = buf_ + pos_;
        std::memset(e, 0, kEntry);
        detail::store_le<std::uint64_t>(e + 0, order_id);
        detail::store_le<std::int64_t>(e + 8, price);
        detail::store_le<std::uint32_t>(e + 16, quantity);
        detail::store_le<std::uint8_t>(e + 20, static_cast<std::uint8_t>(side));
        pos_ += kEntry;
        ++count_;
        return true;
    }

    /// Patches the group count and returns the total bytes written.
    [[nodiscard]] std::size_t finish() noexcept {
        detail::store_le<std::uint16_t>(buf_ + kMessageHeaderLen + 12 + 2, count_);
        return pos_;
    }

  private:
    SnapshotEncoder(std::byte* buf, std::size_t cap, std::size_t pos) noexcept
        : buf_(buf), cap_(cap), pos_(pos) {}

    std::byte* buf_;
    std::size_t cap_;
    std::size_t pos_;
    std::uint16_t count_ = 0;
};

// --- Heartbeat -----------------------------------------------------

/// Published on an idle channel so a handler can tell quiet from dead
class HeartbeatDecoder {
  public:
    static constexpr std::uint16_t kTemplateId = 6;
    static constexpr std::uint16_t kBlockLength = 8;

    /// Wraps a buffer whose first byte is the message header. The root
    /// block length comes from the wire so a newer publisher that
    /// appended fields is skipped rather than misparsed.
    [[nodiscard]] static std::optional<HeartbeatDecoder> wrap(const std::byte* p, std::size_t len) noexcept {
        auto hdr = MessageHeaderDecoder::wrap(p, len);
        if (!hdr) return std::nullopt;
        if (hdr->template_id() != kTemplateId) return std::nullopt;
        const std::size_t root_len = hdr->block_length();
        if (root_len < kBlockLength) return std::nullopt;
        if (len < kMessageHeaderLen + root_len) return std::nullopt;
        HeartbeatDecoder d(p, root_len);
        return d;
    }

    HeartbeatDecoder(const std::byte* p, std::size_t root_len) noexcept
        : p_(p), root_len_(root_len) {}

    /// Highest sequence published so far on this channel
    [[nodiscard]] std::uint64_t last_sequence() const noexcept { return detail::load_le<std::uint64_t>(p_ + kMessageHeaderLen); }

    [[nodiscard]] std::size_t total_len() const noexcept { return kMessageHeaderLen + root_len_; }

  private:
    const std::byte* p_;
    std::size_t root_len_;
};

/// Encodes a `Heartbeat` at `buf[0]`, header included. Reserved bytes
/// are zeroed, which is what makes a re-encode byte-identical.
[[nodiscard]] inline std::optional<std::size_t> encode_heartbeat(
    std::byte* buf, std::size_t cap
    , std::uint64_t last_sequence
) noexcept {
    constexpr std::size_t kLen = kMessageHeaderLen + 8;
    if (cap < kLen) return std::nullopt;
    std::memset(buf, 0, kLen);
    detail::write_message_header(buf, 8, tmpl::kHeartbeat);
    detail::store_le<std::uint64_t>(buf + kMessageHeaderLen, last_sequence);
    return kLen;
}

// --- SequenceReset -------------------------------------------------

/// The publisher restarts its sequence; the handler must resynchronise
class SequenceResetDecoder {
  public:
    static constexpr std::uint16_t kTemplateId = 7;
    static constexpr std::uint16_t kBlockLength = 8;

    /// Wraps a buffer whose first byte is the message header. The root
    /// block length comes from the wire so a newer publisher that
    /// appended fields is skipped rather than misparsed.
    [[nodiscard]] static std::optional<SequenceResetDecoder> wrap(const std::byte* p, std::size_t len) noexcept {
        auto hdr = MessageHeaderDecoder::wrap(p, len);
        if (!hdr) return std::nullopt;
        if (hdr->template_id() != kTemplateId) return std::nullopt;
        const std::size_t root_len = hdr->block_length();
        if (root_len < kBlockLength) return std::nullopt;
        if (len < kMessageHeaderLen + root_len) return std::nullopt;
        SequenceResetDecoder d(p, root_len);
        return d;
    }

    SequenceResetDecoder(const std::byte* p, std::size_t root_len) noexcept
        : p_(p), root_len_(root_len) {}

    /// The sequence the next message will carry
    [[nodiscard]] std::uint64_t new_sequence() const noexcept { return detail::load_le<std::uint64_t>(p_ + kMessageHeaderLen); }

    [[nodiscard]] std::size_t total_len() const noexcept { return kMessageHeaderLen + root_len_; }

  private:
    const std::byte* p_;
    std::size_t root_len_;
};

/// Encodes a `SequenceReset` at `buf[0]`, header included. Reserved bytes
/// are zeroed, which is what makes a re-encode byte-identical.
[[nodiscard]] inline std::optional<std::size_t> encode_sequence_reset(
    std::byte* buf, std::size_t cap
    , std::uint64_t new_sequence
) noexcept {
    constexpr std::size_t kLen = kMessageHeaderLen + 8;
    if (cap < kLen) return std::nullopt;
    std::memset(buf, 0, kLen);
    detail::write_message_header(buf, 8, tmpl::kSequenceReset);
    detail::store_le<std::uint64_t>(buf + kMessageHeaderLen, new_sequence);
    return kLen;
}

}  // namespace mdstack::wire
